import { FamilyMember, Appointment, Recipe, MealPlanDay, PhotoMemory, GalleryAlbum, GroceryItem, Chore, PinnedNote, StoreDefinition } from '../types';

// Helper to get formatted dates relative to today
const getRelativeDate = (offsetDays: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const INITIAL_MEMBERS: FamilyMember[] = [
  {
    id: 'm1',
    name: 'Sarah',
    role: 'Mama',
    avatar: '👩‍💼',
    color: '#EC4899',
    bgLight: 'bg-pink-50',
    borderClass: 'border-pink-300',
    textClass: 'text-pink-700',
    birthday: '1986-05-14',
    notes: 'Kinderärztin, liebt Laufen am Wochenende & Cappuccino',
    pin: '1234',
    isChild: false,
    customFields: [
      { id: 'cf_s1', label: 'Arbeit / Klinik', value: 'Kinderklinik (Abt. 3)', category: 'other' },
      { id: 'cf_s2', label: 'Blutgruppe', value: '0+', category: 'health' },
    ],
  },
  {
    id: 'm2',
    name: 'Alex',
    role: 'Papa',
    avatar: '👨‍💻',
    color: '#0D9488',
    bgLight: 'bg-teal-50',
    borderClass: 'border-teal-300',
    textClass: 'text-teal-700',
    birthday: '1984-11-20',
    notes: 'Landschaftsarchitekt, Grill-Chef am Wochenende',
    pin: '1234',
    isChild: false,
    customFields: [
      { id: 'cf_a1', label: 'Krankenkasse', value: 'Techniker Krankenkasse (TK) #8194', category: 'health' },
      { id: 'cf_a2', label: 'Blutgruppe', value: 'A+', category: 'health' },
    ],
  },
  {
    id: 'm3',
    name: 'Leo',
    role: 'Sohn (12)',
    avatar: '⚽',
    color: '#F59E0B',
    bgLight: 'bg-amber-50',
    borderClass: 'border-amber-300',
    textClass: 'text-amber-700',
    birthday: '2014-03-08',
    notes: 'Mittelfeldspieler im Fußballverein, Programmier-AG',
    isChild: true,
    childDetails: {
      clothingSize: 'Größe 152 (12-14 J.)',
      shoeSize: 'EU 39',
      pantsSize: '152 Regular',
      doctorName: 'Dr. Emily Hayes (Kinderärztin)',
      doctorPhone: '089 342-9100',
      doctorAddress: 'Blütenstraße 42, 80331 München',
      dentistName: 'Dr. Peter Vance (Zahnarzt)',
      dentistPhone: '089 883-2040',
      dentistAddress: 'Flußgasse 10',
      allergies: 'Leichter Heuschnupfen / Frühblüher',
      bloodType: 'A+',
      schoolName: 'Gymnasium Schillerstraße',
      grade: '7. Klasse (Zimmer 204)',
      emergencyContact: 'Sarah Baum (Mama): 0171 7124401',
      customFields: [
        { id: 'cfl_1', label: 'Fahrradhelm', value: '54-58 cm', category: 'sizes' },
        { id: 'cfl_2', label: 'Vereinsnummer', value: 'FC West #9041', category: 'school' },
        { id: 'cfl_3', label: 'Schienbeinschoner', value: 'Größe M', category: 'sizes' },
      ],
    },
  },
  {
    id: 'm4',
    name: 'Mia',
    role: 'Tochter (8)',
    avatar: '🎨',
    color: '#8B5CF6',
    bgLight: 'bg-purple-50',
    borderClass: 'border-purple-300',
    textClass: 'text-purple-700',
    birthday: '2018-09-02',
    notes: 'Geräteturnen, Comics zeichnen, liebt Pfannkuchen',
    isChild: true,
    childDetails: {
      clothingSize: 'Größe 128 (8-10 J.)',
      shoeSize: 'EU 34',
      pantsSize: '128 Slim',
      doctorName: 'Dr. Emily Hayes (Kinderärztin)',
      doctorPhone: '089 342-9100',
      doctorAddress: 'Blütenstraße 42, 80331 München',
      dentistName: 'Dr. Peter Vance (Zahnarzt)',
      dentistPhone: '089 883-2040',
      dentistAddress: 'Flußgasse 10',
      allergies: 'Keine bekannten Allergien',
      bloodType: '0+',
      schoolName: 'Grundschule am Park',
      grade: '3. Klasse',
      emergencyContact: 'Alex Baum (Papa): 0172 9482309',
      customFields: [
        { id: 'cfm_1', label: 'Turnanzug', value: 'Größe 128', category: 'sizes' },
        { id: 'cfm_2', label: 'Schwimmabzeichen', value: 'Bronze (Freischwimmer)', category: 'school' },
        { id: 'cfm_3', label: 'Lieblingsfarbe', value: 'Himmelblau & Flieder', category: 'other' },
      ],
    },
  },
  {
    id: 'm5',
    name: 'Oma Elena',
    role: 'Oma',
    avatar: '👵',
    color: '#3B82F6',
    bgLight: 'bg-blue-50',
    borderClass: 'border-blue-300',
    textClass: 'text-blue-700',
    birthday: '1955-08-19',
    notes: 'Back-Meisterin, Gartenexpertin, Familien-Erzählerin',
    isChild: false,
    customFields: [
      { id: 'cfg_1', label: 'Hausarzt', value: 'Dr. Robert Martinez (089 602-1818)', category: 'health' },
      { id: 'cfg_2', label: 'Wichtiger Hinweis', value: 'Penicillin-Allergie', category: 'health' },
      { id: 'cfg_3', label: 'Zahnarzt', value: 'Dr. Peter Vance', category: 'health' },
    ],
  },
];

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: 'r1',
    title: 'Cremige Zitronen-Kräuter-Pasta mit Kirschtomaten',
    prepTime: '20 Min.',
    servings: 5,
    category: 'quick',
    theme: 'fresh',
    isFavorite: true,
    mainProtein: 'pasta',
    estimatedCost: 11.5,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Super schnelles Abendessen unter der Woche. Leo liebt extra viel Parmesan darauf!',
    ingredients: [
      { name: 'Fettuccine oder Tagliatelle', amount: '500g', category: 'pantry' },
      { name: 'Kirschtomaten', amount: '250g', category: 'produce' },
      { name: 'Frisches Basilikum', amount: '1 Bund', category: 'produce' },
      { name: 'Sahne oder Mascarpone', amount: '200ml', category: 'dairy' },
      { name: 'Parmesankäse', amount: '100g', category: 'dairy' },
      { name: 'Bio-Zitronen', amount: '2 Stück', category: 'produce' },
      { name: 'Knoblauchzehen', amount: '3 Zehen', category: 'produce' },
    ],
  },
  {
    id: 'r2',
    title: 'Knusprige Ofenblech-Hähnchen-Tacos',
    prepTime: '30 Min.',
    servings: 5,
    category: 'family-favorite',
    theme: 'kids',
    isFavorite: true,
    mainProtein: 'poultry',
    estimatedCost: 16.0,
    synergyBase: 'chicken',
    synergyRole: 'cook-extra',
    synergyTip: 'Brate heute 200g mehr Hähnchen: Morgen perfekt für Chicken Wraps oder Salad (-15 Min.)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    notes: 'Taco-Dienstag Tradition! Alle Zutaten auf den Tisch stellen zum Selberbelegen.',
    ingredients: [
      { name: 'Hähnchenbrustfilet', amount: '700g', category: 'meat' },
      { name: 'Mais-Tortillas', amount: '1 Packung (12 Stk)', category: 'bakery' },
      { name: 'Avocados (Guacamole)', amount: '3 reife', category: 'produce' },
      { name: 'Limetten', amount: '2 Stück', category: 'produce' },
      { name: 'Geriebener Käse', amount: '150g', category: 'dairy' },
      { name: 'Schmand oder Sauerrahm', amount: '1 Becher', category: 'dairy' },
      { name: 'Taco-Gewürzmischung', amount: '1 Pck.', category: 'pantry' },
    ],
  },
  {
    id: 'r3',
    title: 'Oma Elenas Goldener Hähnchen-Gemüse-Topf',
    prepTime: '50 Min.',
    servings: 6,
    category: 'comfort',
    theme: 'warming',
    isFavorite: false,
    mainProtein: 'poultry',
    estimatedCost: 15.5,
    imageUrl: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=600&q=80',
    notes: 'Perfektes Sonntagsessen für die ganze Familie mit knuspriger Blätterteighaube.',
    ingredients: [
      { name: 'Blätterteig (Kühlregal)', amount: '2 Rollen', category: 'bakery' },
      { name: 'Hähnchenfleisch', amount: '600g', category: 'meat' },
      { name: 'Möhren & Erbsen', amount: '300g', category: 'produce' },
      { name: 'Kartoffeln', amount: '4 mittelgroße', category: 'produce' },
      { name: 'Hühnerbrühe', amount: '500ml', category: 'pantry' },
      { name: 'Butter', amount: '50g', category: 'dairy' },
    ],
  },
  {
    id: 'r4',
    title: 'Hausgemachte Steinofen-Pizza Margherita',
    prepTime: '25 Min.',
    servings: 5,
    category: 'family-favorite',
    theme: 'kids',
    isFavorite: true,
    mainProtein: 'vegetarian',
    estimatedCost: 11.0,
    imageUrl: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=600&q=80',
    notes: 'Freitagabend ist Pizza-Abend! Mia legt gern Smileys mit Basilikumblättern.',
    ingredients: [
      { name: 'Pizzateig', amount: '2 Rollen / Kugeln', category: 'bakery' },
      { name: 'San Marzano Tomatensauce', amount: '1 Glas', category: 'pantry' },
      { name: 'Frischer Mozzarella', amount: '3 Kugeln', category: 'dairy' },
      { name: 'Frisches Basilikum', amount: '1 Bund', category: 'produce' },
      { name: 'Natives Olivenöl extra', amount: '1 Flasche', category: 'pantry' },
    ],
  },
  {
    id: 'r5',
    title: 'Fluffige Samstagmorgen Beeren-Pancakes',
    prepTime: '20 Min.',
    servings: 5,
    category: 'baking',
    theme: 'kids',
    isFavorite: false,
    mainProtein: 'vegetarian',
    estimatedCost: 9.5,
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=600&q=80',
    notes: 'Wochenend-Frühstück mit echtem Ahornsirup und frischen Beeren.',
    ingredients: [
      { name: 'Weizenmehl', amount: '400g', category: 'pantry' },
      { name: 'Bio-Vollmilch', amount: '1 Liter', category: 'dairy' },
      { name: 'Frische Blaubeeren & Erdbeeren', amount: '2 Schalen', category: 'produce' },
      { name: 'Reiner Ahornsirup', amount: '1 Flasche', category: 'pantry' },
      { name: 'Eier', amount: '6er-Pack', category: 'dairy' },
    ],
  },
  {
    id: 'r6',
    title: 'Honig-Lachs mit knackigem Brokkoli & Jasminreis',
    prepTime: '25 Min.',
    servings: 5,
    category: 'healthy',
    theme: 'healthy',
    isFavorite: true,
    mainProtein: 'fish',
    estimatedCost: 17.5,
    synergyBase: 'rice',
    synergyRole: 'cook-extra',
    synergyTip: 'Koche heute 500g Reis: Morgen gibt es blitzschnellen gebratenen Eierreis (-15 Min. Kochzeit)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    notes: 'Frischer Lachs mit süß-würziger Glasur, gedämpftem Brokkoli und duftendem Reis.',
    ingredients: [
      { name: 'Lachsfilet (frisch)', amount: '600g', category: 'meat' },
      { name: 'Frischer Brokkoli', amount: '500g', category: 'produce' },
      { name: 'Jasminreis', amount: '500g', category: 'pantry' },
      { name: 'Bio-Honig & Sojasauce', amount: 'je 3 EL', category: 'pantry' },
      { name: 'Frischer Knoblauch & Ingwer', amount: '1 Knolle / Stück', category: 'produce' },
      { name: 'Sesamöl', amount: '2 EL', category: 'pantry' },
    ],
  },
  {
    id: 'r7',
    title: 'Herzhafter Schmortopf mit Kartoffeln & Maisbrot',
    prepTime: '45 Min.',
    servings: 5,
    category: 'comfort',
    theme: 'warming',
    isFavorite: false,
    mainProtein: 'meat',
    estimatedCost: 15.0,
    synergyBase: 'potatoes',
    synergyRole: 'cook-extra',
    synergyTip: 'Koche extra Kartoffeln mit: Das spart morgen 20 Min. für knusprige Bratkartoffeln!',
    timeSavedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80',
    notes: 'Wärmender Familieneintopf mit zartem Fleisch, frischem Wurzelgemüse und goldgelbem Maisbrot.',
    ingredients: [
      { name: 'Rinder-Schmorfleisch oder Gulasch', amount: '600g', category: 'meat' },
      { name: 'Festkochende Kartoffeln', amount: '1kg', category: 'produce' },
      { name: 'Bundmöhren', amount: '500g', category: 'produce' },
      { name: 'Rinderbrühe', amount: '500ml', category: 'pantry' },
      { name: 'Maismehl & Buttermilch', amount: 'je 1 Pck. / Becher', category: 'dairy' },
      { name: 'Zwiebeln', amount: '2 Stück', category: 'produce' },
    ],
  },
  {
    id: 'r8',
    title: 'Bunte Familien-Bowl zum Selberbelegen',
    prepTime: '20 Min.',
    servings: 5,
    category: 'healthy',
    theme: 'fresh',
    isFavorite: true,
    mainProtein: 'vegetarian',
    estimatedCost: 12.0,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    notes: 'Bunt, gesund und abwechslungsreich: Jeder füllt seine Schale nach eigenem Geschmack.',
    ingredients: [
      { name: 'Bunter Quinoa oder Reis', amount: '300g', category: 'pantry' },
      { name: 'Reife Avocados', amount: '2 Stück', category: 'produce' },
      { name: 'Kichererbsen (Dose)', amount: '1 Dose (400g)', category: 'pantry' },
      { name: 'Feta-Käse', amount: '200g', category: 'dairy' },
      { name: 'Kirschtomaten & Salatgurke', amount: '1 Schale / 1 Stück', category: 'produce' },
      { name: 'Granatapfelkerne & Kürbiskerne', amount: '50g', category: 'produce' },
    ],
  },
];

export const INITIAL_MEAL_PLANS: MealPlanDay[] = [
  {
    date: getRelativeDate(0), // Heute
    breakfast: { title: 'Griechischer Joghurt mit Knuspermüsli & Honig', chefId: 'm1' },
    lunch: { title: 'Puten- & Schweizer Käse-Wraps', chefId: 'm2' },
    dinner: { title: 'Knusprige Ofenblech-Hähnchen-Tacos', recipeId: 'r2', chefId: 'm2' },
  },
  {
    date: getRelativeDate(1), // Morgen
    breakfast: { title: 'Rührei & frisches Vollkornbrot', chefId: 'm2' },
    lunch: { title: 'Bunte Taco-Bowl-Reste', chefId: 'm1' },
    dinner: { title: 'Cremige Zitronen-Kräuter-Pasta mit Kirschtomaten', recipeId: 'r1', chefId: 'm1' },
  },
  {
    date: getRelativeDate(2),
    breakfast: { title: 'Beeren-Smoothies & Haferflocken', chefId: 'm1' },
    lunch: { title: 'Knusprige Caprese-Baguettes', chefId: 'm5' },
    dinner: { title: 'Hausgemachte Steinofen-Pizza Margherita', recipeId: 'r4', chefId: 'm3' },
  },
  {
    date: getRelativeDate(3),
    breakfast: { title: 'Fluffige Samstagmorgen Beeren-Pancakes', recipeId: 'r5', chefId: 'm2' },
    lunch: { title: 'Marktfrische Picknick-Stullen', chefId: 'm1' },
    dinner: { title: 'Oma Elenas Goldener Hähnchen-Gemüse-Topf', recipeId: 'r3', chefId: 'm5' },
  },
  {
    date: getRelativeDate(4),
    breakfast: { title: 'Avocado-Toast mit pochierten Eiern', chefId: 'm1' },
    lunch: { title: 'Minestrone-Gemüseeintopf & warme Brötchen', chefId: 'm5' },
    dinner: { title: 'Honig-Lachs mit knackigem Brokkoli', recipeId: 'r6', chefId: 'm2' },
  },
  {
    date: getRelativeDate(5),
    breakfast: { title: 'Warmer Zimt-Porridge mit Äpfeln', chefId: 'm5' },
    lunch: { title: 'Knackiger Hähnchen-Caesar-Salat', chefId: 'm1' },
    dinner: { title: 'Herzhafter Schmortopf mit Maisbrot', recipeId: 'r7', chefId: 'm2' },
  },
  {
    date: getRelativeDate(6),
    breakfast: { title: 'Bunter Obstteller & ofenfrische Croissants', chefId: 'm5' },
    lunch: { title: 'Gegrilltes Käsesandwich mit Tomatencremesuppe', chefId: 'm3' },
    dinner: { title: 'Bunte Familien-Bowl zum Selberbelegen', recipeId: 'r8', chefId: 'm1' },
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'a1',
    title: 'Leos Fußballspiel gegen die Tiger ⚽',
    date: getRelativeDate(0), // Heute
    time: '16:30',
    durationMinutes: 90,
    location: 'Sportpark West (Platz 3)',
    memberIds: ['m2', 'm3'],
    category: 'sports',
    notes: 'Leos Schienbeinschoner und Trinkflasche einpacken. Alex fährt!',
  },
  {
    id: 'a2',
    title: 'Mias Zahnarzt-Kontrolle 🦷',
    date: getRelativeDate(0), // Heute
    time: '14:00',
    durationMinutes: 45,
    location: 'Kinderzahnarztpraxis Dr. Weiss',
    memberIds: ['m1', 'm4'],
    category: 'health',
    notes: 'Halbjährliche Vorsorgeuntersuchung & Versiegelung.',
  },
  {
    id: 'a3',
    title: 'Sarahs Teammeeting Klinik 🏥',
    date: getRelativeDate(1), // Morgen
    time: '08:30',
    durationMinutes: 60,
    location: 'Kinderklinik Konferenzraum B',
    memberIds: ['m1'],
    category: 'work',
    notes: 'Abteilungsleiter-Besprechung und Quartalsplanung.',
  },
  {
    id: 'a4',
    title: 'Robotik-AG Wettbewerbsvorbereitung 🤖',
    date: getRelativeDate(1),
    time: '15:30',
    durationMinutes: 75,
    location: 'Realschule Raum 104',
    memberIds: ['m3'],
    category: 'school',
    notes: 'Testlauf der autonomen Hinderniserkennung für den Pokal.',
  },
  {
    id: 'a5',
    title: 'Mias Turn-Training 🤸‍♀️',
    date: getRelativeDate(2),
    time: '16:00',
    durationMinutes: 60,
    location: 'Sporthalle Turnerbund',
    memberIds: ['m4', 'm5'],
    category: 'sports',
    notes: 'Oma Elena übernimmt das Abholen nach dem Training.',
  },
  {
    id: 'a6',
    title: 'Familien-Kinoabend: Paddington 🎬🍿',
    date: getRelativeDate(2),
    time: '19:30',
    durationMinutes: 120,
    location: 'Wohnzimmer (Popcorn steht bereit!)',
    memberIds: ['m1', 'm2', 'm3', 'm4', 'm5'],
    category: 'family',
    notes: 'Wir alle fünf zusammen! Mia sucht die Knabbersachen aus.',
  },
  {
    id: 'a7',
    title: 'Oma Elenas Gartenbauverein 🌻',
    date: getRelativeDate(3),
    time: '10:00',
    durationMinutes: 90,
    location: 'Botanischer Schaugarten',
    memberIds: ['m5'],
    category: 'social',
    notes: 'Samen alter Tomatensorten und Dahlienknollen tauschen.',
  },
  {
    id: 'a8',
    title: 'Großer Familien-Sonntagsausflug mit Picknick 🌲🧺',
    date: getRelativeDate(4),
    time: '11:00',
    durationMinutes: 180,
    location: 'Naturpark Fichtenhöhe',
    memberIds: ['m1', 'm2', 'm3', 'm4', 'm5'],
    category: 'family',
    notes: 'Rucksäcke, Kamera und feste Wanderschuhe einpacken.',
  },
];

export const INITIAL_PHOTOS: PhotoMemory[] = [
  {
    id: 'p1',
    title: 'Leo erzielt das Siegtor! ⚽',
    caption: 'Gleichstand 2:2 mit nur noch 3 Minuten auf der Uhr – Leo zirkelt den Ball genau in den Winkel! Das ganze Team stürmt aufs Feld.',
    imageUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1000&q=80',
    date: getRelativeDate(-2),
    uploadedByMemberId: 'm2',
    taggedMemberIds: ['m2', 'm3'],
    likes: ['m1', 'm4', 'm5'],
    album: 'Sport & Spiele',
  },
  {
    id: 'p2',
    title: 'Backnachmittag mit Oma 🍪',
    caption: 'Oma Elena zeigt Mia das Familienrezept für echte Butterkekse. Schaut euch das Mehl auf Mias Nase an!',
    imageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1000&q=80',
    date: getRelativeDate(-5),
    uploadedByMemberId: 'm5',
    taggedMemberIds: ['m4', 'm5'],
    likes: ['m1', 'm2', 'm3'],
    album: 'Alltagsmomente',
  },
  {
    id: 'p3',
    title: 'Kanutour im Abendrot am Bergsee 🛶',
    caption: 'Unser Sommerurlaub in den Bergen. Spiegelglattes Wasser und goldene Abendstimmung. Können den nächsten Urlaub kaum erwarten!',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',
    date: '2026-07-22',
    uploadedByMemberId: 'm1',
    taggedMemberIds: ['m1', 'm2', 'm3', 'm4'],
    likes: ['m1', 'm2', 'm3', 'm4', 'm5'],
    album: 'Urlaub & Reisen',
  },
  {
    id: 'p4',
    title: '1. Platz für Mias Aquarell-Gemälde 🎨',
    caption: 'Mia hat beim Schulausstellungswettbewerb den 1. Preis gewonnen! Wir sind so stolz auf unsere kleine Künstlerin.',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1000&q=80',
    date: getRelativeDate(-10),
    uploadedByMemberId: 'm1',
    taggedMemberIds: ['m1', 'm4'],
    likes: ['m2', 'm3', 'm5'],
    album: 'Meilensteine',
  },
  {
    id: 'p5',
    title: 'Sonntagsgrillen im Garten 🥩🔥',
    caption: 'Papa Alex grillt Flammlachs auf Zedernholz und Pfirsiche mit Honigmarinade.',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1000&q=80',
    date: getRelativeDate(-14),
    uploadedByMemberId: 'm2',
    taggedMemberIds: ['m1', 'm2'],
    likes: ['m1', 'm5'],
    album: 'Alltagsmomente',
  },
];

export const INITIAL_GALLERIES: GalleryAlbum[] = [
  {
    id: 'gal_1',
    title: 'Sommerurlaub am Bergsee & Alpen 🏔️',
    description: 'Frische Bergluft, Kanufahrten bei Sonnenuntergang, Almwanderungen und Marshmallows am Lagerfeuer.',
    date: '2026-07-22',
    coverPhotoUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    category: 'vacation',
    createdByMemberId: 'm1',
    isPublicShared: true,
    shareCode: 'bergsee-sommer-2026',
    photos: [
      {
        id: 'p_gal1_1',
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        caption: 'Kanutour bei Sonnenuntergang auf ruhigem Bergwasser',
        uploadedByMemberId: 'm1',
        uploadedAt: '2026-07-22',
        likes: ['m2', 'm3', 'm4', 'm5'],
      },
      {
        id: 'p_gal1_2',
        imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
        caption: 'Frühmorgendliche Gipfelwanderung – was für ein Panoramablick ins Tal!',
        uploadedByMemberId: 'm2',
        uploadedAt: '2026-07-23',
        likes: ['m1', 'm3'],
      },
      {
        id: 'p_gal1_3',
        imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
        caption: 'Leo hat einen geheimen Wasserfall am Kiefernsteig entdeckt 🌲',
        uploadedByMemberId: 'm3',
        uploadedAt: '2026-07-24',
        likes: ['m1', 'm2', 'm4'],
      },
      {
        id: 'p_gal1_4',
        imageUrl: 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?auto=format&fit=crop&w=1200&q=80',
        caption: 'Gemütliches Frühstück auf der Hüttenterrasse vor der Bootstour',
        uploadedByMemberId: 'm2',
        uploadedAt: '2026-07-25',
        likes: ['m1', 'm4', 'm5'],
      },
    ],
    guestReactions: [
      {
        id: 'gr_1',
        author: 'Oma Elena',
        message: 'Das Foto mit dem Kanu im Abendlicht ist ein Traum! Das müssen wir unbedingt rahmen!',
        emoji: '❤️',
        timestamp: 'Vor 2 Tagen',
      },
      {
        id: 'gr_2',
        author: 'Onkel Marc',
        message: 'Leo sieht aus wie ein echter Bergsteiger! Wäre zu gern mitgekommen!',
        emoji: '🙌',
        timestamp: 'Gestern',
      },
    ],
  },
  {
    id: 'gal_2',
    title: 'Mias 7. Geburtstag & Kunstschleife 🎂🎨',
    description: 'Glitzernde Einhorn-Muffins, 1. Platz beim Malwettbewerb und Gartenspiele mit ihren Freundinnen.',
    date: getRelativeDate(-10),
    coverPhotoUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80',
    category: 'birthday',
    createdByMemberId: 'm1',
    isPublicShared: true,
    shareCode: 'mias-7-geburtstag',
    photos: [
      {
        id: 'p_gal2_1',
        imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80',
        caption: 'Mias Siegerbild mit blauer Ehrenschleife!',
        uploadedByMemberId: 'm1',
        uploadedAt: getRelativeDate(-10),
        likes: ['m2', 'm3', 'm5'],
      },
      {
        id: 'p_gal2_2',
        imageUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=1200&q=80',
        caption: 'Die 7 Kerzen auspusten während alle „Happy Birthday“ singen 🕯️',
        uploadedByMemberId: 'm2',
        uploadedAt: getRelativeDate(-10),
        likes: ['m1', 'm3', 'm4', 'm5'],
      },
      {
        id: 'p_gal2_3',
        imageUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=80',
        caption: 'Bunte Luftballons im sonnigen Garten',
        uploadedByMemberId: 'm5',
        uploadedAt: getRelativeDate(-10),
        likes: ['m1', 'm4'],
      },
    ],
    guestReactions: [
      {
        id: 'gr_3',
        author: 'Tante Clara',
        message: 'Alles Liebe zum 7. Geburtstag, liebe Mia! Wahnsinn, wie groß du schon bist! Hab dich lieb!',
        emoji: '🎉',
        timestamp: 'Vor 3 Tagen',
      },
    ],
  },
  {
    id: 'gal_3',
    title: 'Sonntagsplätzchen backen in Omas Küche 🍪',
    description: 'Oma Elena zeigt Mia den perfekten Trick für zarte Butterplätzchen.',
    date: getRelativeDate(-5),
    coverPhotoUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1200&q=80',
    category: 'everyday',
    createdByMemberId: 'm5',
    isPublicShared: true,
    shareCode: 'oma-kekse-backen',
    photos: [
      {
        id: 'p_gal3_1',
        imageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1200&q=80',
        caption: 'Gemeinsames Teigausrollen – schaut auf die Mehlstupser auf der Nase!',
        uploadedByMemberId: 'm5',
        uploadedAt: getRelativeDate(-5),
        likes: ['m1', 'm2', 'm3', 'm4'],
      },
      {
        id: 'p_gal3_2',
        imageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=1200&q=80',
        caption: 'Frisch aus dem Ofen auf dem Abkühlgitter. Das ganze Haus duftet herrlich!',
        uploadedByMemberId: 'm1',
        uploadedAt: getRelativeDate(-5),
        likes: ['m2', 'm3', 'm5'],
      },
    ],
    guestReactions: [
      {
        id: 'gr_4',
        author: 'Oma Elena',
        message: 'Mia war die beste kleine Chefköchin! Nächsten Monat backen wir Zimtsterne.',
        emoji: '🍪',
        timestamp: 'Vor 4 Tagen',
      },
    ],
  },
  {
    id: 'gal_4',
    title: 'Leos Meisterschafts-Finale ⚽🏆',
    description: '2:2 Unentschieden bis zur 87. Minute – dann traf Leo genau in den Winkel zum Pokalsieg!',
    date: getRelativeDate(-2),
    coverPhotoUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1200&q=80',
    category: 'sports',
    createdByMemberId: 'm2',
    isPublicShared: true,
    shareCode: 'leos-fussball-meisterschaft',
    photos: [
      {
        id: 'p_gal4_1',
        imageUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1200&q=80',
        caption: 'Der entscheidende Treffer in der 87. Minute!',
        uploadedByMemberId: 'm2',
        uploadedAt: getRelativeDate(-2),
        likes: ['m1', 'm3', 'm4', 'm5'],
      },
      {
        id: 'p_gal4_2',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=1200&q=80',
        caption: 'Große Jubeltraube mit dem Siegerpokal! 🏆',
        uploadedByMemberId: 'm3',
        uploadedAt: getRelativeDate(-2),
        likes: ['m1', 'm2'],
      },
    ],
    guestReactions: [
      {
        id: 'gr_5',
        author: 'Trainer Müller',
        message: 'Tor des Monats! Verdienter Pokalsieg für die ganze Mannschaft!',
        emoji: '⚽',
        timestamp: 'Vor 1 Tag',
      },
    ],
  },
];

export const INITIAL_STORES: StoreDefinition[] = [
  { id: 'rewe', name: 'Rewe', icon: '🛒', badgeColor: 'bg-red-100 text-red-700', borderColor: 'border-red-300' },
  { id: 'dm', name: 'dm', icon: '🧴', badgeColor: 'bg-blue-100 text-blue-700', borderColor: 'border-blue-300' },
  { id: 'bakery', name: 'Bäcker', icon: '🥖', badgeColor: 'bg-amber-100 text-amber-800', borderColor: 'border-amber-300' },
  { id: 'pharmacy', name: 'Apotheke', icon: '💊', badgeColor: 'bg-emerald-100 text-emerald-800', borderColor: 'border-emerald-300' },
];

export const INITIAL_STORE_LEARNING_MAP: Record<string, string> = {
  // dm Drogerie (Reinigung, Hygiene, Kosmetik, Haushalt)
  'dishwasher pods': 'dm',
  'spülmaschinentabs': 'dm',
  'spülmaschinentabletten': 'dm',
  'paper towels': 'dm',
  'küchenrolle': 'dm',
  'küchenrollen': 'dm',
  'laundry detergent': 'dm',
  'waschmittel': 'dm',
  'shampoo': 'dm',
  'haarschampoo': 'dm',
  'conditioner': 'dm',
  'haarspülung': 'dm',
  'spülung': 'dm',
  'toothpaste': 'dm',
  'zahnpasta': 'dm',
  'zahncreme': 'dm',
  'toothbrush': 'dm',
  'zahnbürste': 'dm',
  'toilet paper': 'dm',
  'toilettenpapier': 'dm',
  'klopapier': 'dm',
  'hand soap': 'dm',
  'handseife': 'dm',
  'seife': 'dm',
  'trash bags': 'dm',
  'müllbeutel': 'dm',
  'mülltüten': 'dm',
  'cleaning spray': 'dm',
  'putzmittel': 'dm',
  'allzweckreiniger': 'dm',
  'sponges': 'dm',
  'schwämme': 'dm',
  'putzschwämme': 'dm',
  'body wash': 'dm',
  'duschgel': 'dm',
  'cotton pads': 'dm',
  'wattepads': 'dm',
  'sunscreen': 'dm',
  'sonnencreme': 'dm',
  'sonnenmilch': 'dm',
  'wet wipes': 'dm',
  'feuchttücher': 'dm',
  'windeln': 'dm',

  // Bäcker (Frisches Brot, Brötchen, Gebäck)
  'sourdough loaf': 'Bäcker',
  'sourdough bread': 'Bäcker',
  'sauerteigbrot': 'Bäcker',
  'brot': 'Bäcker',
  'vollkornbrot': 'Bäcker',
  'croissants': 'Bäcker',
  'fresh croissants': 'Bäcker',
  'croissant': 'Bäcker',
  'bread rolls': 'Bäcker',
  'brötchen': 'Bäcker',
  'semmeln': 'Bäcker',
  'baguette': 'Bäcker',
  'pretzels': 'Bäcker',
  'brezeln': 'Bäcker',
  'laugengebäck': 'Bäcker',
  'kuchen': 'Bäcker',

  // Apotheke (Gesundheit, Vitamine, Erste Hilfe)
  'bandages': 'Apotheke',
  'pflaster': 'Apotheke',
  'vitamins': 'Apotheke',
  'vitamintabletten': 'Apotheke',
  'pain relievers': 'Apotheke',
  'schmerzmittel': 'Apotheke',
  'ibuprofen': 'Apotheke',
  'paracetamol': 'Apotheke',
  'cough drops': 'Apotheke',
  'hustenbonbons': 'Apotheke',
  'hustensaft': 'Apotheke',
  'thermometer': 'Apotheke',
  'fieberthermometer': 'Apotheke',
  'nasenspray': 'Apotheke',
  'desinfektionsmittel': 'Apotheke',

  // Rewe ist Standard für Lebensmittel, Frische, Fleisch & Milchprodukte
};

export const INITIAL_ALWAYS_IN_STOCK: string[] = [
  'salt',
  'salz',
  'sea salt',
  'meersalz',
  'speisesalz',
  'table salt',
  'pepper',
  'pfeffer',
  'black pepper',
  'schwarzer pfeffer',
  'water',
  'wasser',
  'tap water',
  'leitungswasser',
  'olive oil',
  'olivenöl',
  'extra virgin olive oil',
  'natives olivenöl extra',
  'cooking oil',
  'speiseöl',
  'pflanzenöl',
  'öl',
  'vegetable oil',
  'sonnenblumenöl',
  'sugar',
  'zucker',
  'white sugar',
  'haushaltszucker',
  'flour',
  'mehl',
  'all-purpose flour',
  'weizenmehl',
  'baking powder',
  'backpulver',
  'butter',
  'milch',
  'frischmilch',
];

export const INITIAL_GROCERIES: GroceryItem[] = [
  { id: 'g1', name: 'Frisches Basilikum', amount: '1 Bund', store: 'Rewe', category: 'produce', checked: false, addedByMemberId: 'm1' },
  { id: 'g2', name: 'Reife Avocados', amount: '4 Stück', store: 'Rewe', category: 'produce', checked: false, addedByMemberId: 'm2' },
  { id: 'g3', name: 'Kirschtomaten', amount: '2 Schalen', store: 'Rewe', category: 'produce', checked: true, addedByMemberId: 'm1' },
  { id: 'g4', name: 'Bio-Vollmilch', amount: '2 Liter', store: 'Rewe', category: 'dairy', checked: false, addedByMemberId: 'm2' },
  { id: 'g5', name: 'Frischer Mozzarella', amount: '3 Kugeln', store: 'Rewe', category: 'dairy', checked: false, addedByMemberId: 'm1' },
  { id: 'g6', name: 'Freilandeier', amount: '10er-Pack', store: 'Rewe', category: 'dairy', checked: true, addedByMemberId: 'm5' },
  { id: 'g7', name: 'Hähnchenbrustfilet', amount: '800g', store: 'Rewe', category: 'meat', checked: false, addedByMemberId: 'm2' },
  { id: 'g8', name: 'Zitronen-Mineralwasser', amount: '1 Kiste', store: 'Rewe', category: 'pantry', checked: false, addedByMemberId: 'm3' },
  { id: 'g9', name: 'Spülmaschinen-Tabs', amount: '1 Vorratspack', store: 'dm', category: 'household', checked: false, addedByMemberId: 'm1' },
  { id: 'g10', name: 'Küchenrolle', amount: '4er-Pack', store: 'dm', category: 'household', checked: false, addedByMemberId: 'm2' },
  { id: 'g11', name: 'Frisches Sauerteigbrot', amount: '1 Laib', store: 'Bäcker', category: 'bakery', checked: false, addedByMemberId: 'm5' },
];

export const INITIAL_CHORES: Chore[] = [
  { id: 'c1', title: 'Familienhund Barnaby füttern & bürsten 🐕', assignedMemberId: 'm3', frequency: 'daily', completed: true, stars: 2 },
  { id: 'c2', title: 'Geschirrspüler ausräumen & Tassen einräumen', assignedMemberId: 'm4', frequency: 'daily', completed: false, stars: 3 },
  { id: 'c3', title: 'Altpapier & Bio-Tonne zur Straße bringen', assignedMemberId: 'm3', frequency: 'weekly', completed: false, stars: 4 },
  { id: 'c4', title: 'Malsachen & Spielecke im Wohnzimmer aufräumen', assignedMemberId: 'm4', frequency: 'daily', completed: true, stars: 2 },
  { id: 'c5', title: 'Tomatenpflanzen & Kräuterbeete im Garten gießen', assignedMemberId: 'm5', frequency: 'daily', completed: true, stars: 3 },
];

export const INITIAL_NOTES: PinnedNote[] = [
  {
    id: 'n1',
    title: '🏡 WLAN-Heimnetzwerk',
    content: 'SSID: „SunflowerCottage-5G“ | Passwort: „SunnyPancakes2026!“ – Gäste-WLAN benötigt kein Passwort.',
    isPinned: true,
    tag: 'wifi',
    authorMemberId: 'm2',
    createdAt: '2026-09-01',
  },
  {
    id: 'n2',
    title: '🚌 Schulbus & Abholzeiten',
    content: 'Linie 14 bringt Leo & Mia um 15:15 Uhr an die Haltestelle Lindenallee. Donnerstags holt Alex Leo früher zur Robotik-AG ab.',
    isPinned: true,
    tag: 'urgent',
    authorMemberId: 'm1',
    createdAt: '2026-09-10',
  },
  {
    id: 'n3',
    title: '🌟 Familien-Lob: Mias Siegerbild!',
    content: 'Riesiges Lob an Mia für den 1. Platz beim Schulausstellungswettbewerb! Zur Feier gibt es am Samstag Eis für alle!',
    isPinned: false,
    tag: 'fun',
    authorMemberId: 'm1',
    createdAt: '2026-09-17',
  },
];
