import { FamilyMember, Appointment, Recipe, MealPlanDay, PhotoMemory, GalleryAlbum, GroceryItem, Chore, PinnedNote, StoreDefinition } from '../types';

// Helper to get formatted dates relative to today
const getRelativeDate = (offsetDays: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const INITIAL_MEMBERS: FamilyMember[] = [
  {
    id: 'm1',
    name: 'Sarah',
    role: 'Mom',
    avatar: '👩‍💼',
    color: '#EC4899',
    bgLight: 'bg-pink-50',
    borderClass: 'border-pink-300',
    textClass: 'text-pink-700',
    birthday: '1986-05-14',
    notes: 'Pediatrician, loves weekend runs & iced lattes',
    pin: '1234',
    isChild: false,
    customFields: [
      { id: 'cf_s1', label: 'Work Hospital', value: 'Metro Children’s (Dept 3)', category: 'other' },
      { id: 'cf_s2', label: 'Blood Type', value: 'O+', category: 'health' },
    ],
  },
  {
    id: 'm2',
    name: 'Alex',
    role: 'Dad',
    avatar: '👨‍💻',
    color: '#0D9488',
    bgLight: 'bg-teal-50',
    borderClass: 'border-teal-300',
    textClass: 'text-teal-700',
    birthday: '1984-11-20',
    notes: 'Landscape architect, weekend BBQ chef',
    pin: '1234',
    isChild: false,
    customFields: [
      { id: 'cf_a1', label: 'Health Insurance', value: 'Techniker Krankenkasse (TK) #8194', category: 'health' },
      { id: 'cf_a2', label: 'Blood Type', value: 'A+', category: 'health' },
    ],
  },
  {
    id: 'm3',
    name: 'Leo',
    role: 'Son (12)',
    avatar: '⚽',
    color: '#F59E0B',
    bgLight: 'bg-amber-50',
    borderClass: 'border-amber-300',
    textClass: 'text-amber-700',
    birthday: '2014-03-08',
    notes: 'Midfielder on school soccer team, coding club',
    isChild: true,
    childDetails: {
      clothingSize: 'Youth L (12-14)',
      shoeSize: 'US 6.5 / EU 39',
      pantsSize: '12 Regular (Inseam 26")',
      doctorName: 'Dr. Emily Hayes, MD (Pediatrics)',
      doctorPhone: '(555) 342-9100',
      doctorAddress: 'Oak Valley Pediatric Care, 420 Blossom Ave, Suite 2B',
      dentistName: 'Dr. Peter Vance, DDS',
      dentistPhone: '(555) 883-2040',
      dentistAddress: 'Valley Smiles Orthodontics, 108 River St',
      allergies: 'Mild seasonal pollen / hayfever',
      bloodType: 'A+',
      schoolName: 'Lincoln Middle School',
      grade: '7th Grade (Homeroom 204)',
      emergencyContact: 'Sarah Miller (Mom): (555) 712-4401',
      customFields: [
        { id: 'cfl_1', label: 'Bicycle Helmet', value: '54-58 cm', category: 'sizes' },
        { id: 'cfl_2', label: 'Soccer Club Member ID', value: 'FC West #9041', category: 'school' },
        { id: 'cfl_3', label: 'Shin Guard Size', value: 'Youth Medium', category: 'sizes' },
      ],
    },
  },
  {
    id: 'm4',
    name: 'Mia',
    role: 'Daughter (8)',
    avatar: '🎨',
    color: '#8B5CF6',
    bgLight: 'bg-purple-50',
    borderClass: 'border-purple-300',
    textClass: 'text-purple-700',
    birthday: '2018-09-02',
    notes: 'Gymnastics, drawing comics, loves pancakes',
    isChild: true,
    childDetails: {
      clothingSize: 'Youth M (8-10)',
      shoeSize: 'US 2.5 / EU 34',
      pantsSize: '8 Slim',
      doctorName: 'Dr. Emily Hayes, MD (Pediatrics)',
      doctorPhone: '(555) 342-9100',
      doctorAddress: 'Oak Valley Pediatric Care, 420 Blossom Ave, Suite 2B',
      dentistName: 'Dr. Peter Vance, DDS',
      dentistPhone: '(555) 883-2040',
      dentistAddress: 'Valley Smiles Orthodontics, 108 River St',
      allergies: 'No known allergies',
      bloodType: 'O+',
      schoolName: 'Sunnyvale Elementary School',
      grade: '3rd Grade (Mrs. Higgins)',
      emergencyContact: 'Alex Miller (Dad): (555) 948-2309',
      customFields: [
        { id: 'cfm_1', label: 'Gymnastics Leotard', value: 'Size 8 / 128 cm', category: 'sizes' },
        { id: 'cfm_2', label: 'Swim Badge Level', value: 'Bronze (Seepferdchen)', category: 'school' },
        { id: 'cfm_3', label: 'Favorite Color', value: 'Sky Blue & Lilac', category: 'other' },
      ],
    },
  },
  {
    id: 'm5',
    name: 'Grandma Elena',
    role: 'Grandma',
    avatar: '👵',
    color: '#3B82F6',
    bgLight: 'bg-blue-50',
    borderClass: 'border-blue-300',
    textClass: 'text-blue-700',
    birthday: '1955-08-19',
    notes: 'Master baker, garden guru, family storyteller',
    isChild: false,
    customFields: [
      { id: 'cfg_1', label: 'Primary Physician', value: 'Dr. Robert Martinez, MD (555) 602-1818', category: 'health' },
      { id: 'cfg_2', label: 'Medical Alert', value: 'Penicillin Allergy', category: 'health' },
      { id: 'cfg_3', label: 'Dentist', value: 'Dr. Peter Vance, DDS', category: 'health' },
    ],
  },
];

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: 'r1',
    title: 'Creamy Lemon Herb Pasta with Cherry Tomatoes',
    prepTime: '20 mins',
    servings: 5,
    category: 'quick',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281057?auto=format&fit=crop&w=600&q=80',
    notes: 'Super quick weekday dinner. Leo loves extra parmesan on top!',
    ingredients: [
      { name: 'Fettuccine or Tagliatelle', amount: '500g', category: 'pantry' },
      { name: 'Cherry Tomatoes', amount: '250g', category: 'produce' },
      { name: 'Fresh Basil', amount: '1 bunch', category: 'produce' },
      { name: 'Heavy Cream or Mascarpone', amount: '200ml', category: 'dairy' },
      { name: 'Parmesan Cheese', amount: '100g', category: 'dairy' },
      { name: 'Lemons', amount: '2', category: 'produce' },
      { name: 'Garlic Cloves', amount: '3 cloves', category: 'produce' },
    ],
  },
  {
    id: 'r2',
    title: 'Crispy Sheet-Pan Chicken Tacos',
    prepTime: '30 mins',
    servings: 5,
    category: 'family-favorite',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    notes: 'Taco Tuesday tradition! Set out toppings so everyone builds their own.',
    ingredients: [
      { name: 'Chicken Breast', amount: '700g', category: 'meat' },
      { name: 'Corn Tortillas', amount: '1 pack (12 pcs)', category: 'bakery' },
      { name: 'Avocados (Guacamole)', amount: '3 ripe', category: 'produce' },
      { name: 'Lime', amount: '2', category: 'produce' },
      { name: 'Cheddar Cheese', amount: '150g', category: 'dairy' },
      { name: 'Sour Cream', amount: '1 tub', category: 'dairy' },
      { name: 'Taco Seasoning', amount: '1 packet', category: 'pantry' },
    ],
  },
  {
    id: 'r3',
    title: 'Grandma Elena’s Golden Chicken & Vegetable Pot Pie',
    prepTime: '50 mins',
    servings: 6,
    category: 'comfort',
    imageUrl: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=600&q=80',
    notes: 'Perfect Sunday family dinner. Made with buttery puff pastry.',
    ingredients: [
      { name: 'Puff Pastry Sheets', amount: '2 rolls', category: 'bakery' },
      { name: 'Chicken Thighs', amount: '600g', category: 'meat' },
      { name: 'Carrots & Peas', amount: '300g', category: 'produce' },
      { name: 'Potatoes', amount: '4 medium', category: 'produce' },
      { name: 'Chicken Broth', amount: '500ml', category: 'pantry' },
      { name: 'Butter', amount: '50g', category: 'dairy' },
    ],
  },
  {
    id: 'r4',
    title: 'Homemade Stone-Baked Margherita Pizza',
    prepTime: '25 mins',
    servings: 5,
    category: 'family-favorite',
    imageUrl: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=600&q=80',
    notes: 'Friday night family pizza making! Mia makes smiley faces with basil.',
    ingredients: [
      { name: 'Pizza Dough', amount: '2 balls', category: 'bakery' },
      { name: 'San Marzano Tomato Sauce', amount: '1 jar', category: 'pantry' },
      { name: 'Fresh Mozzarella', amount: '3 balls', category: 'dairy' },
      { name: 'Fresh Basil leaves', amount: '1 bunch', category: 'produce' },
      { name: 'Extra Virgin Olive Oil', amount: '1 bottle', category: 'pantry' },
    ],
  },
  {
    id: 'r5',
    title: 'Fluffy Saturday Morning Berry Pancakes',
    prepTime: '20 mins',
    servings: 5,
    category: 'baking',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=600&q=80',
    notes: 'Weekend breakfast treat with real maple syrup and fresh berries.',
    ingredients: [
      { name: 'Pancake Flour / Mix', amount: '400g', category: 'pantry' },
      { name: 'Organic Whole Milk', amount: '1 Liter', category: 'dairy' },
      { name: 'Fresh Blueberries & Strawberries', amount: '2 punnets', category: 'produce' },
      { name: 'Pure Maple Syrup', amount: '1 bottle', category: 'pantry' },
      { name: 'Eggs', amount: '6 pack', category: 'dairy' },
    ],
  },
];

export const INITIAL_MEAL_PLANS: MealPlanDay[] = [
  {
    date: getRelativeDate(0), // Today
    breakfast: { title: 'Greek Yogurt with Granola & Honey', chefId: 'm1' },
    lunch: { title: 'Turkey & Swiss Wraps', chefId: 'm2' },
    dinner: { title: 'Crispy Sheet-Pan Chicken Tacos', recipeId: 'r2', chefId: 'm2' },
  },
  {
    date: getRelativeDate(1), // Tomorrow
    breakfast: { title: 'Scrambled Eggs & Toast', chefId: 'm2' },
    lunch: { title: 'Leftover Taco Bowls', chefId: 'm1' },
    dinner: { title: 'Creamy Lemon Herb Pasta with Cherry Tomatoes', recipeId: 'r1', chefId: 'm1' },
  },
  {
    date: getRelativeDate(2),
    breakfast: { title: 'Berry Smoothies & Oatmeal', chefId: 'm1' },
    lunch: { title: 'Caprese Baguette Sandwiches', chefId: 'm5' },
    dinner: { title: 'Homemade Stone-Baked Margherita Pizza', recipeId: 'r4', chefId: 'm3' },
  },
  {
    date: getRelativeDate(3),
    breakfast: { title: 'Fluffy Saturday Morning Berry Pancakes', recipeId: 'r5', chefId: 'm2' },
    lunch: { title: 'Farmer Market Picnic Sandwiches', chefId: 'm1' },
    dinner: { title: 'Grandma Elena’s Golden Chicken & Vegetable Pot Pie', recipeId: 'r3', chefId: 'm5' },
  },
  {
    date: getRelativeDate(4),
    breakfast: { title: 'Avocado Toast with Poached Eggs', chefId: 'm1' },
    lunch: { title: 'Minestrone Soup & Warm Rolls', chefId: 'm5' },
    dinner: { title: 'Honey Glazed Salmon with Steamed Broccoli', chefId: 'm2' },
  },
  {
    date: getRelativeDate(5),
    breakfast: { title: 'Warm Cinnamon Oatmeal', chefId: 'm5' },
    lunch: { title: 'Chicken Caesar Salad', chefId: 'm1' },
    dinner: { title: 'Slow Cooker Beef Chili with Cornbread', chefId: 'm2' },
  },
  {
    date: getRelativeDate(6),
    breakfast: { title: 'Fruit Salad & Croissants', chefId: 'm5' },
    lunch: { title: 'Grilled Cheese & Tomato Bisque', chefId: 'm3' },
    dinner: { title: 'Build-Your-Own Grain Bowls', chefId: 'm1' },
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'a1',
    title: 'Leo Soccer Match vs Tigers',
    date: getRelativeDate(0), // Today
    time: '16:30',
    durationMinutes: 90,
    location: 'Westside Community Fields (Pitch 3)',
    memberIds: ['m2', 'm3'],
    category: 'sports',
    notes: 'Bring Leo’s shin guards and extra water bottles. Alex driving.',
  },
  {
    id: 'a2',
    title: 'Mia Dental Checkup',
    date: getRelativeDate(0), // Today
    time: '14:00',
    durationMinutes: 45,
    location: 'Oak Valley Pediatric Dental Care',
    memberIds: ['m1', 'm4'],
    category: 'health',
    notes: 'Routine 6-month cleaning & sealants inspection.',
  },
  {
    id: 'a3',
    title: 'Sarah Hospital Staff Meeting',
    date: getRelativeDate(1), // Tomorrow
    time: '08:30',
    durationMinutes: 60,
    location: 'Metro Children’s Hospital Conf Room B',
    memberIds: ['m1'],
    category: 'work',
    notes: 'Department head briefing.',
  },
  {
    id: 'a4',
    title: 'Robotics Team Competition Prep',
    date: getRelativeDate(1),
    time: '15:30',
    durationMinutes: 75,
    location: 'Middle School Lab 104',
    memberIds: ['m3'],
    category: 'school',
    notes: 'Team will test autonomous obstacle routing.',
  },
  {
    id: 'a5',
    title: 'Mia Gymnastics Practice',
    date: getRelativeDate(2),
    time: '16:00',
    durationMinutes: 60,
    location: 'Olympic Spark Gymnastics Academy',
    memberIds: ['m4', 'm5'],
    category: 'sports',
    notes: 'Grandma Elena doing pickup.',
  },
  {
    id: 'a6',
    title: 'Family Movie Night: Paddington in Peru',
    date: getRelativeDate(2),
    time: '19:30',
    durationMinutes: 120,
    location: 'Living Room (Popcorn Ready!)',
    memberIds: ['m1', 'm2', 'm3', 'm4', 'm5'],
    category: 'family',
    notes: 'All 5 of us! Mia picking the movie candy.',
  },
  {
    id: 'a7',
    title: 'Grandma Elena Gardening Club',
    date: getRelativeDate(3),
    time: '10:00',
    durationMinutes: 90,
    location: 'Botanical Heritage Gardens',
    memberIds: ['m5'],
    category: 'social',
    notes: 'Sharing heirloom tomato seeds and Dahlia bulbs.',
  },
  {
    id: 'a8',
    title: 'Whole Family Sunday Hike & Picnic',
    date: getRelativeDate(4),
    time: '11:00',
    durationMinutes: 180,
    location: 'Pine Ridge Nature Reserve',
    memberIds: ['m1', 'm2', 'm3', 'm4', 'm5'],
    category: 'family',
    notes: 'Pack backpacks, camera, and hiking boots.',
  },
];

export const INITIAL_PHOTOS: PhotoMemory[] = [
  {
    id: 'p1',
    title: 'Leo scoring the winning goal! ⚽',
    caption: 'Tied 2-2 with 3 minutes left, Leo found the top corner! The whole team dog-piled him.',
    imageUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1000&q=80',
    date: getRelativeDate(-2),
    uploadedByMemberId: 'm2',
    taggedMemberIds: ['m2', 'm3'],
    likes: ['m1', 'm4', 'm5'],
    album: 'Sports & Games',
  },
  {
    id: 'p2',
    title: 'Baking afternoon with Grandma 🍪',
    caption: 'Grandma Elena teaching Mia the secret fold for butter cookies. Look at all that flour on Mia’s nose!',
    imageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1000&q=80',
    date: getRelativeDate(-5),
    uploadedByMemberId: 'm5',
    taggedMemberIds: ['m4', 'm5'],
    likes: ['m1', 'm2', 'm3'],
    album: 'Everyday Moments',
  },
  {
    id: 'p3',
    title: 'Lake Tahoe Sunset Canoe 🛶',
    caption: 'Last summer’s lake trip. Calm water and beautiful orange skies. Can’t wait for next vacation.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',
    date: '2026-07-22',
    uploadedByMemberId: 'm1',
    taggedMemberIds: ['m1', 'm2', 'm3', 'm4'],
    likes: ['m1', 'm2', 'm3', 'm4', 'm5'],
    album: 'Vacations',
  },
  {
    id: 'p4',
    title: 'Mia’s First Place Art Ribbon 🎨',
    caption: 'Mia won 1st prize in the grade school nature watercolor contest! Super proud parents.',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1000&q=80',
    date: getRelativeDate(-10),
    uploadedByMemberId: 'm1',
    taggedMemberIds: ['m1', 'm4'],
    likes: ['m2', 'm3', 'm5'],
    album: 'Milestones',
  },
  {
    id: 'p5',
    title: 'Backyard Sunday BBQ grilling session',
    caption: 'Alex experimenting with smoked cedar-plank salmon and grilled peaches.',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1000&q=80',
    date: getRelativeDate(-14),
    uploadedByMemberId: 'm2',
    taggedMemberIds: ['m1', 'm2'],
    likes: ['m1', 'm5'],
    album: 'Everyday Moments',
  },
];

export const INITIAL_GALLERIES: GalleryAlbum[] = [
  {
    id: 'gal_1',
    title: 'Summer Trip to Lake Tahoe & Alps 🏔️',
    description: 'Crisp mountain air, canoe sessions at sunset, alpine trails, and campfire s’mores.',
    date: '2026-07-22',
    coverPhotoUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    category: 'vacation',
    createdByMemberId: 'm1',
    isPublicShared: true,
    shareCode: 'tahoe-summer-2026',
    photos: [
      {
        id: 'p_gal1_1',
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        caption: 'Sunset canoe on calm lake water',
        uploadedByMemberId: 'm1',
        uploadedAt: '2026-07-22',
        likes: ['m2', 'm3', 'm4', 'm5'],
      },
      {
        id: 'p_gal1_2',
        imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
        caption: 'Morning hike to the ridge summit - look at that valley!',
        uploadedByMemberId: 'm2',
        uploadedAt: '2026-07-23',
        likes: ['m1', 'm3'],
      },
      {
        id: 'p_gal1_3',
        imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
        caption: 'Leo found a hidden waterfall along the pine trail 🌲',
        uploadedByMemberId: 'm3',
        uploadedAt: '2026-07-24',
        likes: ['m1', 'm2', 'm4'],
      },
      {
        id: 'p_gal1_4',
        imageUrl: 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?auto=format&fit=crop&w=1200&q=80',
        caption: 'Cabin deck breakfast before setting off on the boats',
        uploadedByMemberId: 'm2',
        uploadedAt: '2026-07-25',
        likes: ['m1', 'm4', 'm5'],
      },
    ],
    guestReactions: [
      {
        id: 'gr_1',
        author: 'Grandma Elena',
        message: 'The sunset canoe photo is magnificent! Put that in a frame in the living room!',
        emoji: '❤️',
        timestamp: '2 days ago',
      },
      {
        id: 'gr_2',
        author: 'Uncle Marc',
        message: 'Leo looks like a true mountain explorer! Wish I could have joined!',
        emoji: '🙌',
        timestamp: 'Yesterday',
      },
    ],
  },
  {
    id: 'gal_2',
    title: 'Mia’s 7th Birthday Party & Art ribbons 🎂🎨',
    description: 'Sparkling unicorn cupcakes, watercolor nature contest win, and garden games with friends.',
    date: getRelativeDate(-10),
    coverPhotoUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80',
    category: 'birthday',
    createdByMemberId: 'm1',
    isPublicShared: true,
    shareCode: 'mias-7th-birthday',
    photos: [
      {
        id: 'p_gal2_1',
        imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80',
        caption: 'Mia’s 1st place blue ribbon watercolor painting!',
        uploadedByMemberId: 'm1',
        uploadedAt: getRelativeDate(-10),
        likes: ['m2', 'm3', 'm5'],
      },
      {
        id: 'p_gal2_2',
        imageUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=1200&q=80',
        caption: 'Blowing out the 7 candles with everyone singing 🕯️',
        uploadedByMemberId: 'm2',
        uploadedAt: getRelativeDate(-10),
        likes: ['m1', 'm3', 'm4', 'm5'],
      },
      {
        id: 'p_gal2_3',
        imageUrl: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=80',
        caption: 'Colorful party balloons in the backyard garden',
        uploadedByMemberId: 'm5',
        uploadedAt: getRelativeDate(-10),
        likes: ['m1', 'm4'],
      },
    ],
    guestReactions: [
      {
        id: 'gr_3',
        author: 'Aunt Clara',
        message: 'Happy 7th Birthday Mia! Can’t believe how fast you’re growing! Love you!',
        emoji: '🎉',
        timestamp: '3 days ago',
      },
    ],
  },
  {
    id: 'gal_3',
    title: 'Sunday Cookie Baking in Grandma’s Kitchen 🍪',
    description: 'Grandma Elena teaching Mia the secret fold for crispy Allgäu butter cookies.',
    date: getRelativeDate(-5),
    coverPhotoUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1200&q=80',
    category: 'everyday',
    createdByMemberId: 'm5',
    isPublicShared: true,
    shareCode: 'grandma-cookies-baking',
    photos: [
      {
        id: 'p_gal3_1',
        imageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1200&q=80',
        caption: 'Rolling the dough together — look at the flour on Mia’s nose!',
        uploadedByMemberId: 'm5',
        uploadedAt: getRelativeDate(-5),
        likes: ['m1', 'm2', 'm3', 'm4'],
      },
      {
        id: 'p_gal3_2',
        imageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=1200&q=80',
        caption: 'Fresh batch cooling on the rack. The house smells incredible!',
        uploadedByMemberId: 'm1',
        uploadedAt: getRelativeDate(-5),
        likes: ['m2', 'm3', 'm5'],
      },
    ],
    guestReactions: [
      {
        id: 'gr_4',
        author: 'Grandma Elena',
        message: 'Mia was the finest little sous-chef! We need to make cinnamon stars next month.',
        emoji: '🍪',
        timestamp: '4 days ago',
      },
    ],
  },
  {
    id: 'gal_4',
    title: 'Leo’s Championship Soccer Finals ⚽',
    description: 'Tied 2-2 with 3 minutes left, Leo found the top corner to take the trophy!',
    date: getRelativeDate(-2),
    coverPhotoUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1200&q=80',
    category: 'sports',
    createdByMemberId: 'm2',
    isPublicShared: true,
    shareCode: 'leos-soccer-championship',
    photos: [
      {
        id: 'p_gal4_1',
        imageUrl: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1200&q=80',
        caption: 'The winning strike in the 87th minute!',
        uploadedByMemberId: 'm2',
        uploadedAt: getRelativeDate(-2),
        likes: ['m1', 'm3', 'm4', 'm5'],
      },
      {
        id: 'p_gal4_2',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=1200&q=80',
        caption: 'Whole team dog-piling with the cup! 🏆',
        uploadedByMemberId: 'm3',
        uploadedAt: getRelativeDate(-2),
        likes: ['m1', 'm2'],
      },
    ],
    guestReactions: [
      {
        id: 'gr_5',
        author: 'Coach Miller',
        message: 'Top corner strike of the season! Well earned Leo!',
        emoji: '⚽',
        timestamp: '1 day ago',
      },
    ],
  },
];

export const INITIAL_STORES: StoreDefinition[] = [
  { id: 'rewe', name: 'Rewe', icon: '🛒', badgeColor: 'bg-red-100 text-red-700', borderColor: 'border-red-300' },
  { id: 'dm', name: 'dm', icon: '🧴', badgeColor: 'bg-blue-100 text-blue-700', borderColor: 'border-blue-300' },
  { id: 'bakery', name: 'Bakery', icon: '🥖', badgeColor: 'bg-amber-100 text-amber-800', borderColor: 'border-amber-300' },
  { id: 'pharmacy', name: 'Pharmacy', icon: '💊', badgeColor: 'bg-emerald-100 text-emerald-800', borderColor: 'border-emerald-300' },
];

export const INITIAL_STORE_LEARNING_MAP: Record<string, string> = {
  // dm drogerie (Cleaning, toiletries, paper, personal care)
  'dishwasher pods': 'dm',
  'paper towels': 'dm',
  'laundry detergent': 'dm',
  'shampoo': 'dm',
  'conditioner': 'dm',
  'toothpaste': 'dm',
  'toothbrush': 'dm',
  'toilet paper': 'dm',
  'hand soap': 'dm',
  'trash bags': 'dm',
  'cleaning spray': 'dm',
  'sponges': 'dm',
  'body wash': 'dm',
  'cotton pads': 'dm',
  'sunscreen': 'dm',
  'wet wipes': 'dm',

  // Bakery (Fresh bread, rolls, pastries)
  'sourdough loaf': 'Bakery',
  'sourdough bread': 'Bakery',
  'croissants': 'Bakery',
  'fresh croissants': 'Bakery',
  'bread rolls': 'Bakery',
  'baguette': 'Bakery',
  'pretzels': 'Bakery',

  // Pharmacy (Health, vitamins, first aid)
  'bandages': 'Pharmacy',
  'vitamins': 'Pharmacy',
  'pain relievers': 'Pharmacy',
  'cough drops': 'Pharmacy',
  'thermometer': 'Pharmacy',

  // Rewe is default for food, fresh produce, meat, dairy
};

export const INITIAL_ALWAYS_IN_STOCK: string[] = [
  'salt',
  'sea salt',
  'table salt',
  'pepper',
  'black pepper',
  'water',
  'tap water',
  'olive oil',
  'extra virgin olive oil',
  'cooking oil',
  'vegetable oil',
  'sugar',
  'white sugar',
  'flour',
  'all-purpose flour',
  'baking powder',
];

export const INITIAL_GROCERIES: GroceryItem[] = [
  { id: 'g1', name: 'Fresh Basil', amount: '1 bunch', store: 'Rewe', category: 'produce', checked: false, addedByMemberId: 'm1' },
  { id: 'g2', name: 'Avocados', amount: '4 ripe', store: 'Rewe', category: 'produce', checked: false, addedByMemberId: 'm2' },
  { id: 'g3', name: 'Cherry Tomatoes', amount: '2 boxes', store: 'Rewe', category: 'produce', checked: true, addedByMemberId: 'm1' },
  { id: 'g4', name: 'Organic Milk', amount: '2 Gallons', store: 'Rewe', category: 'dairy', checked: false, addedByMemberId: 'm2' },
  { id: 'g5', name: 'Fresh Mozzarella', amount: '3 balls', store: 'Rewe', category: 'dairy', checked: false, addedByMemberId: 'm1' },
  { id: 'g6', name: 'Free Range Eggs', amount: '18 pack', store: 'Rewe', category: 'dairy', checked: true, addedByMemberId: 'm5' },
  { id: 'g7', name: 'Chicken Breast', amount: '800g', store: 'Rewe', category: 'meat', checked: false, addedByMemberId: 'm2' },
  { id: 'g8', name: 'Sparkling Lemon Water', amount: '12 cans', store: 'Rewe', category: 'pantry', checked: false, addedByMemberId: 'm3' },
  { id: 'g9', name: 'Dishwasher Pods', amount: '1 pack', store: 'dm', category: 'household', checked: false, addedByMemberId: 'm1' },
  { id: 'g10', name: 'Paper Towels', amount: '4 rolls', store: 'dm', category: 'household', checked: false, addedByMemberId: 'm2' },
  { id: 'g11', name: 'Sourdough Loaf', amount: '1 fresh loaf', store: 'Bakery', category: 'bakery', checked: false, addedByMemberId: 'm5' },
];

export const INITIAL_CHORES: Chore[] = [
  { id: 'c1', title: 'Feed & brush Barnaby the Golden Retriever 🐕', assignedMemberId: 'm3', frequency: 'daily', completed: true, stars: 2 },
  { id: 'c2', title: 'Empty dishwasher & put away clean cups', assignedMemberId: 'm4', frequency: 'daily', completed: false, stars: 3 },
  { id: 'c3', title: 'Take out recycling and compost bins', assignedMemberId: 'm3', frequency: 'weekly', completed: false, stars: 4 },
  { id: 'c4', title: 'Tidy up living room playroom art supplies', assignedMemberId: 'm4', frequency: 'daily', completed: true, stars: 2 },
  { id: 'c5', title: 'Water backyard tomato & herb planters', assignedMemberId: 'm5', frequency: 'daily', completed: true, stars: 3 },
];

export const INITIAL_NOTES: PinnedNote[] = [
  {
    id: 'n1',
    title: '🏡 Home Wi-Fi Network',
    content: 'SSID: "SunflowerCottage-5G" | Password: "SunnyPancakes2026!" - Guest network has no pass.',
    isPinned: true,
    tag: 'wifi',
    authorMemberId: 'm2',
    createdAt: '2026-09-01',
  },
  {
    id: 'n2',
    title: '🚌 School Bus & Pickup Reminder',
    content: 'Route 14 drops off Leo & Mia at the corner of Elm St at 3:15 PM. On Thursdays, Alex picks up early for robotics.',
    isPinned: true,
    tag: 'urgent',
    authorMemberId: 'm1',
    createdAt: '2026-09-10',
  },
  {
    id: 'n3',
    title: '🌟 Family Shoutout: Mia’s Art Ribbon!',
    content: 'Huge high five to Mia for winning 1st place in the nature watercolor contest! Ice cream celebration this Saturday!',
    isPinned: false,
    tag: 'fun',
    authorMemberId: 'm1',
    createdAt: '2026-09-17',
  },
];
