import { Recipe } from '../types';

export interface RecipeThemeDefinition {
  id: 'healthy' | 'fresh' | 'warming' | 'quick' | 'kids';
  name: string;
  icon: string;
  description: string;
  colorClass: string;
  badgeClass: string;
}

export const RECIPE_THEMES: RecipeThemeDefinition[] = [
  {
    id: 'healthy',
    name: 'Gesund & Vital',
    icon: '🥗',
    description: 'Leichte, nährstoffreiche Küche mit viel buntem Gemüse & Proteinen',
    colorClass: 'emerald',
    badgeClass: 'bg-emerald-100 dark:bg-emerald-950/70 text-emerald-800 dark:text-emerald-300 border-emerald-300 dark:border-emerald-700',
  },
  {
    id: 'fresh',
    name: 'Frisch & Sommerlich',
    icon: '🍋',
    description: 'Knackige Salate, leichte mediterrane Pasta & bunte Bowls',
    colorClass: 'teal',
    badgeClass: 'bg-teal-100 dark:bg-teal-950/70 text-teal-800 dark:text-teal-300 border-teal-300 dark:border-teal-700',
  },
  {
    id: 'warming',
    name: 'Wärmend & Deftig',
    icon: '🍲',
    description: 'Wohltuende Eintöpfe, cremige Currys, Aufläufe & Ofengerichte',
    colorClass: 'orange',
    badgeClass: 'bg-orange-100 dark:bg-orange-950/70 text-orange-800 dark:text-orange-300 border-orange-300 dark:border-orange-700',
  },
  {
    id: 'quick',
    name: 'Blitzschnell (< 25m)',
    icon: '⚡',
    description: 'Stressfreie Feierabendgerichte in unter 25 Minuten fertig auf dem Tisch',
    colorClass: 'amber',
    badgeClass: 'bg-amber-100 dark:bg-amber-950/70 text-amber-800 dark:text-amber-300 border-amber-300 dark:border-amber-700',
  },
  {
    id: 'kids',
    name: 'Kinder-Hits',
    icon: '👶',
    description: 'Von Kindern heiß geliebt, mild gewürzt und garantiert tellerleer',
    colorClass: 'purple',
    badgeClass: 'bg-purple-100 dark:bg-purple-950/70 text-purple-800 dark:text-purple-300 border-purple-300 dark:border-purple-700',
  },
];

export const CURATED_RECIPE_CATALOG: Recipe[] = [
  // 1. GESUND & VITAL (healthy)
  {
    id: 'cat_h1',
    title: 'Gegrillter Lachs mit Zitronen-Spargel & Süßkartoffeln',
    prepTime: '25 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    notes: 'Reich an Omega-3-Fettsäuren. Der Spargel kann im Winter durch Brokkoli ersetzt werden.',
    ingredients: [
      { name: 'Lachsfilet (frisch)', amount: '600g', category: 'meat' },
      { name: 'Grüner Spargel oder Brokkoli', amount: '500g', category: 'produce' },
      { name: 'Süßkartoffeln', amount: '2 große', category: 'produce' },
      { name: 'Bio-Zitrone', amount: '1 Stück', category: 'produce' },
      { name: 'Olivenöl', amount: '3 EL', category: 'pantry' },
      { name: 'Meersalz & Pfeffer', amount: 'nach Belieben', category: 'pantry' },
    ],
    instructions: [
      'Süßkartoffeln in Würfel schneiden und mit 2 EL Olivenöl bei 200°C 20 Min. im Ofen backen.',
      'Grünen Spargel an den Enden kürzen, Lachsfilet mit Zitronensaft, Salz und Pfeffer würzen.',
      'Lachs in der Pfanne je Seite 3-4 Min. anbraten. Den Spargel die letzten 5 Min. mitbraten.',
      'Alles zusammen auf Tellern mit frischen Zitronenspalten servieren.',
    ],
  },
  {
    id: 'cat_h2',
    title: 'Bunte Quinoa-Power-Bowl mit Avocado & Feta',
    prepTime: '20 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    notes: 'Bunt, knackig und vegetarisch. Jeder am Tisch kann sich seine Schale selbst garnieren.',
    ingredients: [
      { name: 'Quinoa', amount: '250g', category: 'pantry' },
      { name: 'Reife Avocados', amount: '2 Stück', category: 'produce' },
      { name: 'Gurke', amount: '1 Stück', category: 'produce' },
      { name: 'Kichererbsen (Dose)', amount: '1 Dose (400g)', category: 'pantry' },
      { name: 'Feta-Käse', amount: '150g', category: 'dairy' },
      { name: 'Granatapfelkerne', amount: '50g', category: 'produce' },
    ],
    instructions: [
      'Quinoa nach Packungsanleitung in leichtem Salzwasser ca. 15 Min. gar kochen und abkühlen lassen.',
      'Kichererbsen abspülen, Gurke würfeln und Avocado in feine Scheiben schneiden.',
      'Quinoa auf Bowls verteilen, mit Gemüse und Kichererbsen belegen.',
      'Feta darüber bröseln und mit Olivenöl, Limettensaft und Granatapfelkernen toppen.',
    ],
  },
  {
    id: 'cat_h3',
    title: 'Hähnchen-Brokkoli-Pfanne mit Sesam & Cashews',
    prepTime: '20 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80',
    notes: 'Proteinreich und zuckerarm. Schmeckt hervorragend mit Basmatireis.',
    ingredients: [
      { name: 'Hähnchenbrustfilet', amount: '500g', category: 'meat' },
      { name: 'Frischer Brokkoli', amount: '1 großer Kopf', category: 'produce' },
      { name: 'Cashewkerne', amount: '60g', category: 'snacks' },
      { name: 'Sojasauce (salzreduziert)', amount: '4 EL', category: 'pantry' },
      { name: 'Sesamöl & Knoblauch', amount: '2 Zehen', category: 'produce' },
      { name: 'Basmatireis', amount: '250g', category: 'pantry' },
    ],
    instructions: [
      'Reis aufsetzen und gar kochen.',
      'Hähnchen in mundgerechte Streifen schneiden und scharf in etwas Sesamöl anbraten.',
      'Brokkoli in Röschen teilen und mit Knoblauch zum Fleisch geben, 5 Min. knackig braten.',
      'Mit Sojasauce ablöschen, Cashewkerne und Sesam untermischen und sofort servieren.',
    ],
  },
  {
    id: 'cat_h4',
    title: 'Mediterraner Kichererbsen-Spinat-Eintopf',
    prepTime: '25 Min.',
    servings: 5,
    category: 'healthy',
    theme: 'healthy',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80',
    notes: 'Rein pflanzlich, voller Ballaststoffe und herrlich aromatisch mit Kreuzkümmel.',
    ingredients: [
      { name: 'Kichererbsen', amount: '2 Dosen', category: 'pantry' },
      { name: 'Baby-Spinat', amount: '250g', category: 'produce' },
      { name: 'Gehackte Tomaten', amount: '2 Dosen', category: 'pantry' },
      { name: 'Zwiebel & Knoblauch', amount: '2 Stück', category: 'produce' },
      { name: 'Kreuzkümmel & Paprikapulver', amount: '1 TL je', category: 'pantry' },
    ],
    instructions: [
      'Zwiebeln und Knoblauch fein hacken und in Olivenöl glasig dünsten.',
      'Gewürze kurz mit anrösten, dann Tomaten und Kichererbsen hinzugeben und 15 Min. köcheln lassen.',
      'Den frischen Spinat unterrühren, bis er zusammenfällt.',
      'Mit etwas Naturjoghurt und Fladenbrot servieren.',
    ],
  },

  // 2. FRISCH & SOMMERLICH (fresh)
  {
    id: 'cat_f1',
    title: 'Frische Sommer-Pasta mit Kirschtomaten & Burrata',
    prepTime: '18 Min.',
    servings: 4,
    category: 'quick',
    theme: 'fresh',
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Urlaubsfeeling pur! Die cremig-zarte Burrata schmilzt über den heißen Nudeln.',
    ingredients: [
      { name: 'Spaghetti oder Linguine', amount: '500g', category: 'pantry' },
      { name: 'Süße Kirschtomaten', amount: '400g', category: 'produce' },
      { name: 'Burrata oder Büffelmozzarella', amount: '2 Kugeln', category: 'dairy' },
      { name: 'Frisches Basilikum', amount: '1 Bund', category: 'produce' },
      { name: 'Knoblauchzehen', amount: '3 Zehen', category: 'produce' },
      { name: 'Gutes Olivenöl', amount: '4 EL', category: 'pantry' },
    ],
    instructions: [
      'Spaghetti in reichlich Salzwasser al dente kochen.',
      'Kirschtomaten halbieren und mit Knoblauch in Olivenöl anschwitzen, bis sie aufplatzen.',
      'Pasta direkt aus dem Wasser zu den Tomaten heben und durchschwenken.',
      'Mit viel frischem Basilikum anrichten und je Teller eine halbe Burrata darauf platzieren.',
    ],
  },
  {
    id: 'cat_f2',
    title: 'Mediterrane Halloumi-Gemüse-Wraps mit Minz-Joghurt',
    prepTime: '20 Min.',
    servings: 4,
    category: 'quick',
    theme: 'fresh',
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80',
    notes: 'Knusprig gebratener Halloumi kombiniert mit kühlem Kräuterjoghurt und Gurke.',
    ingredients: [
      { name: 'Halloumi-Grillkäse', amount: '2 Packungen (450g)', category: 'dairy' },
      { name: 'Weizentortillas / Wraps', amount: '6 Stück', category: 'bakery' },
      { name: 'Griechischer Joghurt', amount: '250g', category: 'dairy' },
      { name: 'Frische Minze', amount: '1 Bund', category: 'produce' },
      { name: 'Römersalat & Gurke', amount: 'je 1 Stück', category: 'produce' },
      { name: 'Kirschtomaten', amount: '200g', category: 'produce' },
    ],
    instructions: [
      'Halloumi in fingerdicke Scheiben schneiden und in einer Pfanne goldgelb braten.',
      'Joghurt mit fein gehackter Minze, Salz, Pfeffer und etwas Zitronensaft verrühren.',
      'Wraps kurz erwärmen, mit Joghurt bestreichen und mit Salat, Tomaten, Gurken und Käse füllen.',
      'Fest aufrollen, schräg halbieren und genießen.',
    ],
  },
  {
    id: 'cat_f3',
    title: 'Knackige Thai-Erdnuss-Nudeln mit Gurke & Koriander',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'fresh',
    imageUrl: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=600&q=80',
    notes: 'Kalt oder lauwarm ein Genuss. Die cremige Erdnusssauce lieben Groß und Klein.',
    ingredients: [
      { name: 'Mie-Nudeln oder Bandnudeln', amount: '350g', category: 'pantry' },
      { name: 'Erdnussbutter (cremig)', amount: '4 EL', category: 'pantry' },
      { name: 'Sojasauce & Ahornsirup', amount: 'je 2 EL', category: 'pantry' },
      { name: 'Limettensaft', amount: 'von 2 Limetten', category: 'produce' },
      { name: 'Gurke & Möhren (gestiftelt)', amount: 'je 2 Stück', category: 'produce' },
      { name: 'Geröstete Erdnüsse', amount: '50g', category: 'snacks' },
    ],
    instructions: [
      'Nudeln kochen und unter kaltem Wasser abschrecken.',
      'Erdnussbutter mit Sojasauce, Limettensaft, Ahornsirup und 3 EL warmem Wasser glattrühren.',
      'Nudeln mit dem gestiftelten Gemüse und der Sauce vermengen.',
      'Mit gehackten Erdnüssen und frischem Koriander bestreuen.',
    ],
  },
  {
    id: 'cat_f4',
    title: 'Cremiges Zucchini-Zitronen-Risotto mit Parmesan',
    prepTime: '30 Min.',
    servings: 4,
    category: 'comfort',
    theme: 'fresh',
    imageUrl: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=600&q=80',
    notes: 'Sommerlich frisch dank Zitronenabrieb und zarten Zucchiniraspeln.',
    ingredients: [
      { name: 'Risotto-Reis (Arborio)', amount: '300g', category: 'pantry' },
      { name: 'Zucchini', amount: '2 kleine', category: 'produce' },
      { name: 'Gemüsebrühe', amount: '1 Liter', category: 'pantry' },
      { name: 'Bio-Zitrone (Abrieb & Saft)', amount: '1 Stück', category: 'produce' },
      { name: 'Parmesan frisch gerieben', amount: '80g', category: 'dairy' },
      { name: 'Butter', amount: '40g', category: 'dairy' },
    ],
    instructions: [
      'Schalotte fein würfeln und in 20g Butter glasig anbraten, Risotto-Reis kurz mitrösten.',
      'Schöpflöffelweise heiße Brühe zugeben und unter ständigem Rühren einköcheln lassen.',
      'Nach 15 Min. die geraspelte Zucchini unterrühren.',
      'Vom Herd nehmen, restliche Butter, Parmesan, Zitronensaft und Abrieb einrühren. Cremig servieren.',
    ],
  },

  // 3. WÄRMEND & DEFTIG (warming)
  {
    id: 'cat_w1',
    title: 'Wärmendes Süßkartoffel-Kichererbsen-Curry mit Kokos',
    prepTime: '30 Min.',
    servings: 5,
    category: 'comfort',
    theme: 'warming',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=600&q=80',
    notes: 'Das ultimative Soulfood für herbstliche oder regnerische Abende.',
    ingredients: [
      { name: 'Süßkartoffeln', amount: '2 große (600g)', category: 'produce' },
      { name: 'Kichererbsen (Dose)', amount: '1 Dose', category: 'pantry' },
      { name: 'Kokosmilch (cremig)', amount: '1 Dose (400ml)', category: 'pantry' },
      { name: 'Gehackte Tomaten', amount: '1 Dose', category: 'pantry' },
      { name: 'Mildes gelbes Currypulver', amount: '2 EL', category: 'pantry' },
      { name: 'Frischer Babyspinat', amount: '150g', category: 'produce' },
      { name: 'Basmatireis', amount: '300g', category: 'pantry' },
    ],
    instructions: [
      'Süßkartoffeln schälen und in mundgerechte Stücke würfeln.',
      'Currypulver mit Zwiebeln und Knoblauch kurz in Öl anbraten, bis es duftet.',
      'Süßkartoffeln, Kichererbsen, Tomaten und Kokosmilch zugeben, 20 Min. sanft köcheln.',
      'Babyspinat ganz zum Schluss unterrühren. Zusammen mit duftendem Reis servieren.',
    ],
  },
  {
    id: 'cat_w2',
    title: 'Herzhafte Familien-Lasagne Bolognese al Forno',
    prepTime: '55 Min.',
    servings: 6,
    category: 'family-favorite',
    theme: 'warming',
    imageUrl: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=600&q=80',
    notes: 'Der unangefochtene Klassiker. Lässt sich perfekt am Vortag vorbereiten.',
    ingredients: [
      { name: 'Lasagneplatten', amount: '1 Packung (500g)', category: 'pantry' },
      { name: 'Rinderhackfleisch', amount: '600g', category: 'meat' },
      { name: 'Passierte Tomaten', amount: '2 Flaschen (1kg)', category: 'pantry' },
      { name: 'Möhren & Sellerie', amount: 'je 2 Stück', category: 'produce' },
      { name: 'Béchamelsauce oder Ricotta', amount: '400ml', category: 'dairy' },
      { name: 'Geriebener Gouda oder Mozzarella', amount: '200g', category: 'dairy' },
    ],
    instructions: [
      'Gemüse fein würfeln, mit Hackfleisch scharf anbraten und mit Tomaten 30 Min. einköcheln.',
      'In einer großen Auflaufform schichten: Bolognese, Nudelplatten, Béchamel.',
      'Als oberste Schicht Béchamelsauce und reichlich Käse verteilen.',
      'Bei 190°C Ober-/Unterhitze ca. 35 Min. goldbraun überbacken.',
    ],
  },
  {
    id: 'cat_w3',
    title: 'Deftiger Kartoffel-Lauch-Auflauf mit Knusperkruste',
    prepTime: '45 Min.',
    servings: 5,
    category: 'comfort',
    theme: 'warming',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
    notes: 'Wärmende Hausmannskost. Wer mag, gibt noch Schinkenwürfel hinzu.',
    ingredients: [
      { name: 'Vorwiegend festkochende Kartoffeln', amount: '1 kg', category: 'produce' },
      { name: 'Lauch / Porree', amount: '2 Stangen', category: 'produce' },
      { name: 'Sahne oder Pflanzensahne', amount: '250ml', category: 'dairy' },
      { name: 'Milch', amount: '150ml', category: 'dairy' },
      { name: 'Muskatnuss frisch gerieben', amount: '1 Prise', category: 'pantry' },
      { name: 'Bergkäse oder Gruyère', amount: '150g', category: 'dairy' },
    ],
    instructions: [
      'Kartoffeln schälen und in feine Scheiben hobeln. Lauch in Ringe schneiden.',
      'Sahne mit Milch, Knoblauch, Salz, Pfeffer und Muskat verquirlen.',
      'Kartoffeln und Lauch abwechselnd in eine Auflaufform fächern.',
      'Sahnemischung darübergießen, mit Käse bestreuen und bei 180°C 40 Min. backen.',
    ],
  },
  {
    id: 'cat_w4',
    title: 'Würziger Kürbis-Eintopf mit roten Linsen & Ingwer',
    prepTime: '30 Min.',
    servings: 5,
    category: 'comfort',
    theme: 'warming',
    imageUrl: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?auto=format&fit=crop&w=600&q=80',
    notes: 'Hokkaido-Kürbis muss nicht geschält werden! Wunderbar samtig und gesund.',
    ingredients: [
      { name: 'Hokkaido-Kürbis', amount: '1 kleiner (800g)', category: 'produce' },
      { name: 'Rote Linsen', amount: '200g', category: 'pantry' },
      { name: 'Frischer Ingwer & Knoblauch', amount: '1 Stück', category: 'produce' },
      { name: 'Gemüsebrühe', amount: '800ml', category: 'pantry' },
      { name: 'Kokosmilch', amount: '200ml', category: 'pantry' },
      { name: 'Kürbiskerne zum Toppen', amount: '40g', category: 'snacks' },
    ],
    instructions: [
      'Kürbis entkernen und würfeln. Zwiebel und Ingwer reiben und anschwitzen.',
      'Kürbis und rote Linsen zugeben, mit Gemüsebrühe aufgießen und 20 Min. weich kochen.',
      'Mit einem Pürierstab cremig pürieren, Kokosmilch unterrühren und abschmecken.',
      'In Schalen füllen und mit gerösteten Kürbiskernen und Kürbisöl verfeinern.',
    ],
  },

  // 4. BLITZSCHNELL (< 25m) (quick)
  {
    id: 'cat_q1',
    title: '20-Minuten Gnocchi-Pfanne mit Spinat & Tomaten',
    prepTime: '18 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80',
    notes: 'Gnocchi werden direkt in der Pfanne knusprig gebraten – kein Nudelwasser nötig!',
    ingredients: [
      { name: 'Frische Gnocchi (Kühlregal)', amount: '600g', category: 'dairy' },
      { name: 'Kirschtomaten', amount: '250g', category: 'produce' },
      { name: 'Frischer Spinat', amount: '150g', category: 'produce' },
      { name: 'Mini-Mozzarella-Kugeln', amount: '1 Beutel (125g)', category: 'dairy' },
      { name: 'Pesto Genovese (grün)', amount: '3 EL', category: 'pantry' },
    ],
    instructions: [
      'Gnocchi in etwas Butter oder Olivenöl ca. 8 Min. anbraten, bis sie goldbraun und knusprig sind.',
      'Halbierte Kirschtomaten zugeben und 3 Min. mitschwenken.',
      'Spinat und grünes Pesto unterheben, bis der Spinat zusammenfällt.',
      'Mozzarellakugeln einstreuen, Pfanne zudecken und 2 Min. schmelzen lassen.',
    ],
  },
  {
    id: 'cat_q2',
    title: 'Schnelle Käse-Quesadillas mit Mais & Guacamole',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    notes: 'Ein Fest für die ganze Familie. Schmeckt fantastisch mit selbstgemachtem Limetten-Dip.',
    ingredients: [
      { name: 'Weizentortillas', amount: '8 Stück', category: 'bakery' },
      { name: 'Geriebener Cheddar oder Gouda', amount: '200g', category: 'dairy' },
      { name: 'Süßmais (Dose)', amount: '1 kleine Dose', category: 'pantry' },
      { name: 'Schwarze Bohnen (Dose)', amount: '1/2 Dose', category: 'pantry' },
      { name: 'Reife Avocados', amount: '2 Stück', category: 'produce' },
      { name: 'Sauerrahm', amount: '1 Becher', category: 'dairy' },
    ],
    instructions: [
      'Eine Tortilla in eine heiße Pfanne legen, mit Käse, Mais und Bohnen belegen, zweite Tortilla auflegen.',
      'Von beiden Seiten je 2-3 Min. goldbraun und knusprig backen, bis der Käse schmilzt.',
      'In Viertel schneiden.',
      'Mit zerdrückter Avocado (Zitrone, Salz) und Sauerrahm servieren.',
    ],
  },
  {
    id: 'cat_q3',
    title: 'Cremige Tortellini in Salbeibutter & Parmesan',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Echtes italienisches Feierabendessen. Salbei vorher kurz knusprig anbraten.',
    ingredients: [
      { name: 'Frische Ricotta-Spinat-Tortellini', amount: '500g', category: 'dairy' },
      { name: 'Gute Butter', amount: '70g', category: 'dairy' },
      { name: 'Frische Salbeiblätter', amount: '15 Blätter', category: 'produce' },
      { name: 'Parmesan am Stück', amount: '60g', category: 'dairy' },
      { name: 'Schwarzer Pfeffer & Meersalz', amount: 'nach Geschmack', category: 'pantry' },
    ],
    instructions: [
      'Tortellini in siedendem Salzwasser nach Packungsanleitung 3-4 Min. ziehen lassen.',
      'Butter in einer weiten Pfanne schmelzen, Salbeiblätter hineingeben und knusprig braten.',
      'Tortellini direkt in die schäumende Salbeibutter geben und schwenken.',
      'Auf Tellern anrichten und reichlich frischen Parmesan darüber hobeln.',
    ],
  },
  {
    id: 'cat_q4',
    title: 'Knuspriger Elsässer Blitz-Flammkuchen',
    prepTime: '20 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    imageUrl: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=600&q=80',
    notes: 'Hauchdünn, knusprig und in nur 10 Minuten im Ofen gebacken.',
    ingredients: [
      { name: 'Flammkuchenteig (Kühlregal)', amount: '2 Rollen', category: 'bakery' },
      { name: 'Crème fraîche oder Schmand', amount: '2 Becher (300g)', category: 'dairy' },
      { name: 'Räucherspeck- oder Schinkenwürfel', amount: '150g', category: 'meat' },
      { name: 'Rote Zwiebeln', amount: '2 Stück', category: 'produce' },
      { name: 'Frischer Schnittlauch', amount: '1 Bund', category: 'produce' },
    ],
    instructions: [
      'Ofen auf 220°C Ober-/Unterhitze vorheizen.',
      'Teig auf Backblechen ausrollen und dünn mit Crème fraîche bestreichen. Kräftig pfeffern.',
      'Zwiebeln in feine Halbringe schneiden und mit Schinkenwürfeln auf dem Teig verteilen.',
      '10-12 Min. backen, bis die Ränder goldbraun und kross sind. Mit Schnittlauch garnieren.',
    ],
  },

  // 5. KINDER-HITS (kids)
  {
    id: 'cat_k1',
    title: 'Goldene Apfel-Zimt-Pancakes mit Ahornsirup',
    prepTime: '20 Min.',
    servings: 4,
    category: 'family-favorite',
    theme: 'kids',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=600&q=80',
    notes: 'Der Liebling aller Kinder am Samstag oder als süßes Abendessen.',
    ingredients: [
      { name: 'Weizenmehl', amount: '350g', category: 'pantry' },
      { name: 'Vollmilch', amount: '300ml', category: 'dairy' },
      { name: 'Eier', amount: '3 Stück', category: 'dairy' },
      { name: 'Süße Äpfel (z.B. Elstar)', amount: '2 Stück', category: 'produce' },
      { name: 'Zimt & Backpulver', amount: 'je 1 TL', category: 'pantry' },
      { name: 'Echter Ahornsirup', amount: 'nach Belieben', category: 'pantry' },
    ],
    instructions: [
      'Mehl, Backpulver, Milch, Eier und Zimt zu einem dickflüssigen Teig verrühren.',
      'Äpfel schälen und in feine Scheiben hobeln, unter den Teig heben.',
      'In einer Pfanne mit etwas Butter handtellergroße Pancakes von beiden Seiten goldbraun backen.',
      'Warm mit Ahornsirup und frischen Apfelschnitzen servieren.',
    ],
  },
  {
    id: 'cat_k2',
    title: 'Bunte Nudeln mit der geheimen 5-Gemüse-Sauce',
    prepTime: '25 Min.',
    servings: 5,
    category: 'family-favorite',
    theme: 'kids',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281057?auto=format&fit=crop&w=600&q=80',
    notes: 'Der Eltern-Geheimtipp: Karotten, Zucchini und Paprika werden samtweich püriert.',
    ingredients: [
      { name: 'Lieblingsnudeln (z.B. Fussili oder Penne)', amount: '500g', category: 'pantry' },
      { name: 'Möhren', amount: '3 Stück', category: 'produce' },
      { name: 'Zucchini', amount: '1 kleine', category: 'produce' },
      { name: 'Rote Paprika', amount: '1 Stück', category: 'produce' },
      { name: 'Passierte Tomaten', amount: '1 Flasche (500ml)', category: 'pantry' },
      { name: 'Frischkäse oder Sahne', amount: '2 EL', category: 'dairy' },
      { name: 'Parmesankäse', amount: '50g', category: 'dairy' },
    ],
    instructions: [
      'Gemüse klein würfeln und in 1 EL Öl 5 Min. weich dünsten.',
      'Passierte Tomaten angießen und 10 Min. köcheln lassen.',
      'Mit dem Pürierstab komplett glatt pürieren, Frischkäse unterrühren für milde Cremigkeit.',
      'Mit heißen Nudeln und viel Parmesan servieren – kein Gemüsestückchen mehr zu sehen!',
    ],
  },
  {
    id: 'cat_k3',
    title: 'Knusprige Hähnchen-Knuspersticks mit Ofen-Wedges',
    prepTime: '30 Min.',
    servings: 4,
    category: 'family-favorite',
    theme: 'kids',
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
    notes: 'Gesünder als gekauft: Im Ofen gebacken mit knuspriger Cornflakes-Kruste.',
    ingredients: [
      { name: 'Hähnchenbrustfilet', amount: '500g', category: 'meat' },
      { name: 'Ungesüßte Cornflakes', amount: '150g', category: 'pantry' },
      { name: 'Eier', amount: '2 Stück', category: 'dairy' },
      { name: 'Kartoffeln für Wedges', amount: '800g', category: 'produce' },
      { name: 'Paprikapulver edelsüß', amount: '1 TL', category: 'pantry' },
    ],
    instructions: [
      'Kartoffeln in Spalten schneiden, mit Öl und Paprika mischen und bei 200°C 25 Min. backen.',
      'Hähnchen in Sticks schneiden. Cornflakes in einem Gefrierbeutel grob zerdrücken.',
      'Fleisch erst in verquirltem Ei, dann in den knusprigen Cornflakes wenden.',
      'Die letzten 15 Min. mit auf das Backblech zu den Kartoffeln legen, bis alles goldbraun ist.',
    ],
  },
  {
    id: 'cat_k4',
    title: 'Bunte Mini-Pizzen zum Selberbelegen',
    prepTime: '25 Min.',
    servings: 5,
    category: 'family-favorite',
    theme: 'kids',
    imageUrl: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=600&q=80',
    notes: 'Kinder lieben es, ihre eigenen Gesichter und Muster mit Belägen zu legen!',
    ingredients: [
      { name: 'Frischer Pizzateig', amount: '2 Rollen', category: 'bakery' },
      { name: 'Pizzasauce', amount: '1 Glas', category: 'pantry' },
      { name: 'Geriebener Mozzarella', amount: '200g', category: 'dairy' },
      { name: 'Mais, Paprika, Schinken, Champignons', amount: 'kleine Schälchen', category: 'produce' },
    ],
    instructions: [
      'Teig mit einem Glas oder Förmchen in handgroße runde Mini-Pizzen ausstechen.',
      'Alle Zutaten in kleinen Schüsseln auf den Familientisch stellen.',
      'Jedes Kind bestreicht seine Pizzen mit Sauce und belegt sie kreativ.',
      'Bei 220°C für 10-12 Min. backen, bis der Käse herrlich blubbert.',
    ],
  },
];
