import { Recipe } from '../types';

export interface RecipeThemeDefinition {
  id: 'healthy' | 'fresh' | 'warming' | 'quick' | 'kids';
  name: string;
  icon: string;
  description: string;
  colorClass: string;
  badgeClass: string;
}

export const RECIPE_THEMES: RecipeThemeDefinition[] = [
  {
    id: 'healthy',
    name: 'Gesund & Vital',
    icon: '🥗',
    description: 'Leichte, nährstoffreiche Küche mit viel buntem Gemüse & wertvollen Proteinen',
    colorClass: 'emerald',
    badgeClass: 'bg-emerald-100 dark:bg-emerald-950/70 text-emerald-800 dark:text-emerald-300 border-emerald-300 dark:border-emerald-700',
  },
  {
    id: 'fresh',
    name: 'Frisch & Sommerlich',
    icon: '🍋',
    description: 'Knackige Salate, leichte mediterrane Pasta & frische Bowls',
    colorClass: 'teal',
    badgeClass: 'bg-teal-100 dark:bg-teal-950/70 text-teal-800 dark:text-teal-300 border-teal-300 dark:border-teal-700',
  },
  {
    id: 'warming',
    name: 'Wärmend & Deftig',
    icon: '🍲',
    description: 'Wohltuende Eintöpfe, cremige Currys, Aufläufe & traditionelle Hausmannskost',
    colorClass: 'orange',
    badgeClass: 'bg-orange-100 dark:bg-orange-950/70 text-orange-800 dark:text-orange-300 border-orange-300 dark:border-orange-700',
  },
  {
    id: 'quick',
    name: 'Blitzschnell (< 25m)',
    icon: '⚡',
    description: 'Stressfreie Feierabendgerichte in unter 25 Minuten fertig auf dem Tisch',
    colorClass: 'amber',
    badgeClass: 'bg-amber-100 dark:bg-amber-950/70 text-amber-800 dark:text-amber-300 border-amber-300 dark:border-amber-700',
  },
  {
    id: 'kids',
    name: 'Kinder-Hits',
    icon: '👶',
    description: 'Von Kindern heiß geliebt, mild gewürzt und garantiert tellerleer',
    colorClass: 'purple',
    badgeClass: 'bg-purple-100 dark:bg-purple-950/70 text-purple-800 dark:text-purple-300 border-purple-300 dark:border-purple-700',
  },
];

export const CURATED_RECIPE_CATALOG: Recipe[] = [
  // ==========================================
  // 1. GESUND & VITAL (healthy) - 8 Rezepte
  // ==========================================
  {
    id: 'cat_h1',
    title: 'Gegrillter Lachs mit Zitronen-Brokkoli & Süßkartoffeln',
    prepTime: '25 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'fish',
    estimatedCost: 16.5,
    synergyBase: 'veggies',
    synergyRole: 'cook-extra',
    synergyTip: 'Röste heute 400g Süßkartoffeln extra: Perfekt für die cremige Ingwer-Suppe am Folgetag (-15 Min.)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    notes: 'Reich an wertvollen Omega-3-Fettsäuren. Die Süßkartoffeln werden im Ofen herrlich karamellisiert.',
    ingredients: [
      { name: 'Lachsfilet (frisch)', amount: '600g', category: 'meat' },
      { name: 'Frischer Brokkoli', amount: '500g', category: 'produce' },
      { name: 'Süßkartoffeln', amount: '800g', category: 'produce' },
      { name: 'Bio-Zitrone', amount: '1 Stück', category: 'produce' },
      { name: 'Natives Olivenöl', amount: '3 EL', category: 'pantry' },
      { name: 'Knoblauchzehen', amount: '2 Zehen', category: 'produce' },
      { name: 'Meersalz', amount: '1 TL', category: 'pantry' },
      { name: 'Schwarzer Pfeffer', amount: '0.5 TL', category: 'pantry' },
    ],
    instructions: [
      'Ofen auf 200°C Ober-/Unterhitze vorheizen. Süßkartoffeln schälen, in 2cm große Würfel schneiden und mit 2 EL Olivenöl, Salz und Pfeffer auf einem Backblech verteilen.',
      'Süßkartoffeln 22-25 Minuten im Ofen goldbraun und weich backen.',
      'Brokkoli in mundgerechte Röschen teilen. In einem Topf mit 100ml Wasser und 1 Prise Salz zugedeckt ca. 4 Minuten bissfest dünsten.',
      'Lachsfilet trocken tupfen, mit etwas Zitronensaft, Salz und Pfeffer würzen. In einer Pfanne mit 1 EL Olivenöl je Seite 3-4 Minuten anbraten, bis er saftig gegart ist.',
      'Fein gehackten Knoblauch kurz zum Brokkoli schwenken.',
      'Lachs auf den gebackenen Süßkartoffeln und Brokkoli mit frischen Zitronenspalten servieren.',
    ],
  },
  {
    id: 'cat_h2',
    title: 'Bunte Quinoa-Power-Bowl mit Avocado & Feta',
    prepTime: '20 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'vegetarian',
    estimatedCost: 11.5,
    synergyBase: 'rice',
    synergyRole: 'use-leftovers',
    synergyTip: 'Nutzt den gekochten Reis vom Vortag als Bowl-Basis: Spart 15 Min. Kochzeit!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    notes: 'Bunt, pflanzlich und proteinreich. Jeder am Familientisch kann seine Schale nach Wunsch toppen.',
    ingredients: [
      { name: 'Bunter Quinoa', amount: '250g', category: 'pantry' },
      { name: 'Reife Avocados', amount: '2 Stück', category: 'produce' },
      { name: 'Salatgurke', amount: '1 Stück', category: 'produce' },
      { name: 'Kirschtomaten', amount: '250g', category: 'produce' },
      { name: 'Kichererbsen (Dose)', amount: '1 Dose (400g)', category: 'pantry' },
      { name: 'Feta-Käse', amount: '200g', category: 'dairy' },
      { name: 'Bio-Zitrone', amount: '1 Stück', category: 'produce' },
      { name: 'Natives Olivenöl', amount: '3 EL', category: 'pantry' },
    ],
    instructions: [
      'Quinoa in einem Sieb heiß abspülen. In 500ml leicht gesalzenem Wasser aufkochen und ca. 15 Minuten bei milder Hitze quellen lassen (oder vorgekochten Reis erwärmen).',
      'Kichererbsen abspülen und trocken tupfen. In einer Pfanne mit 1 EL Olivenöl und Paprikapulver 5 Minuten knusprig anbraten.',
      'Salatgurke würfeln, Kirschtomaten halbieren, Avocados in feine Scheiben schneiden.',
      'Für das Dressing Zitronensaft, 2 EL Olivenöl, Salz, Pfeffer und 1 TL Honig cremig verrühren.',
      'Quinoa in vier Bowls verteilen. Gurke, Tomaten, Kichererbsen und Avocado fächerförmig darauf anrichten.',
      'Feta grob darüber bröckeln und mit dem Zitronen-Dressing beträufeln.',
    ],
  },
  {
    id: 'cat_h3',
    title: 'Zitronen-Hähnchenbrust mit buntem Ofengemüse',
    prepTime: '30 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'poultry',
    estimatedCost: 13.5,
    synergyBase: 'chicken',
    synergyRole: 'cook-extra',
    synergyTip: 'Brate heute 300g Hähnchenbrust extra: Morgen gibt es blitzschnelle Avocado-Hähnchen-Wraps (-15 Min.)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80',
    notes: 'Knuspriges Blechgericht ohne viel Abwasch. Die Zitrone hält das Geflügel herrlich saftig.',
    ingredients: [
      { name: 'Hähnchenbrustfilets', amount: '750g', category: 'meat' },
      { name: 'Zucchini', amount: '2 Stück', category: 'produce' },
      { name: 'Rote Paprika', amount: '2 Stück', category: 'produce' },
      { name: 'Rote Zwiebeln', amount: '2 Stück', category: 'produce' },
      { name: 'Bio-Zitronen', amount: '2 Stück', category: 'produce' },
      { name: 'Getrockneter Oregano', amount: '1 TL', category: 'pantry' },
      { name: 'Getrockneter Thymian', amount: '1 TL', category: 'pantry' },
      { name: 'Natives Olivenöl', amount: '3 EL', category: 'pantry' },
    ],
    instructions: [
      'Backofen auf 200°C Umluft vorheizen. Backblech mit Backpapier auslegen.',
      'Zucchini in Scheiben, Paprika in mundgerechte Stücke und rote Zwiebeln in Spalten schneiden.',
      'Gemüse mit 2 EL Olivenöl, Oregano, Thymian, Salz und Pfeffer vermengen und auf dem Blech verteilen.',
      'Hähnchenbrustfilets mit Zitronensaft, restlichem Olivenöl und Kräutern einreiben und zwischen das Gemüse legen.',
      '1 Zitrone in Scheiben schneiden und auf die Hähnchenbrüste legen.',
      'Im Ofen ca. 22-25 Minuten backen, bis das Hähnchen durchgegart und das Gemüse an den Rändern leicht gebräunt ist.',
    ],
  },
  {
    id: 'cat_h4',
    title: 'Cremiges Süßkartoffel-Kichererbsen-Curry mit Reis',
    prepTime: '25 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'vegetarian',
    estimatedCost: 9.8,
    synergyBase: 'rice',
    synergyRole: 'cook-extra',
    synergyTip: 'Koche heute gleich 500g Reis: Morgen gibt es knusprigen gebratenen Eierreis (-15 Min. Kochzeit)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=600&q=80',
    notes: 'Mild-cremig mit Kokosmilch, perfekt für Familien und wärmend an kühlen Abenden.',
    ingredients: [
      { name: 'Süßkartoffeln', amount: '600g', category: 'produce' },
      { name: 'Kichererbsen (Dose)', amount: '1 Dose (400g)', category: 'pantry' },
      { name: 'Kokosmilch (Dose)', amount: '1 Dose (400ml)', category: 'pantry' },
      { name: 'Gehackte Tomaten (Dose)', amount: '1 Dose (400g)', category: 'pantry' },
      { name: 'Basmatireis', amount: '500g', category: 'pantry' },
      { name: 'Babyspinat', amount: '150g', category: 'produce' },
      { name: 'Zwiebeln', amount: '1 Stück', category: 'produce' },
      { name: 'Frischer Ingwer', amount: '1 daumengroßes Stück', category: 'produce' },
      { name: 'Mildes Currypulver', amount: '2 TL', category: 'pantry' },
    ],
    instructions: [
      'Basmatireis in doppelter Menge Salzwasser aufkochen und 12 Minuten bei milder Hitze quellen lassen.',
      'Zwiebel und Ingwer fein hacken. Süßkartoffeln schälen und in 1.5cm große Würfel schneiden.',
      'In einem großen Topf 1 EL Öl erhitzen, Zwiebel und Ingwer 2 Minuten anschwitzen. Currypulver zugeben und 30 Sekunden anrösten.',
      'Süßkartoffeln, gehackte Tomaten und Kokosmilch hinzufügen. Aufkochen und zugedeckt bei mittlerer Hitze 15 Minuten köcheln lassen.',
      'Abgespülte Kichererbsen und Babyspinat unterrühren, weitere 3 Minuten ziehen lassen, bis der Spinat zusammenfällt.',
      'Mit Salz, Pfeffer und einem Spritzer Limettensaft abschmecken und mit dem duftenden Basmatireis servieren.',
    ],
  },
  {
    id: 'cat_h5',
    title: 'Knusprige Knoblauch-Garnelen auf Zucchini-Nudeln & Kirschtomaten',
    prepTime: '20 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'fish',
    estimatedCost: 15.9,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Low-Carb Traum: Knackige Gemüsespiralen mit aromatischen Riesengarnelen in feinem Olivenöl.',
    ingredients: [
      { name: 'Garnelen', amount: '450g', category: 'meat' },
      { name: 'Zucchini', amount: '4 Stück', category: 'produce' },
      { name: 'Kirschtomaten', amount: '300g', category: 'produce' },
      { name: 'Knoblauchzehen', amount: '3 Zehen', category: 'produce' },
      { name: 'Frische Petersilie', amount: '1 Bund', category: 'produce' },
      { name: 'Bio-Zitrone', amount: '1 Stück', category: 'produce' },
      { name: 'Natives Olivenöl extra', amount: '3 EL', category: 'pantry' },
    ],
    instructions: [
      'Zucchini mit einem Spiralschneider zu Spaghetti (Zoodles) drehen. Kirschtomaten halbieren, Knoblauch in feine Scheiben schneiden.',
      'Garnelen trocken tupfen. 2 EL Olivenöl in einer großen Pfanne erhitzen und die Garnelen je Seite 2 Minuten scharf anbraten.',
      'Garnelen aus der Pfanne nehmen und warmhalten.',
      'In derselben Pfanne restliches Öl erhitzen, Knoblauch und Kirschtomaten 2 Minuten anbraten, bis die Tomaten aufplatzen.',
      'Zucchini-Nudeln zugeben und bei hoher Hitze nur 2 Minuten mit anbraten, damit sie knackig bleiben.',
      'Garnelen und gehackte Petersilie unterheben, mit Zitronensaft, Salz und Pfeffer abschmecken und sofort servieren.',
    ],
  },
  {
    id: 'cat_h6',
    title: 'Würziger Berglinsensalat mit geröstetem Ofenkürbis & Feta',
    prepTime: '30 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'vegetarian',
    estimatedCost: 8.9,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    notes: 'Sättigend, ballaststoffreich und voller nussiger Aromen. Ideal auch als Lunch für den nächsten Tag.',
    ingredients: [
      { name: 'Braune Berglinsen', amount: '250g', category: 'pantry' },
      { name: 'Hokkaido-Kürbis', amount: '500g', category: 'produce' },
      { name: 'Feta-Käse', amount: '150g', category: 'dairy' },
      { name: 'Walnusskerne', amount: '60g', category: 'pantry' },
      { name: 'Rucolasalat', amount: '100g', category: 'produce' },
      { name: 'Balsamico-Essig', amount: '3 EL', category: 'pantry' },
      { name: 'Natives Olivenöl', amount: '3 EL', category: 'pantry' },
      { name: 'Bio-Honig', amount: '1 TL', category: 'pantry' },
    ],
    instructions: [
      'Ofen auf 200°C vorheizen. Hokkaido waschen, entkernen und in 1.5cm Spalten schneiden. Mit 1 EL Öl und Salz 20 Min. rösten.',
      'Berglinsen in 500ml Wasser ca. 20 Minuten bissfest köcheln lassen, dann abgießen.',
      'Walnüsse in einer trockenen Pfanne 3 Minuten anrösten.',
      'Dressing aus Balsamico, 2 EL Olivenöl, Honig, Salz und Pfeffer verrühren.',
      'Laubwarme Linsen mit dem Dressing vermengen, Rucola und Ofenkürbis vorsichtig unterheben.',
      'Mit Feta-Bröseln und gerösteten Walnüssen bestreuen.',
    ],
  },
  {
    id: 'cat_h7',
    title: 'Saftige Putenmedaillons mit grünem Spargel & Ofenkartoffeln',
    prepTime: '25 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'poultry',
    estimatedCost: 14.5,
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80',
    notes: 'Mageres Geflügel kombiniert mit aromatischem grünem Spargel und krossen Rosmarinkartoffeln.',
    ingredients: [
      { name: 'Putenbrustfilet', amount: '600g', category: 'meat' },
      { name: 'Grüner Spargel', amount: '500g', category: 'produce' },
      { name: 'Kleine Kartoffeln (Drillinge)', amount: '700g', category: 'produce' },
      { name: 'Frischer Rosmarin', amount: '2 Zweige', category: 'produce' },
      { name: 'Natives Olivenöl', amount: '3 EL', category: 'pantry' },
      { name: 'Bio-Zitrone', amount: '1 Stück', category: 'produce' },
    ],
    instructions: [
      'Kartoffeln halbieren, mit 2 EL Olivenöl, Rosmarinnadeln und Meersalz auf ein Backblech geben. Bei 200°C 25 Min. backen.',
      'Putenbrust in 8 Medaillons schneiden, leicht flachdrücken, salzen und pfeffern.',
      'Holzige Enden vom grünen Spargel abschneiden, Stangen schräg dritteln.',
      'In einer Pfanne 1 EL Öl erhitzen, Putenmedaillons von jeder Seite ca. 3 Minuten goldbraun braten, herausnehmen.',
      'Spargel in derselben Pfanne 5 Minuten bissfest anbraten, mit Zitronensaft ablöschen.',
      'Putenmedaillons mit grünem Spargel und den knusprigen Kartoffeln servieren.',
    ],
  },
  {
    id: 'cat_h8',
    title: 'Würziger Erdnuss-Tofu mit knackigem Brokkoli & Basmatireis',
    prepTime: '20 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'vegetarian',
    estimatedCost: 9.5,
    synergyBase: 'rice',
    synergyRole: 'use-leftovers',
    synergyTip: 'Nutzt den vorgekochten Reis vom Vortag: In nur 15 Min. fertig auf dem Tisch!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    notes: 'Knusprig gebratener Tofu in herrlich cremiger Erdnusssauce – auch für Tofu-Skeptiker unwiderstehlich.',
    ingredients: [
      { name: 'Natur-Tofu (fest)', amount: '400g', category: 'produce' },
      { name: 'Frischer Brokkoli', amount: '500g', category: 'produce' },
      { name: 'Erdnussbutter (cremig)', amount: '3 EL', category: 'pantry' },
      { name: 'Sojasauce', amount: '3 EL', category: 'pantry' },
      { name: 'Ahornsirup', amount: '1 EL', category: 'pantry' },
      { name: 'Sesamkörner', amount: '2 EL', category: 'pantry' },
      { name: 'Basmatireis', amount: '350g', category: 'pantry' },
      { name: 'Speisestärke', amount: '1 EL', category: 'pantry' },
    ],
    instructions: [
      'Basmatireis nach Packungsanleitung gar kochen (oder gekühlten Reis erwärmen).',
      'Tofu in Küchenpapier kräftig ausdrücken, in 2cm Würfel schneiden und mit 1 EL Speisestärke bestäuben.',
      'In einer Pfanne 2 EL Öl erhitzen, Tofuwürfel von allen Seiten 6-8 Minuten goldbraun und kross anbraten.',
      'Brokkoli in kleine Röschen teilen und 4 Minuten in Salzwasser bissfest blanchieren.',
      'Für die Sauce Erdnussbutter, Sojasauce, Ahornsirup und 4 EL warmes Wasser glattrühren.',
      'Sauce und Brokkoli zum krossen Tofu in die Pfanne geben, 1 Minute schwenken und mit Sesam auf Reis servieren.',
    ],
  },

  // ==========================================
  // 2. FRISCH & SOMMERLICH (fresh) - 8 Rezepte
  // ==========================================
  {
    id: 'cat_f1',
    title: 'Cremige Zitronen-Ricotta-Pasta mit Rucola & Pinienkernen',
    prepTime: '18 Min.',
    servings: 4,
    category: 'quick',
    theme: 'fresh',
    mainProtein: 'pasta',
    estimatedCost: 8.5,
    synergyBase: 'pasta',
    synergyRole: 'cook-extra',
    synergyTip: 'Koche heute 250g Pasta mehr ab: Morgen gibt es den mediterranen Nudelsalat (-15 Min.)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Italienische Sommerküche pur: Leicht, cremig und in der Zeit fertig, in der die Pasta kocht.',
    ingredients: [
      { name: 'Spaghetti', amount: '500g', category: 'pantry' },
      { name: 'Ricotta-Käse', amount: '250g', category: 'dairy' },
      { name: 'Bio-Zitronen', amount: '2 Stück', category: 'produce' },
      { name: 'Rucolasalat', amount: '100g', category: 'produce' },
      { name: 'Pinienkerne', amount: '40g', category: 'pantry' },
      { name: 'Parmesankäse', amount: '80g', category: 'dairy' },
      { name: 'Natives Olivenöl', amount: '2 EL', category: 'pantry' },
    ],
    instructions: [
      'Einen großen Topf Salzwasser aufkochen und Spaghetti al dente garen. Vor dem Abgießen 1 Tasse Nudelkochwasser auffangen.',
      'Pinienkerne in einer kleinen Pfanne ohne Fett 2 Minuten goldgelb rösten, beiseitestellen.',
      'Schale der Bio-Zitronen fein abreiben, Saft auspressen.',
      'Ricotta, Zitronenabrieb, 3 EL Zitronensaft, geriebenen Parmesan und 100ml warmes Nudelwasser zu einer samtigen Sauce rühren.',
      'Heiße Spaghetti mit der Ricotta-Sauce vermengen. Bei Bedarf noch etwas Nudelwasser zugeben.',
      'Mit frischem Rucola, gerösteten Pinienkernen und etwas frisch gemahlenem Pfeffer anrichten.',
    ],
  },
  {
    id: 'cat_f2',
    title: 'Knusprige Fisch-Tacos mit Mango-Avocado-Salsa',
    prepTime: '25 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'fresh',
    mainProtein: 'fish',
    estimatedCost: 13.9,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    notes: 'Frisch, fruchtig und leicht knusprig. Der absolute Favorit für gesellige Taco-Abende.',
    ingredients: [
      { name: 'Kabeljaufilet (frisch)', amount: '500g', category: 'meat' },
      { name: 'Kleine Tortilla-Wraps', amount: '8 Stück', category: 'bakery' },
      { name: 'Reife Mango', amount: '1 Stück', category: 'produce' },
      { name: 'Avocado', amount: '1 Stück', category: 'produce' },
      { name: 'Limetten', amount: '2 Stück', category: 'produce' },
      { name: 'Frischer Koriander', amount: '1 Bund', category: 'produce' },
      { name: 'Rote Zwiebel', amount: '1 Stück', category: 'produce' },
    ],
    instructions: [
      'Mango, Avocado und rote Zwiebel in feine Würfel schneiden. Koriander hacken.',
      'In einer Schüssel mit Saft von 1 Limette, Salz und Pfeffer zur frischen Salsa vermengen.',
      'Kabeljau trocken tupfen, in Streifen schneiden und mit Paprikapulver, Kreuzkümmel und Salz würzen.',
      'Fischstreifen in einer Pfanne mit 2 EL Öl ca. 2-3 Minuten je Seite goldbraun anbraten.',
      'Tortilla-Wraps kurz in einer trockenen Pfanne erwärmen.',
      'Wraps mit warmem Fisch und reichlich Mango-Avocado-Salsa füllen und mit Limettenspalten servieren.',
    ],
  },
  {
    id: 'cat_f3',
    title: 'Griechischer Bauernsalat mit warmem Knoblauch-Fladenbrot',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'fresh',
    mainProtein: 'vegetarian',
    estimatedCost: 8.9,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    notes: 'Klassiker ohne Herdzeit für heiße Sommertage. Schmeckt wie ein Urlaub am Mittelmeer.',
    ingredients: [
      { name: 'Feta-Käse', amount: '250g', category: 'dairy' },
      { name: 'Salatgurken', amount: '2 Stück', category: 'produce' },
      { name: 'Rispentomaten', amount: '500g', category: 'produce' },
      { name: 'Kalamata-Oliven', amount: '100g', category: 'pantry' },
      { name: 'Rote Zwiebeln', amount: '1 Stück', category: 'produce' },
      { name: 'Fladenbrot', amount: '1 Laib', category: 'bakery' },
      { name: 'Natives Olivenöl extra', amount: '4 EL', category: 'pantry' },
      { name: 'Getrockneter Oregano', amount: '1 TL', category: 'pantry' },
    ],
    instructions: [
      'Tomaten in Spalten, Gurken in dicke Halbmonde und rote Zwiebel in feine Ringe schneiden.',
      'Gemüse und Oliven in einer großen Salatschüssel anrichten.',
      'Mit 4 EL bestem Olivenöl, Rotweinessig, Meersalz und Pfeffer marinieren.',
      'Feta in dicke Scheiben schneiden, auf den Salat legen und großzügig mit Oregano bestreuen.',
      'Fladenbrot mit etwas Olivenöl bestreichen und im Ofen bei 180°C 5 Minuten knusprig aufbacken.',
      'Salat sofort mit dem warmen Fladenbrot servieren.',
    ],
  },
  {
    id: 'cat_f4',
    title: 'Caprese-Hähnchenbrust mit geschmolzenem Mozzarella',
    prepTime: '25 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'fresh',
    mainProtein: 'poultry',
    estimatedCost: 12.5,
    synergyBase: 'chicken',
    synergyRole: 'cook-extra',
    synergyTip: 'Brate 1-2 Hähnchenbrüste extra mit: Morgen im Handumdrehen Hähnchen-Wraps zaubern (-15 Min.)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80',
    notes: 'Mit grünem Pesto bestrichen, mit saftigen Tomaten und Mozzarella überbacken.',
    ingredients: [
      { name: 'Hähnchenbrustfilets', amount: '650g', category: 'meat' },
      { name: 'Mozzarella', amount: '2 Kugeln (250g)', category: 'dairy' },
      { name: 'Fleischtomaten', amount: '2 Stück', category: 'produce' },
      { name: 'Basilikum-Pesto', amount: '3 EL', category: 'pantry' },
      { name: 'Balsamico-Glace', amount: '2 EL', category: 'pantry' },
      { name: 'Frisches Basilikum', amount: '1 Bund', category: 'produce' },
      { name: 'Ciabatta-Brot', amount: '1 Stück', category: 'bakery' },
    ],
    instructions: [
      'Ofen auf 200°C Ober-/Unterhitze vorheizen. Auflaufform leicht fetten.',
      'Hähnchenbrüste salzen, pfeffern und in einer Pfanne je Seite 2 Minuten scharf anbraten. In die Form legen.',
      'Jede Hähnchenbrust mit 1 gehäuften EL Pesto bestreichen.',
      'Tomaten und Mozzarella in Scheiben schneiden und abwechselnd fächerförmig auf das Hähnchen schichten.',
      'Im Ofen ca. 15 Minuten überbacken, bis der Mozzarella schmilzt und leicht gebräunt ist.',
      'Mit frischen Basilikumblättern und Balsamico-Glace garnieren. Dazu warmes Ciabatta reichen.',
    ],
  },
  {
    id: 'cat_f5',
    title: 'Mediterraner Nudelsalat mit getrockneten Tomaten & Mozzarella',
    prepTime: '20 Min.',
    servings: 4,
    category: 'quick',
    theme: 'fresh',
    mainProtein: 'pasta',
    estimatedCost: 9.2,
    synergyBase: 'pasta',
    synergyRole: 'use-leftovers',
    synergyTip: 'Nutzt die gekochten Nudeln von gestern: Kalt direkt mit Mozzarella & Tomaten vermengen (-15 Min.)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Ganz ohne Mayonnaise: Leichtes Balsamico-Olivenöl-Dressing mit Rucola und Kernen.',
    ingredients: [
      { name: 'Penne', amount: '400g', category: 'pantry' },
      { name: 'Getrocknete Tomaten in Öl', amount: '100g', category: 'pantry' },
      { name: 'Mini-Mozzarellakugeln', amount: '150g', category: 'dairy' },
      { name: 'Rucola', amount: '100g', category: 'produce' },
      { name: 'Pinienkerne', amount: '40g', category: 'pantry' },
      { name: 'Balsamico-Essig', amount: '3 EL', category: 'pantry' },
      { name: 'Natives Olivenöl', amount: '3 EL', category: 'pantry' },
    ],
    instructions: [
      'Penne nach Packungsanleitung al dente kochen und abkühlen lassen (oder vorgekochte Pasta verwenden).',
      'Getrocknete Tomaten in feine Streifen schneiden, Mini-Mozzarella abtropfen lassen und halbieren.',
      'Pinienkerne in einer trockenen Pfanne 2 Minuten anrösten.',
      'Balsamico, Olivenöl, 1 TL Senf, Salz und Pfeffer zu einem homogenen Dressing aufschlagen.',
      'Nudeln, getrocknete Tomaten und Mozzarella mit dem Dressing vermengen und 10 Minuten durchziehen lassen.',
      'Kurz vor dem Servieren den frischen Rucola und die Pinienkerne unterheben.',
    ],
  },
  {
    id: 'cat_f6',
    title: 'Bunte Halloumi-Gemüse-Wraps mit frischem Minz-Joghurt',
    prepTime: '18 Min.',
    servings: 4,
    category: 'quick',
    theme: 'fresh',
    mainProtein: 'vegetarian',
    estimatedCost: 10.2,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    notes: 'Knusprig gebratener Grillkäse trifft auf kühlen Kräuterjoghurt und knackigen Salat.',
    ingredients: [
      { name: 'Halloumi-Grillkäse', amount: '400g', category: 'dairy' },
      { name: 'Tortilla-Wraps', amount: '6 Stück', category: 'bakery' },
      { name: 'Griechischer Joghurt', amount: '250g', category: 'dairy' },
      { name: 'Frische Minze', amount: '1 Bund', category: 'produce' },
      { name: 'Salatgurke', amount: '1 Stück', category: 'produce' },
      { name: 'Rote Spitzpaprika', amount: '2 Stück', category: 'produce' },
    ],
    instructions: [
      'Halloumi in 1cm dicke Scheiben schneiden. Gurke und Spitzpaprika in dünne Streifen schneiden.',
      'Minze fein hacken und mit Joghurt, 1 TL Zitronensaft, Salz und Pfeffer glattrühren.',
      'Halloumi in einer beschichteten Pfanne mit 1 TL Olivenöl von beiden Seiten je 3 Minuten goldbraun braten.',
      'Tortillas kurz in der heißen Pfanne oder Mikrowelle anwärmen.',
      'Wraps mit Minz-Joghurt bestreichen, mit Gurke, Paprika und warmem Halloumi belegen.',
      'Fest einrollen, schräg halbieren und sofort warm genießen.',
    ],
  },
  {
    id: 'cat_f7',
    title: 'Sommerliche Glasnudel-Bowl mit Erdnuss-Dressing & Gurke',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'fresh',
    mainProtein: 'vegetarian',
    estimatedCost: 8.8,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    notes: 'Erfrischend kalt oder lauwarm. Glasnudeln müssen nur mit kochendem Wasser übergossen werden.',
    ingredients: [
      { name: 'Glasnudeln', amount: '200g', category: 'pantry' },
      { name: 'Möhren', amount: '2 Stück', category: 'produce' },
      { name: 'Salatgurke', amount: '1 Stück', category: 'produce' },
      { name: 'Frühlingszwiebeln', amount: '1 Bund', category: 'produce' },
      { name: 'Geröstete Erdnüsse', amount: '60g', category: 'pantry' },
      { name: 'Limettensaft', amount: '3 EL', category: 'produce' },
      { name: 'Sojasauce', amount: '3 EL', category: 'pantry' },
    ],
    instructions: [
      'Glasnudeln in eine Schüssel geben, mit kochendem Wasser übergießen und 4 Minuten ziehen lassen, dann kalt abspülen.',
      'Möhren und Salatgurke in feine Julienne-Streifen schneiden oder raspeln.',
      'Frühlingszwiebeln in feine Röllchen schneiden. Erdnüsse grob hacken.',
      'Limettensaft, Sojasauce, 1 EL Sesamöl und 1 TL Honig zu einem pikanten Dressing verquirlen.',
      'Glasnudeln mit Gemüse und Dressing vermengen.',
      'In Schalen anrichten und mit gehackten Erdnüssen bestreuen.',
    ],
  },
  {
    id: 'cat_f8',
    title: 'Frische Lachs-Sashimi-Bowl mit Edamame & Duftreis',
    prepTime: '20 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'fresh',
    mainProtein: 'fish',
    estimatedCost: 17.2,
    synergyBase: 'rice',
    synergyRole: 'cook-extra',
    synergyTip: 'Koche heute 500g Reis: Morgen gibt es den schnellen gebratenen Eierreis (-15 Min.)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    notes: 'Sushi-Feeling für zuhause: Frischer Lachs mariniert mit Sesamöl und Sojasauce.',
    ingredients: [
      { name: 'Lachsfilet (frisch)', amount: '500g', category: 'meat' },
      { name: 'Jasminreis', amount: '400g', category: 'pantry' },
      { name: 'Edamame (TK, geschält)', amount: '200g', category: 'produce' },
      { name: 'Reife Avocados', amount: '2 Stück', category: 'produce' },
      { name: 'Sesamöl', amount: '2 EL', category: 'pantry' },
      { name: 'Sojasauce', amount: '3 EL', category: 'pantry' },
      { name: 'Sesamkörner', amount: '2 EL', category: 'pantry' },
    ],
    instructions: [
      'Jasminreis nach Packungsanleitung locker kochen und leicht abkühlen lassen.',
      'Edamame in kochendem Salzwasser 4 Minuten garen, kalt abschrecken.',
      'Lachsfilet in mundgerechte 1.5cm Würfel schneiden. Mit Sojasauce und Sesamöl 5 Minuten marinieren.',
      'Avocado halbieren und in Fächer schneiden.',
      'Reis auf vier Schalen verteilen. Lachs, Edamame und Avocado geordnet darauf platzieren.',
      'Mit geröstetem Sesam garnieren und servieren.',
    ],
  },

  // ==========================================
  // 3. WÄRMEND & DEFTIG (warming) - 8 Rezepte
  // ==========================================
  {
    id: 'cat_w1',
    title: 'Deftige Allgäuer Käsespätzle mit Röstzwiebeln',
    prepTime: '25 Min.',
    servings: 4,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'vegetarian',
    estimatedCost: 9.2,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Beste Hütten-Tradition: Herzhafter Bergkäse zieht herrlich lange Fäden.',
    ingredients: [
      { name: 'Frische Eierspätzle', amount: '750g', category: 'dairy' },
      { name: 'Würziger Bergkäse', amount: '150g', category: 'dairy' },
      { name: 'Emmentaler', amount: '150g', category: 'dairy' },
      { name: 'Zwiebeln', amount: '3 Stück', category: 'produce' },
      { name: 'Butter', amount: '3 EL', category: 'dairy' },
      { name: 'Frischer Schnittlauch', amount: '1 Bund', category: 'produce' },
    ],
    instructions: [
      'Zwiebeln schälen und in dünne Ringe schneiden. In 2 EL Butter bei mittlerer Hitze ca. 12 Minuten goldbraun und weich schmoren.',
      'Spätzle in kochendem Salzwasser kurz erwärmen oder direkt in einer großen Pfanne in 1 EL Butter anschwenken.',
      'Bergkäse und Emmentaler frisch reiben und mischen.',
      'Heiße Spätzle und die Käsemischung abwechselnd in die heiße Pfanne schichten. Mit 50ml Spätzlewasser verrühren, bis der Käse cremig schmilzt.',
      'Mit frisch geriebener Muskatnuss, Salz und kräftig schwarzem Pfeffer abschmecken.',
      'Mit den goldbraunen Schmorzwiebeln und feinem Schnittlauch garniert servieren.',
    ],
  },
  {
    id: 'cat_w2',
    title: 'Cremiges Rotes Linsen-Dal mit Naan-Brot & Reis',
    prepTime: '25 Min.',
    servings: 4,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'vegetarian',
    estimatedCost: 8.5,
    synergyBase: 'rice',
    synergyRole: 'cook-extra',
    synergyTip: 'Koche heute gleich 500g Reis: Morgen gibt es den schnellen gebratenen Eierreis (-15 Min.)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=600&q=80',
    notes: 'Ein indischer Klassiker: Wohltuend, ballaststoffreich und extrem cremig eingekocht.',
    ingredients: [
      { name: 'Rote Linsen', amount: '350g', category: 'pantry' },
      { name: 'Kokosmilch (Dose)', amount: '1 Dose (400ml)', category: 'pantry' },
      { name: 'Gehackte Tomaten (Dose)', amount: '1 Dose (400g)', category: 'pantry' },
      { name: 'Basmatireis', amount: '500g', category: 'pantry' },
      { name: 'Naan-Brot', amount: '1 Packung (2-4 Stk)', category: 'bakery' },
      { name: 'Zwiebeln', amount: '2 Stück', category: 'produce' },
      { name: 'Knoblauchzehen', amount: '3 Zehen', category: 'produce' },
      { name: 'Frischer Ingwer', amount: '1 daumengroßes Stück', category: 'produce' },
      { name: 'Garam Masala', amount: '1 TL', category: 'pantry' },
      { name: 'Kurkuma (gemahlen)', amount: '1 TL', category: 'pantry' },
      { name: 'Kreuzkümmel (gemahlen)', amount: '1 TL', category: 'pantry' },
      { name: 'Tomatenmark', amount: '1 EL', category: 'pantry' },
      { name: 'Gemüsebrühe', amount: '400ml', category: 'pantry' },
      { name: 'Bio-Zitrone', amount: '1 Stück', category: 'produce' },
      { name: 'Frischer Koriander', amount: '1 Bund', category: 'produce' },
    ],
    instructions: [
      'Basmatireis in doppelter Menge leicht gesalzenem Wasser aufkochen und 12-15 Min. zugedeckt quellen lassen.',
      'Zwiebeln, Knoblauch und Ingwer fein würfeln. In 2 EL Öl im großen Topf bei mittlerer Hitze ca. 3 Min. glasig dünsten.',
      'Garam Masala, Kurkuma, Kreuzkümmel und Tomatenmark dazugeben und unter Rühren 1 Min. sanft anrösten, bis es aromatisch duftet.',
      'Rote Linsen in einem Sieb gründlich abspülen. Mit gehackten Tomaten, Kokosmilch und Gemüsebrühe in den Topf geben.',
      'Alles aufkochen, Hitze reduzieren und ca. 18-20 Min. leicht köcheln lassen, bis die Linsen samtig weich zerfallen.',
      'Mit frischem Zitronensaft, Salz und Pfeffer abschmecken. Naan-Brot im Ofen 4 Min. aufbacken und alles mit frischem Koriander servieren.',
    ],
  },
  {
    id: 'cat_w3',
    title: 'Klassisches Chili con Carne mit Mais & Bohnen',
    prepTime: '35 Min.',
    servings: 5,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'meat',
    estimatedCost: 11.9,
    synergyBase: 'rice',
    synergyRole: 'cook-extra',
    synergyTip: 'Koche gleich 500g Reis dazu: Morgen gibt es knusprigen gebratenen Eierreis (-15 Min.)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80',
    notes: 'Würziger Familieneintopf. Schmeckt am nächsten Tag aufgewärmt fast noch besser!',
    ingredients: [
      { name: 'Rinderhackfleisch', amount: '500g', category: 'meat' },
      { name: 'Kidneybohnen (Dose)', amount: '2 Dosen (800g)', category: 'pantry' },
      { name: 'Mais (Dose)', amount: '1 Dose (300g)', category: 'pantry' },
      { name: 'Passierte Tomaten', amount: '500g', category: 'pantry' },
      { name: 'Zwiebeln', amount: '2 Stück', category: 'produce' },
      { name: 'Knoblauchzehen', amount: '2 Zehen', category: 'produce' },
      { name: 'Sauerrahm', amount: '1 Becher (200g)', category: 'dairy' },
      { name: 'Basmatireis', amount: '500g', category: 'pantry' },
      { name: 'Kreuzkümmel (gemahlen)', amount: '1 TL', category: 'pantry' },
      { name: 'Paprikapulver edelsüß', amount: '1 EL', category: 'pantry' },
    ],
    instructions: [
      'Basmatireis in gesalzenem Wasser gar kochen.',
      'Zwiebeln und Knoblauch fein hacken. In einem großen Topf mit 1 EL Öl das Rinderhack kräftig anbraten.',
      'Zwiebeln, Knoblauch, Kreuzkümmel und Paprikapulver zugeben und 3 Minuten mitrösten.',
      'Passierte Tomaten, abgetropfte Kidneybohnen und Mais unterrühren. Mit Salz und Pfeffer würzen.',
      'Bei milder Hitze zugedeckt ca. 20 Minuten sanft einköcheln lassen.',
      'Chili heiß mit Basmatireis und einem kühlen Klecks Sauerrahm servieren.',
    ],
  },
  {
    id: 'cat_w4',
    title: 'Kartoffel-Lauch-Cremesuppe mit knusprigen Bacon-Croutons',
    prepTime: '30 Min.',
    servings: 4,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'vegetarian',
    estimatedCost: 7.9,
    synergyBase: 'potatoes',
    synergyRole: 'cook-extra',
    synergyTip: 'Koche heute 1kg Kartoffeln mehr ab: Morgen gibt es knusprige Bratkartoffeln (-20 Min.)!',
    timeSavedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80',
    notes: 'Wärmende Seelenschmeichler-Suppe. Cremig püriert und herrlich deftig.',
    ingredients: [
      { name: 'Festkochende Kartoffeln', amount: '1.5kg', category: 'produce' },
      { name: 'Stangenlauch', amount: '2 Stangen', category: 'produce' },
      { name: 'Gemüsebrühe', amount: '1 Liter', category: 'pantry' },
      { name: 'Schmand', amount: '1 Becher (200g)', category: 'dairy' },
      { name: 'Bacon', amount: '100g', category: 'meat' },
      { name: 'Muskatnuss', amount: '1 Prise', category: 'pantry' },
    ],
    instructions: [
      'Kartoffeln schälen und würfeln. Lauch waschen und in Ringe schneiden.',
      'In einem Topf 1 EL Butter erhitzen, Lauch 3 Minuten andünsten.',
      'Kartoffeln und Gemüsebrühe zugeben, aufkochen und ca. 18 Minuten weich köcheln.',
      'Baconstreifen in einer Pfanne ohne Fett knusprig ausbacken, auf Küchenpapier abtropfen lassen.',
      'Die Hälfte der Kartoffeln für morgen beiseitelegen! Die restliche Suppe mit Schmand pürieren.',
      'Mit Muskat, Salz und Pfeffer abschmecken und mit krossem Bacon toppen.',
    ],
  },
  {
    id: 'cat_w5',
    title: 'Klassischer Kartoffel-Gemüse-Auflauf mit goldener Käsekruste',
    prepTime: '40 Min.',
    servings: 5,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'vegetarian',
    estimatedCost: 9.8,
    synergyBase: 'potatoes',
    synergyRole: 'cook-extra',
    synergyTip: 'Koche extra Kartoffeln mit: Morgen blitzschnelle Bratkartoffeln zubereiten (-20 Min.)!',
    timeSavedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80',
    notes: 'Der Liebling aller Generationen: Dünne Kartoffelscheiben gebacken in cremiger Kräutersauce.',
    ingredients: [
      { name: 'Kartoffeln (vorwiegend festkochend)', amount: '1.2kg', category: 'produce' },
      { name: 'Möhren', amount: '3 Stück', category: 'produce' },
      { name: 'Brokkoli', amount: '1 kleiner Kopf', category: 'produce' },
      { name: 'Schlagsahne', amount: '200ml', category: 'dairy' },
      { name: 'Vollmilch', amount: '150ml', category: 'dairy' },
      { name: 'Geriebener Gouda', amount: '180g', category: 'dairy' },
      { name: 'Muskatnuss', amount: '1 Prise', category: 'pantry' },
    ],
    instructions: [
      'Ofen auf 190°C vorheizen. Auflaufform fetten.',
      'Kartoffeln und Möhren schälen und in feine Scheiben hobeln. Brokkoli in kleine Röschen teilen.',
      'Gemüse gemischt in die Auflaufform schichten.',
      'Sahne, Milch, Salz, Pfeffer und frisch geriebene Muskatnuss verquirlen und darübergießen.',
      'Mit geriebenem Gouda bestreuen.',
      'Im Ofen ca. 35-40 Minuten backen, bis das Gemüse weich und der Käse goldbraun überkrustet ist.',
    ],
  },
  {
    id: 'cat_w6',
    title: 'Oma Martas cremiges Hühnerfrikassee mit Reis',
    prepTime: '35 Min.',
    servings: 5,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'poultry',
    estimatedCost: 12.8,
    imageUrl: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=600&q=80',
    notes: 'Zartes Hähnchen in einer feinen Mehlschwitze mit knackigem Gemüse und Kapern.',
    ingredients: [
      { name: 'Hähnchenbrustfilets', amount: '600g', category: 'meat' },
      { name: 'Champignons', amount: '250g', category: 'produce' },
      { name: 'Erbsen (TK)', amount: '150g', category: 'produce' },
      { name: 'Möhren', amount: '2 Stück', category: 'produce' },
      { name: 'Hühnerbrühe', amount: '500ml', category: 'pantry' },
      { name: 'Schlagsahne', amount: '150ml', category: 'dairy' },
      { name: 'Butter', amount: '40g', category: 'dairy' },
      { name: 'Weizenmehl', amount: '30g', category: 'pantry' },
      { name: 'Basmatireis', amount: '400g', category: 'pantry' },
    ],
    instructions: [
      'Hähnchenbrust in 500ml Brühe ca. 15 Minuten sanft gar sieden, herausnehmen und in mundgerechte Stücke zupfen. Brühe aufbewahren.',
      'Möhren würfeln, Champignons vierteln. Reis separat garen.',
      'In einem Topf Butter schmelzen, Mehl einrühren und 1 Minute anschwitzen. Nach und nach die Hühnerbrühe und Sahne unter ständigem Rühren eingießen.',
      'Möhren und Champignons in die Sauce geben und 8 Minuten köcheln lassen.',
      'Gezupftes Hähnchen und Erbsen zugeben, 3 Minuten erwärmen.',
      'Mit Zitronensaft, Salz und Pfeffer abschmecken und zum Basmatireis anrichten.',
    ],
  },
  {
    id: 'cat_w7',
    title: 'Klassisches Rindergulasch mit Salzkartoffeln',
    prepTime: '60 Min.',
    servings: 5,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'meat',
    estimatedCost: 16.5,
    synergyBase: 'potatoes',
    synergyRole: 'cook-extra',
    synergyTip: 'Koche heute extra Salzkartoffeln mit: Morgen gibt es knusprige Bratkartoffeln (-20 Min.)!',
    timeSavedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80',
    notes: 'Herrlich zart geschmortes Rindfleisch mit einer tiefen Paprika-Zwiebel-Sauce.',
    ingredients: [
      { name: 'Rindergulasch (gewürfelt)', amount: '750g', category: 'meat' },
      { name: 'Zwiebeln', amount: '500g', category: 'produce' },
      { name: 'Festkochende Kartoffeln', amount: '1.2kg', category: 'produce' },
      { name: 'Tomatenmark', amount: '2 EL', category: 'pantry' },
      { name: 'Rinderbrühe', amount: '500ml', category: 'pantry' },
      { name: 'Paprikapulver edelsüß', amount: '2 EL', category: 'pantry' },
    ],
    instructions: [
      'Fleisch portionsweise in einem Schmortopf scharf anbraten, herausnehmen.',
      'Zwiebeln grob würfeln und im Bratfett langsam 10 Minuten goldbraun dünsten.',
      'Tomatenmark und Paprikapulver einrühren, mit Brühe ablöschen.',
      'Fleisch zurück in den Topf geben, zudecken und bei milder Hitze ca. 45-50 Min. sanft butterweich schmoren.',
      'Kartoffeln schälen, vierteln und in Salzwasser ca. 20 Minuten kochen.',
      'Gulasch mit Salz und Pfeffer abschmecken und mit den heißen Salzkartoffeln servieren.',
    ],
  },
  {
    id: 'cat_w8',
    title: 'Cremige Süßkartoffel-Ingwer-Suppe mit gerösteten Kürbiskernen',
    prepTime: '20 Min.',
    servings: 4,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'vegetarian',
    estimatedCost: 7.5,
    synergyBase: 'veggies',
    synergyRole: 'use-leftovers',
    synergyTip: 'Nutzt das Ofengemüse von gestern: In nur 15 Min. samtig püriert!',
    timeSavedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80',
    notes: 'Superschnell fertig, wenn Süßkartoffeln vom Vortag da sind. Wärmend und aromatisch.',
    ingredients: [
      { name: 'Süßkartoffeln (gegart)', amount: '600g', category: 'produce' },
      { name: 'Kokosmilch (Dose)', amount: '1 Dose (400ml)', category: 'pantry' },
      { name: 'Gemüsebrühe', amount: '400ml', category: 'pantry' },
      { name: 'Frischer Ingwer', amount: '1 daumengroßes Stück', category: 'produce' },
      { name: 'Kürbiskerne', amount: '40g', category: 'pantry' },
      { name: 'Baguette', amount: '1 Laib', category: 'bakery' },
    ],
    instructions: [
      'Gegarte Süßkartoffeln mit fein geriebenem Ingwer und Gemüsebrühe im Topf aufkochen.',
      'Kokosmilch zugeben und alles mit dem Pürierstab samtig pürieren.',
      'Kürbiskerne in einer kleinen Pfanne ohne Fett 2 Minuten anrösten.',
      'Suppe mit Salz, Pfeffer und einer Prise Chili abschmecken.',
      'Baguette in Scheiben schneiden und kurz rösten.',
      'Suppe in tiefe Teller schöpfen, mit Kürbiskernen toppen und mit warmem Baguette servieren.',
    ],
  },

  // ==========================================
  // 4. BLITZSCHNELL (< 25m) (quick) - 8 Rezepte
  // ==========================================
  {
    id: 'cat_q1',
    title: 'Knuspriger Gebratener Eierreis mit Erbsen & Frühlingszwiebeln',
    prepTime: '12 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'vegetarian',
    estimatedCost: 6.5,
    synergyBase: 'rice',
    synergyRole: 'use-leftovers',
    synergyTip: 'Gekochter Reis vom Vortag brät viel knuspriger und spart 20 Min. Kochzeit!',
    timeSavedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    notes: 'Das schnellste Abendessen der Welt: Gekühlter Reis brät perfekt kross.',
    ingredients: [
      { name: 'Gekochter Basmatireis (vom Vortag)', amount: '500g', category: 'pantry' },
      { name: 'Bio-Eier', amount: '4 Stück', category: 'dairy' },
      { name: 'Erbsen (TK)', amount: '150g', category: 'produce' },
      { name: 'Möhren', amount: '2 Stück', category: 'produce' },
      { name: 'Frühlingszwiebeln', amount: '1 Bund', category: 'produce' },
      { name: 'Sojasauce', amount: '2 EL', category: 'pantry' },
      { name: 'Sesamöl', amount: '2 EL', category: 'pantry' },
      { name: 'Knoblauchzehen', amount: '2 Zehen', category: 'produce' },
    ],
    instructions: [
      'Eier in einer Schüssel verquirlen, mit 1 Prise Salz würzen. In der Pfanne mit 1 TL Öl kurz stocken lassen, herausnehmen.',
      'Möhren raspeln, Frühlingszwiebeln in Röllchen schneiden, Knoblauch hacken.',
      '2 EL Sesamöl in einer großen Pfanne oder Wok stark erhitzen. Möhren, Erbsen und Knoblauch 2 Minuten scharf anbraten.',
      'Den kalten Reis zugeben und bei hoher Hitze 4 Minuten unter Rühren kross anbraten.',
      'Sojasauce und das gestockte Rührei unterheben, Frühlingszwiebeln dazugeben.',
      'Heiß in Schalen servieren.',
    ],
  },
  {
    id: 'cat_q2',
    title: 'Pesto-Gnocchi-Pfanne mit Kirschtomaten & Mini-Mozzarella',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'pasta',
    estimatedCost: 7.9,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Gnocchi aus dem Kühlregal direkt in die Pfanne – kein Topf, kein Wasserabkochen nötig!',
    ingredients: [
      { name: 'Frische Gnocchi (Kühlregal)', amount: '600g', category: 'dairy' },
      { name: 'Basilikum-Pesto', amount: '1 Glas (190g)', category: 'pantry' },
      { name: 'Kirschtomaten', amount: '250g', category: 'produce' },
      { name: 'Mini-Mozzarellakugeln', amount: '150g', category: 'dairy' },
      { name: 'Butter', amount: '1 EL', category: 'dairy' },
    ],
    instructions: [
      'In einer großen Pfanne Butter erhitzen. Die frischen Gnocchi direkt hineingeben und bei mittlerer Hitze 6-8 Minuten goldbraun anbraten.',
      'Kirschtomaten halbieren und für 2 Minuten mit in die Pfanne geben, bis sie leicht weich werden.',
      'Pfanne von der Kochstelle nehmen. Das Basilikum-Pesto vorsichtig unterrühren.',
      'Mini-Mozzarellakugeln halbieren und unterheben, sodass sie in der Resthitze leicht schmelzen.',
      'Mit etwas frischem Pfeffer bestreuen und direkt aus der Pfanne servieren.',
    ],
  },
  {
    id: 'cat_q3',
    title: 'Schnelle Miso-Ramen mit Babyspinat & weichem Ei',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'vegetarian',
    estimatedCost: 7.2,
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
    notes: 'Wärmende japanische Nudelsuppe in Restaurant-Qualität in nur 15 Minuten.',
    ingredients: [
      { name: 'Ramen-Nudeln', amount: '300g', category: 'pantry' },
      { name: 'Miso-Paste', amount: '3 EL', category: 'pantry' },
      { name: 'Babyspinat', amount: '150g', category: 'produce' },
      { name: 'Bio-Eier', amount: '4 Stück', category: 'dairy' },
      { name: 'Frühlingszwiebeln', amount: '1 Bund', category: 'produce' },
      { name: 'Sojasauce', amount: '2 EL', category: 'pantry' },
      { name: 'Gemüsebrühe', amount: '1 Liter', category: 'pantry' },
    ],
    instructions: [
      'Eier in kochendem Wasser genau 6.5 Minuten wachsweich kochen, kalt abschrecken und pellen.',
      'Gemüsebrühe mit Sojasauce aufkochen. Hitze reduzieren und Miso-Paste mit einem Schneebesen einrühren (nicht mehr kochen lassen!).',
      'Ramen-Nudeln separat 3 Minuten kochen und abtropfen lassen.',
      'Babyspinat in 4 tiefe Schalen verteilen. Die heißen Nudeln daraufgeben.',
      'Die dampfende Brühe darüber schöpfen, sodass der Spinat sanft zusammenfällt.',
      'Halbierte Eier auflegen und mit fein gehackten Frühlingszwiebeln toppen.',
    ],
  },
  {
    id: 'cat_q4',
    title: 'Schnelle Avocado-Hähnchen-Wraps mit Kräuterschmand',
    prepTime: '10 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'poultry',
    estimatedCost: 9.5,
    synergyBase: 'chicken',
    synergyRole: 'use-leftovers',
    synergyTip: 'Nutzt das gegarte Hähnchen vom Vortag: In nur 10 Min. gerollt und fertig!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    notes: 'Perfekt für stressige Tage: Kalt oder warm gewickelt in wenigen Augenblicken.',
    ingredients: [
      { name: 'Gegarte Hähnchenbruststreifen (vom Vortag)', amount: '300g', category: 'meat' },
      { name: 'Tortilla-Wraps', amount: '6 Stück', category: 'bakery' },
      { name: 'Reife Avocados', amount: '2 Stück', category: 'produce' },
      { name: 'Kräuterschmand', amount: '1 Becher (200g)', category: 'dairy' },
      { name: 'Salatherzen', amount: '1 Packung', category: 'produce' },
      { name: 'Tomaten', amount: '2 Stück', category: 'produce' },
    ],
    instructions: [
      'Avocados und Tomaten in dünne Scheiben schneiden. Salatblätter waschen.',
      'Tortilla-Wraps kurz in der Mikrowelle oder Pfanne erwärmen.',
      'Jeden Wrap mit 1-2 EL Kräuterschmand bestreichen.',
      'Mit Salatblättern, Tomatenscheiben, Avocadostreifen und dem zarten Hähnchenfleisch belegen.',
      'Wraps fest einrollen und schräg halbieren.',
    ],
  },
  {
    id: 'cat_q5',
    title: 'Schnelle Tortellini in feiner Schinken-Erbsen-Sahnesauce',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'pasta',
    estimatedCost: 8.5,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Italienischer Restaurant-Liebling in nur einer Viertelstunde auf dem Tisch.',
    ingredients: [
      { name: 'Frische Ricotta-Tortellini', amount: '600g', category: 'dairy' },
      { name: 'Kochschinken', amount: '150g', category: 'meat' },
      { name: 'Erbsen (TK)', amount: '150g', category: 'produce' },
      { name: 'Schlagsahne', amount: '250ml', category: 'dairy' },
      { name: 'Parmesankäse', amount: '60g', category: 'dairy' },
      { name: 'Muskatnuss', amount: '1 Prise', category: 'pantry' },
    ],
    instructions: [
      'Einen Topf mit Salzwasser zum Kochen bringen. Frische Tortellini 3 Minuten gar ziehen lassen.',
      'Kochschinken in kleine Quadrate schneiden. In einer Pfanne mit 1 TL Butter 2 Minuten anbraten.',
      'Schlagsahne und Erbsen zugeben, 3 Minuten leicht köcheln lassen.',
      'Geriebenen Parmesan einrühren, mit Muskat, Salz und Pfeffer abschmecken.',
      'Die abgetropften Tortellini in die Sauce geben und 1 Minute durchschwenken.',
    ],
  },
  {
    id: 'cat_q6',
    title: 'Shakshuka – Eier in pikanter Tomaten-Paprika-Sauce mit Feta',
    prepTime: '20 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'vegetarian',
    estimatedCost: 7.8,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    notes: 'Ein-Pfannen-Wunder: Frische Eier pochieren direkt in der sämigen Tomatensauce.',
    ingredients: [
      { name: 'Bio-Eier', amount: '4 Stück', category: 'dairy' },
      { name: 'Gehackte Tomaten (Dose)', amount: '2 Dosen (800g)', category: 'pantry' },
      { name: 'Rote Paprika', amount: '2 Stück', category: 'produce' },
      { name: 'Feta-Käse', amount: '150g', category: 'dairy' },
      { name: 'Kreuzkümmel (gemahlen)', amount: '1 TL', category: 'pantry' },
      { name: 'Paprikapulver edelsüß', amount: '1 TL', category: 'pantry' },
      { name: 'Fladenbrot', amount: '1 Laib', category: 'bakery' },
    ],
    instructions: [
      'Paprika würfeln und in 2 EL Olivenöl 4 Minuten anbraten. Kreuzkümmel und Paprikapulver einrühren.',
      'Gehackte Tomaten zugeben, mit Salz und Pfeffer würzen und 8 Minuten sämig einkochen.',
      'Mit dem Löffel 4 Mulden in die Sauce drücken und die Eier vorsichtig hineinschlagen.',
      'Deckel auflegen und bei milder Hitze ca. 6 Minuten stocken lassen, bis das Eiweiß fest und das Eigelb noch flüssig ist.',
      'Feta grob darüber bröckeln.',
      'Direkt in der Pfanne mit warmem Fladenbrot zum Dippen servieren.',
    ],
  },
  {
    id: 'cat_q7',
    title: 'Knusprige Bratkartoffelpfanne mit Kräuterquark & Gurkensalat',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'vegetarian',
    estimatedCost: 6.9,
    synergyBase: 'potatoes',
    synergyRole: 'use-leftovers',
    synergyTip: 'Gekochte Kartoffeln vom Vortag braten herrlich knusprig und sparen 25 Min. Zeit!',
    timeSavedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80',
    notes: 'Echtes Wohlfühlessen. Kalte Kartoffeln vom Vortag bilden die perfekte Knusperkruste.',
    ingredients: [
      { name: 'Gekochte Kartoffeln (vom Vortag)', amount: '800g', category: 'produce' },
      { name: 'Speisequark', amount: '500g', category: 'dairy' },
      { name: 'Frischer Schnittlauch', amount: '1 Bund', category: 'produce' },
      { name: 'Frische Petersilie', amount: '1 Bund', category: 'produce' },
      { name: 'Salatgurke', amount: '1 Stück', category: 'produce' },
      { name: 'Zwiebeln', amount: '1 Stück', category: 'produce' },
      { name: 'Butterschmalz', amount: '2 EL', category: 'dairy' },
    ],
    instructions: [
      'Gekochte Kartoffeln in 0.5cm dünne Scheiben schneiden. Zwiebel fein würfeln.',
      'In einer großen schweren Pfanne Butterschmalz erhitzen. Kartoffelscheiben flach verteilen und 6 Minuten ohne Rühren knusprig braten.',
      'Wenden, Zwiebeln zugeben und weitere 5 Minuten goldbraun braten. Kräftig salzen und pfeffern.',
      'Quark mit einem Schuss Mineralwasser, gehacktem Schnittlauch, Petersilie, Salz und Pfeffer cremig rühren.',
      'Salatgurke hobeln und mit Essig, Öl, Salz und Dill als Beilagensalat anmachen.',
      'Knusprige Bratkartoffeln heiß mit Kräuterquark und Gurkensalat anrichten.',
    ],
  },
  {
    id: 'cat_q8',
    title: 'Knusprige Käse-Quesadillas mit milder Tomatensalsa',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'vegetarian',
    estimatedCost: 7.9,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    notes: 'In 10 Minuten knusprig aus der Pfanne. Außen kross und innen zart schmelzend.',
    ingredients: [
      { name: 'Tortilla-Wraps', amount: '8 Stück', category: 'bakery' },
      { name: 'Geriebener Cheddar', amount: '250g', category: 'dairy' },
      { name: 'Mais (Dose)', amount: '1 kleine Dose (150g)', category: 'pantry' },
      { name: 'Rote Paprika', amount: '1 Stück', category: 'produce' },
      { name: 'Tomatensalsa', amount: '1 Glas (250g)', category: 'pantry' },
      { name: 'Sauerrahm', amount: '1 Becher (200g)', category: 'dairy' },
    ],
    instructions: [
      'Paprika in winzige Würfel schneiden, Mais abtropfen lassen.',
      'Eine Tortilla in eine trockene Pfanne bei mittlerer Hitze legen. Mit Cheddar, Paprikawürfeln und Mais bestreuen.',
      'Eine zweite Tortilla darauflegen und leicht andrücken.',
      'Nach 3 Minuten vorsichtig wenden und backen, bis der Käse geschmolzen und die Tortilla kross ist.',
      'In Dreiecke schneiden und mit Tomatensalsa und Sauerrahm servieren.',
    ],
  },

  // ==========================================
  // 5. KINDER-HITS (kids) - 8 Rezepte
  // ==========================================
  {
    id: 'cat_k1',
    title: 'Bunte Süßkartoffel-Wedges vom Blech mit Kräuterquark',
    prepTime: '25 Min.',
    servings: 4,
    category: 'family-favorite',
    theme: 'kids',
    mainProtein: 'vegetarian',
    estimatedCost: 6.9,
    imageUrl: 'https://images.unsplash.com/photo-1518013034458-30b0ee248001?auto=format&fit=crop&w=600&q=80',
    notes: 'Natursüß und knusprig gebacken: Die gesunde Pommes-Alternative.',
    ingredients: [
      { name: 'Süßkartoffeln', amount: '800g', category: 'produce' },
      { name: 'Kartoffeln', amount: '400g', category: 'produce' },
      { name: 'Speisequark', amount: '500g', category: 'dairy' },
      { name: 'Frischer Schnittlauch', amount: '1 Bund', category: 'produce' },
      { name: 'Natives Olivenöl', amount: '3 EL', category: 'pantry' },
      { name: 'Paprikapulver edelsüß', amount: '1 TL', category: 'pantry' },
    ],
    instructions: [
      'Ofen auf 200°C Heißluft vorheizen.',
      'Süßkartoffeln und Kartoffeln waschen und in gleichmäßige Spalten (Wedges) schneiden.',
      'In einer Schüssel mit Olivenöl, Paprikapulver und 1 TL Salz vermengen.',
      'Auf einem Backblech verteilen und 22 Minuten backen, bis sie weich und an den Spitzen kross sind.',
      'Quark mit gehacktem Schnittlauch, etwas Milch und Salz glattrühren.',
      'Wedges mit dem frischen Kräuterquark zum Dippen servieren.',
    ],
  },
  {
    id: 'cat_k2',
    title: 'Knusprige Hähnchen-Nuggets vom Blech mit Ofen-Pommes',
    prepTime: '25 Min.',
    servings: 4,
    category: 'family-favorite',
    theme: 'kids',
    mainProtein: 'poultry',
    estimatedCost: 10.9,
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
    notes: 'Im Ofen gebacken mit goldgelber Cornflakes-Panade – herrlich knusprig ganz ohne Frittieren!',
    ingredients: [
      { name: 'Hähnchenbrustfilets', amount: '600g', category: 'meat' },
      { name: 'Cornflakes (ungesüßt)', amount: '150g', category: 'pantry' },
      { name: 'Bio-Eier', amount: '2 Stück', category: 'dairy' },
      { name: 'Weizenmehl', amount: '50g', category: 'pantry' },
      { name: 'Backofen-Pommes', amount: '750g', category: 'pantry' },
      { name: 'Tomatenketchup', amount: '1 Flasche', category: 'pantry' },
    ],
    instructions: [
      'Ofen auf 200°C Umluft vorheizen.',
      'Hähnchenbrust in mundgerechte Nugget-Stücke schneiden, salzen.',
      'Cornflakes in einem Gefrierbeutel mit dem Nudelholz grob zerdrücken.',
      'Panierstraße aufbauen: Mehl, verquirlte Eier und zerbröselte Cornflakes in 3 Teller füllen.',
      'Nuggets nacheinander in Mehl, Ei und Cornflakes wenden und mit den Pommes auf ein Backblech legen.',
      'Im Ofen ca. 18 Minuten backen, bis die Nuggets goldbraun und durchgebacken sind. Mit Ketchup servieren.',
    ],
  },
  {
    id: 'cat_k3',
    title: 'Selbstgemachte Schlemmer-Fischstäbchen mit Kartoffelpüree & Erbsen',
    prepTime: '25 Min.',
    servings: 4,
    category: 'family-favorite',
    theme: 'kids',
    mainProtein: 'fish',
    estimatedCost: 11.8,
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    notes: 'Aus echtem Seelachsfilet, saftig paniert mit samtigem Kartoffelpüree.',
    ingredients: [
      { name: 'Seelachsfilet (frisch)', amount: '600g', category: 'meat' },
      { name: 'Mehligkochende Kartoffeln', amount: '1kg', category: 'produce' },
      { name: 'Erbsen (TK)', amount: '300g', category: 'produce' },
      { name: 'Semmelbrösel', amount: '150g', category: 'bakery' },
      { name: 'Bio-Eier', amount: '2 Stück', category: 'dairy' },
      { name: 'Butter', amount: '40g', category: 'dairy' },
      { name: 'Vollmilch', amount: '150ml', category: 'dairy' },
    ],
    instructions: [
      'Kartoffeln schälen, würfeln und in Salzwasser ca. 18 Minuten weich kochen. Abgießen, mit warmer Milch und Butter stampfen.',
      'Erbsen in kochendem Salzwasser 4 Minuten garen.',
      'Fisch in 3cm breite Stäbchen schneiden. In Mehl, verquirltem Ei und Semmelbröseln panieren.',
      'In einer Pfanne mit reichlich Butter oder Rapsöl von beiden Seiten je 3 Minuten goldbraun ausbacken.',
      'Kartoffelpüree mit Muskat abschmecken.',
      'Fischstäbchen mit cremigem Püree und grünen Erbsen servieren.',
    ],
  },
  {
    id: 'cat_k4',
    title: 'Schnelle One-Pot-Pasta mit milder Tomaten-Sahnesauce',
    prepTime: '20 Min.',
    servings: 4,
    category: 'family-favorite',
    theme: 'kids',
    mainProtein: 'pasta',
    estimatedCost: 7.5,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Alles gart zusammen in einem Topf: Die Nudeln saugen den vollen Tomatengeschmack auf.',
    ingredients: [
      { name: 'Spaghetti', amount: '400g', category: 'pantry' },
      { name: 'Gehackte Tomaten (Dose)', amount: '2 Dosen (800g)', category: 'pantry' },
      { name: 'Gemüsebrühe', amount: '600ml', category: 'pantry' },
      { name: 'Schlagsahne', amount: '100ml', category: 'dairy' },
      { name: 'Frischer Parmesan', amount: '80g', category: 'dairy' },
      { name: 'Frisches Basilikum', amount: '1 Bund', category: 'produce' },
    ],
    instructions: [
      'In einem großen Topf die Spaghetti einmal durchbrechen.',
      'Gehackte Tomaten und warme Gemüsebrühe dazugießen.',
      'Aufkochen und unter regelmäßigem Rühren ca. 11-13 Minuten köcheln lassen, bis die Pasta al dente ist und die Sauce eindickt.',
      'Sahne und geriebenen Parmesan einrühren, mit Salz und 1 Prise Zucker abschmecken.',
      'Mit Basilikumblättern garnieren.',
    ],
  },
  {
    id: 'cat_k5',
    title: 'Mini-Frikadellen mit Kartoffelbrei & feinen Möhrchen',
    prepTime: '30 Min.',
    servings: 4,
    category: 'family-favorite',
    theme: 'kids',
    mainProtein: 'meat',
    estimatedCost: 10.9,
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80',
    notes: 'Saftige mundgerechte Mini-Buletten mit süßlichen glasierten Möhrchen.',
    ingredients: [
      { name: 'Rinderhackfleisch', amount: '500g', category: 'meat' },
      { name: 'Mehligkochende Kartoffeln', amount: '1kg', category: 'produce' },
      { name: 'Bundmöhren', amount: '500g', category: 'produce' },
      { name: 'Bio-Eier', amount: '1 Stück', category: 'dairy' },
      { name: 'Semmelbrösel', amount: '4 EL', category: 'bakery' },
      { name: 'Butter', amount: '40g', category: 'dairy' },
      { name: 'Vollmilch', amount: '150ml', category: 'dairy' },
    ],
    instructions: [
      'Kartoffeln schälen und kochen. Mit Butter und Milch zu samtigem Brei stampfen.',
      'Möhren schälen, in Scheiben schneiden und in 1 EL Butter mit 1 TL Zucker und etwas Wasser 10 Minuten glasieren.',
      'Hackfleisch mit Ei, Semmelbröseln, 1 TL Senf, Salz und Pfeffer verkneten.',
      'Zu 16 kleinen Bällchen formen und leicht flachdrücken.',
      'In der Pfanne mit etwas Öl ca. 8 Minuten von beiden Seiten saftig braten.',
      'Mit Kartoffelbrei und Möhrchen servieren.',
    ],
  },
  {
    id: 'cat_k6',
    title: 'Knusprige Gemüsepuffer mit feinem Kräuterquark',
    prepTime: '25 Min.',
    servings: 4,
    category: 'family-favorite',
    theme: 'kids',
    mainProtein: 'vegetarian',
    estimatedCost: 6.5,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    notes: 'Die leckerste Art, Kindern viel Zucchini und Möhren schmackhaft zu machen.',
    ingredients: [
      { name: 'Zucchini', amount: '2 Stück', category: 'produce' },
      { name: 'Möhren', amount: '3 Stück', category: 'produce' },
      { name: 'Kartoffeln', amount: '3 Stück', category: 'produce' },
      { name: 'Bio-Eier', amount: '2 Stück', category: 'dairy' },
      { name: 'Haferflocken', amount: '60g', category: 'pantry' },
      { name: 'Speisequark', amount: '500g', category: 'dairy' },
      { name: 'Frischer Schnittlauch', amount: '1 Bund', category: 'produce' },
    ],
    instructions: [
      'Zucchini, Möhren und Kartoffeln grob raspeln. Mit 1 TL Salz bestreuen und 5 Minuten ziehen lassen.',
      'In einem sauberen Küchentuch die Flüssigkeit kräftig ausdrücken.',
      'Mit Eiern, Haferflocken, Salz und Pfeffer zu einem Teig vermengen.',
      'In einer Pfanne mit Öl esslöffelgroße Puffer formen und je Seite ca. 4 Minuten goldbraun ausbacken.',
      'Quark mit Schnittlauch und Salz anrühren.',
      'Die warmen Puffer mit dem Kräuterquark servieren.',
    ],
  },
  {
    id: 'cat_k7',
    title: 'Milde Familien-Bolognese mit feinem Wurzelgemüse & Spaghetti',
    prepTime: '35 Min.',
    servings: 5,
    category: 'family-favorite',
    theme: 'kids',
    mainProtein: 'meat',
    estimatedCost: 11.2,
    synergyBase: 'pasta',
    synergyRole: 'cook-extra',
    synergyTip: 'Koche heute 250g Spaghetti mehr ab: Morgen gibt es den schnellen Nudelsalat (-15 Min.)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Sellerie und Möhren werden ganz fein püriert – herrlich mild-süßlich und von allen geliebt.',
    ingredients: [
      { name: 'Rinderhackfleisch', amount: '500g', category: 'meat' },
      { name: 'Spaghetti', amount: '500g', category: 'pantry' },
      { name: 'Gehackte Tomaten (Dose)', amount: '2 Dosen (800g)', category: 'pantry' },
      { name: 'Möhren', amount: '2 Stück', category: 'produce' },
      { name: 'Knollensellerie', amount: '100g', category: 'produce' },
      { name: 'Zwiebeln', amount: '1 Stück', category: 'produce' },
      { name: 'Parmesankäse', amount: '80g', category: 'dairy' },
    ],
    instructions: [
      'Möhren, Sellerie und Zwiebel im Mixer sehr fein zerkleinern.',
      'Rinderhackfleisch in einem Topf mit 1 EL Olivenöl kräftig anbraten.',
      'Das fein zerkleinerte Wurzelgemüse zugeben und 4 Minuten mitdünsten.',
      'Gehackte Tomaten angießen, salzen und bei milder Hitze ca. 25 Minuten einköcheln lassen.',
      'Spaghetti in Salzwasser al dente kochen.',
      'Sauce über die heißen Nudeln geben und mit viel Parmesan bestreuen.',
    ],
  },
  {
    id: 'cat_k8',
    title: 'Knusprige Fischstäbchen-Wraps mit Gurkensalat & milder Sauce',
    prepTime: '15 Min.',
    servings: 4,
    category: 'family-favorite',
    theme: 'kids',
    mainProtein: 'fish',
    estimatedCost: 9.5,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    notes: 'Ein toller Twist: Knusprige Fischstäbchen im weichen Wrap gerollt mit Gurkensalat.',
    ingredients: [
      { name: 'Fischstäbchen (TK)', amount: '1 Packung (15 Stk)', category: 'meat' },
      { name: 'Tortilla-Wraps', amount: '6 Stück', category: 'bakery' },
      { name: 'Salatgurke', amount: '1 Stück', category: 'produce' },
      { name: 'Salatherzen', amount: '1 Packung', category: 'produce' },
      { name: 'Remoulade', amount: '1 Tube', category: 'pantry' },
    ],
    instructions: [
      'Fischstäbchen im Backofen bei 220°C 15 Minuten goldbraun und knusprig backen.',
      'Gurke in feine Scheiben schneiden und Salatblätter waschen.',
      'Wraps kurz in der Pfanne erwärmen, mit etwas Remoulade bestreichen.',
      'Mit Salat, Gurkenscheiben und je 2-3 knusprigen Fischstäbchen belegen.',
      'Einrollen und sofort servieren.',
    ],
  },
];
