import { Recipe } from '../types';

export interface RecipeThemeDefinition {
  id: 'healthy' | 'fresh' | 'warming' | 'quick' | 'kids';
  name: string;
  icon: string;
  description: string;
  colorClass: string;
  badgeClass: string;
}

export const RECIPE_THEMES: RecipeThemeDefinition[] = [
  {
    id: 'healthy',
    name: 'Gesund & Vital',
    icon: '🥗',
    description: 'Leichte, nährstoffreiche Küche mit viel buntem Gemüse & wertvollen Proteinen',
    colorClass: 'emerald',
    badgeClass: 'bg-emerald-100 dark:bg-emerald-950/70 text-emerald-800 dark:text-emerald-300 border-emerald-300 dark:border-emerald-700',
  },
  {
    id: 'fresh',
    name: 'Frisch & Sommerlich',
    icon: '🍋',
    description: 'Knackige Salate, leichte mediterrane Pasta & frische Bowls',
    colorClass: 'teal',
    badgeClass: 'bg-teal-100 dark:bg-teal-950/70 text-teal-800 dark:text-teal-300 border-teal-300 dark:border-teal-700',
  },
  {
    id: 'warming',
    name: 'Wärmend & Deftig',
    icon: '🍲',
    description: 'Wohltuende Eintöpfe, cremige Currys, Aufläufe & traditionelle Hausmannskost',
    colorClass: 'orange',
    badgeClass: 'bg-orange-100 dark:bg-orange-950/70 text-orange-800 dark:text-orange-300 border-orange-300 dark:border-orange-700',
  },
  {
    id: 'quick',
    name: 'Blitzschnell (< 25m)',
    icon: '⚡',
    description: 'Stressfreie Feierabendgerichte in unter 25 Minuten fertig auf dem Tisch',
    colorClass: 'amber',
    badgeClass: 'bg-amber-100 dark:bg-amber-950/70 text-amber-800 dark:text-amber-300 border-amber-300 dark:border-amber-700',
  },
  {
    id: 'kids',
    name: 'Kinder-Hits',
    icon: '👶',
    description: 'Von Kindern heiß geliebt, mild gewürzt und garantiert tellerleer',
    colorClass: 'purple',
    badgeClass: 'bg-purple-100 dark:bg-purple-950/70 text-purple-800 dark:text-purple-300 border-purple-300 dark:border-purple-700',
  },
];

export const CURATED_RECIPE_CATALOG: Recipe[] = [
  // ==========================================
  // 1. GESUND & VITAL (healthy) - 8 Rezepte
  // ==========================================
  {
    id: 'cat_h1',
    title: 'Gegrillter Lachs mit Zitronen-Brokkoli & Süßkartoffeln',
    prepTime: '25 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'fish',
    estimatedCost: 16.5,
    synergyBase: 'veggies',
    synergyRole: 'cook-extra',
    synergyTip: 'Röste extra Süßkartoffeln mit: Perfekt für die cremige Suppe am Folgetag (-15 Min.)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    notes: 'Reich an Omega-3-Fettsäuren und Vitaminen. Frischer Brokkoli bleibt schön knackig.',
    ingredients: [
      { name: 'Lachsfilet (frisch)', amount: '600g', category: 'meat' },
      { name: 'Frischer Brokkoli', amount: '500g', category: 'produce' },
      { name: 'Süßkartoffeln', amount: '3 große', category: 'produce' },
      { name: 'Bio-Zitrone', amount: '1 Stück', category: 'produce' },
      { name: 'Natives Olivenöl', amount: '3 EL', category: 'pantry' },
      { name: 'Knoblauchzehen', amount: '2 Zehen', category: 'produce' },
    ],
    instructions: [
      'Süßkartoffeln in Würfel schneiden und bei 200°C 20 Min. im Ofen backen.',
      'Brokkoli in Röschen teilen, kurz blanchieren oder in der Pfanne mit Knoblauch anbraten.',
      'Lachsfilet mit Zitronensaft würzen und je Seite 3-4 Min. braten.',
      'Alles heiß servieren.',
    ],
  },
  {
    id: 'cat_h2',
    title: 'Bunte Quinoa-Power-Bowl mit Avocado & Feta',
    prepTime: '20 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'vegetarian',
    estimatedCost: 11.5,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    notes: 'Bunt, pflanzlich und proteinreich. Jeder kann seine Schale selbst garnieren.',
    ingredients: [
      { name: 'Bunter Quinoa', amount: '250g', category: 'pantry' },
      { name: 'Reife Avocados', amount: '2 Stück', category: 'produce' },
      { name: 'Salatgurke', amount: '1 Stück', category: 'produce' },
      { name: 'Kichererbsen (Dose)', amount: '1 Dose (400g)', category: 'pantry' },
      { name: 'Feta-Käse', amount: '200g', category: 'dairy' },
      { name: 'Kirschtomaten', amount: '250g', category: 'produce' },
    ],
    instructions: [
      'Quinoa in leichtem Salzwasser ca. 15 Min. gar kochen.',
      'Kichererbsen abspülen, Gurke und Tomaten schneiden.',
      'Alles in Schalen anrichten und mit Feta und Avocado garnieren.',
    ],
  },
  {
    id: 'cat_h3',
    title: 'Zitronen-Hähnchenbrust mit buntem Ofengemüse',
    prepTime: '30 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'poultry',
    estimatedCost: 13.5,
    synergyBase: 'chicken',
    synergyRole: 'cook-extra',
    synergyTip: 'Brate 1-2 Hähnchenbrüste extra: Das ergibt morgen blitzschnelle Hähnchen-Wraps (-15 Min.)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80',
    notes: 'Knuspriges Blechgericht ohne viel Abwasch. Das Hähnchen bleibt wunderbar saftig.',
    ingredients: [
      { name: 'Hähnchenbrustfilets', amount: '750g', category: 'meat' },
      { name: 'Zucchini & Paprika', amount: '3 Stück', category: 'produce' },
      { name: 'Rote Zwiebeln', amount: '2 Stück', category: 'produce' },
      { name: 'Bio-Zitronen', amount: '2 Stück', category: 'produce' },
      { name: 'Getrockneter Oregano & Thymian', amount: '2 TL', category: 'pantry' },
      { name: 'Olivenöl', amount: '3 EL', category: 'pantry' },
    ],
    instructions: [
      'Gemüse und Hähnchen in mundgerechte Stücke schneiden.',
      'Mit Olivenöl, Zitronensaft und Kräutern marinieren.',
      'Auf dem Blech bei 200°C ca. 22-25 Min. goldbraun garen.',
    ],
  },
  {
    id: 'cat_h4',
    title: 'Cremiges Süßkartoffel-Kichererbsen-Curry mit Reis',
    prepTime: '25 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'vegetarian',
    estimatedCost: 9.8,
    synergyBase: 'rice',
    synergyRole: 'cook-extra',
    synergyTip: 'Koche heute gleich 500g Reis: Morgen gibt es 12-Minuten-Bratreis (-15 Min. Kochzeit)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=600&q=80',
    notes: 'Mild-cremig mit Kokosmilch, perfekt für kalte Abende und heiß geliebt von Groß und Klein.',
    ingredients: [
      { name: 'Süßkartoffeln', amount: '2 Stück (ca. 600g)', category: 'produce' },
      { name: 'Kichererbsen (Dose)', amount: '1 Dose (400g)', category: 'pantry' },
      { name: 'Kokosmilch (Dose)', amount: '1 Dose (400ml)', category: 'pantry' },
      { name: 'Babyspinat', amount: '150g', category: 'produce' },
      { name: 'Basmatireis', amount: '450g', category: 'pantry' },
      { name: 'Mildes gelbes Currypulver', amount: '2 TL', category: 'pantry' },
    ],
    instructions: [
      'Basmatireis kochen (große Portion).',
      'Süßkartoffelwürfel in Öl anbraten, Currypulver zugeben und mit Kokosmilch ablöschen.',
      'Kichererbsen zugeben und 15 Min. sanft köcheln lassen. Zuletzt Babyspinat unterheben.',
    ],
  },
  {
    id: 'cat_h5',
    title: 'Zucchini-Nudeln mit Knoblauch-Garnelen & Cherrytomaten',
    prepTime: '20 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'fish',
    estimatedCost: 14.2,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Leichtes Low-Carb-Feierabendgericht voller Aroma und knackiger Frische.',
    ingredients: [
      { name: 'Garnelen / King Prawns (geschält)', amount: '400g', category: 'meat' },
      { name: 'Mittelgroße Zucchini', amount: '4 Stück', category: 'produce' },
      { name: 'Kirschtomaten', amount: '300g', category: 'produce' },
      { name: 'Knoblauchzehen', amount: '4 Zehen', category: 'produce' },
      { name: 'Chiliflocken & Petersilie', amount: '1 Bund', category: 'produce' },
      { name: 'Parmesankäse', amount: '50g', category: 'dairy' },
    ],
    instructions: [
      'Zucchini mit Spiralschneider in feine Nudeln schneiden.',
      'Garnelen mit gehacktem Knoblauch 3 Min. scharf in Olivenöl anbraten.',
      'Halbierte Tomaten und Zucchini-Nudeln für 2 Min. zugeben und mit Parmesan servieren.',
    ],
  },
  {
    id: 'cat_h6',
    title: 'Mediterrane Linsen-Bowl mit gebratenem Halloumi',
    prepTime: '20 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'vegetarian',
    estimatedCost: 10.5,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    notes: 'Beste pflanzliche Ballaststoffe kombiniert mit knusprig-würzigem Grillkäse.',
    ingredients: [
      { name: 'Braune Berglinsen oder Tellerlinsen', amount: '250g', category: 'pantry' },
      { name: 'Halloumi-Grillkäse', amount: '250g', category: 'dairy' },
      { name: 'Rucolasalat', amount: '125g', category: 'produce' },
      { name: 'Gelbe Paprika', amount: '1 Stück', category: 'produce' },
      { name: 'Granatapfelsirup oder Balsamico', amount: '2 EL', category: 'pantry' },
      { name: 'Walnusskerne', amount: '50g', category: 'pantry' },
    ],
    instructions: [
      'Linsen in Gemüsebrühe ca. 20 Min. bissfest garen.',
      'Halloumi in Scheiben schneiden und in der Pfanne goldgelb anbraten.',
      'Linsen mit Paprikawürfeln, Rucola, Nüssen und Dressing anrichten.',
    ],
  },
  {
    id: 'cat_h7',
    title: 'Saftige Putenmedaillons auf buntem Ratatouille-Bett',
    prepTime: '25 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'poultry',
    estimatedCost: 12.8,
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80',
    notes: 'Französischer Gemüsetraum aus Auberginen, Zucchini und aromatischen Tomaten.',
    ingredients: [
      { name: 'Putenbrustfilet / Medaillons', amount: '600g', category: 'meat' },
      { name: 'Aubergine', amount: '1 Stück', category: 'produce' },
      { name: 'Zucchini', amount: '2 Stück', category: 'produce' },
      { name: 'Gehackte Tomaten (Dose)', amount: '1 Dose (400g)', category: 'pantry' },
      { name: 'Kräuter der Provence', amount: '1 EL', category: 'pantry' },
      { name: 'Zwiebel & Knoblauch', amount: 'je 1 Stück', category: 'produce' },
    ],
    instructions: [
      'Gemüse würfeln und in Olivenöl kräftig anschwitzen, mit Tomaten 15 Min. schmoren.',
      'Putenmedaillons würzen und von beiden Seiten je 3-4 Min. zart braten.',
      'Auf dem heißen Ratatouille anrichten.',
    ],
  },
  {
    id: 'cat_h8',
    title: 'Würziger Erdnuss-Tofu mit Brokkoli & Sesam',
    prepTime: '20 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'healthy',
    mainProtein: 'vegetarian',
    estimatedCost: 9.5,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    notes: 'Knusprig gebratener Tofu in herrlich cremiger Erdnusssauce – auch für Tofu-Skeptiker!',
    ingredients: [
      { name: 'Natur-Tofu (fest)', amount: '400g', category: 'produce' },
      { name: 'Frischer Brokkoli', amount: '500g', category: 'produce' },
      { name: 'Erdnussbutter (cremig)', amount: '3 EL', category: 'pantry' },
      { name: 'Sojasauce & Ahornsirup', amount: 'je 2 EL', category: 'pantry' },
      { name: 'Sesamkörner', amount: '2 EL', category: 'pantry' },
      { name: 'Basmatireis oder Nudeln', amount: '300g', category: 'pantry' },
    ],
    instructions: [
      'Tofu in Würfel schneiden, mit 1 EL Stärke bestäuben und in Öl knusprig anbraten.',
      'Brokkoli dämpfen oder mitbraten.',
      'Erdnussbutter, Sojasauce und warmes Wasser verrühren, über den Tofu gießen und kurz eindicken.',
    ],
  },

  // ==========================================
  // 2. FRISCH & SOMMERLICH (fresh) - 8 Rezepte
  // ==========================================
  {
    id: 'cat_f1',
    title: 'Cremige Zitronen-Ricotta-Pasta mit Rucola & Pinienkernen',
    prepTime: '18 Min.',
    servings: 4,
    category: 'quick',
    theme: 'fresh',
    mainProtein: 'pasta',
    estimatedCost: 8.5,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Italienische Sommerküche pur. In der Zeit fertig, in der die Pasta kocht.',
    ingredients: [
      { name: 'Spaghetti oder Linguine', amount: '500g', category: 'pantry' },
      { name: 'Ricotta-Käse', amount: '250g', category: 'dairy' },
      { name: 'Bio-Zitronen (Abrieb & Saft)', amount: '2 Stück', category: 'produce' },
      { name: 'Rucolasalat', amount: '100g', category: 'produce' },
      { name: 'Pinienkerne', amount: '40g', category: 'pantry' },
      { name: 'Parmesankäse', amount: '80g', category: 'dairy' },
    ],
    instructions: [
      'Nudeln al dente kochen, 1 Tasse Nudelwasser auffangen.',
      'Ricotta, Zitronenabrieb, Zitronensaft und Parmesan cremig rühren.',
      'Heiße Pasta mit der Sauce vermengen, mit gerösteten Pinienkernen und Rucola toppen.',
    ],
  },
  {
    id: 'cat_f2',
    title: 'Knusprige Fisch-Tacos mit Mango-Avocado-Salsa',
    prepTime: '25 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'fresh',
    mainProtein: 'fish',
    estimatedCost: 13.9,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    notes: 'Frisch, fruchtig und leicht scharf. Der Hit bei jedem Sommer-Familienessen.',
    ingredients: [
      { name: 'Weißfischfilet (z.B. Kabeljau oder Seelachs)', amount: '500g', category: 'meat' },
      { name: 'Kleine Tortilla-Wraps', amount: '8 Stück', category: 'bakery' },
      { name: 'Reife Mango', amount: '1 Stück', category: 'produce' },
      { name: 'Avocado', amount: '1 Stück', category: 'produce' },
      { name: 'Limetten', amount: '2 Stück', category: 'produce' },
      { name: 'Frischer Koriander oder Petersilie', amount: '1 Bund', category: 'produce' },
    ],
    instructions: [
      'Fisch in Streifen schneiden, würzen und in der Pfanne braten.',
      'Mango, Avocado und Kräuter fein würfeln und mit Limettensaft abschmecken.',
      'Warme Tortillas mit Fisch und frischer Salsa füllen.',
    ],
  },
  {
    id: 'cat_f3',
    title: 'Griechischer Bauernsalat mit warmem Knoblauch-Fladenbrot',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'fresh',
    mainProtein: 'vegetarian',
    estimatedCost: 8.9,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    notes: 'Klassiker ohne Kochen für heiße Sommertage. Schmeckt wie Urlaub am Meer.',
    ingredients: [
      { name: 'Feta-Käse', amount: '250g', category: 'dairy' },
      { name: 'Salatgurken', amount: '2 Stück', category: 'produce' },
      { name: 'Reife Rispentomaten', amount: '500g', category: 'produce' },
      { name: 'Kalamata-Oliven', amount: '100g', category: 'pantry' },
      { name: 'Rote Zwiebel', amount: '1 Stück', category: 'produce' },
      { name: 'Fladenbrot (frisch)', amount: '1 Laib', category: 'bakery' },
    ],
    instructions: [
      'Gemüse grob schneiden und mit Oliven und Zwiebelringen mischen.',
      'Feta in Würfel schneiden oder im Ganzen auf den Salat legen, mit Oregano bestreuen.',
      'Fladenbrot im Toaster oder Ofen rösten und dazu reichen.',
    ],
  },
  {
    id: 'cat_f4',
    title: 'Caprese-Hähnchenbrust mit geschmolzenem Mozzarella',
    prepTime: '25 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'fresh',
    mainProtein: 'poultry',
    estimatedCost: 12.5,
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80',
    notes: 'Mit Basilikum-Pesto bestrichen und mit Tomatenscheiben und Mozzarella überbacken.',
    ingredients: [
      { name: 'Hähnchenbrustfilets', amount: '650g', category: 'meat' },
      { name: 'Frischer Mozzarella', amount: '2 Kugeln', category: 'dairy' },
      { name: 'Fleischtomaten', amount: '2 Stück', category: 'produce' },
      { name: 'Grünes Basilikum-Pesto', amount: '3 EL', category: 'pantry' },
      { name: 'Balsamico-Glace', amount: '2 EL', category: 'pantry' },
      { name: 'Baguette oder Beilagensalat', amount: '1 Stück', category: 'bakery' },
    ],
    instructions: [
      'Hähnchenbrüste anbraten und in eine Auflaufform setzen.',
      'Mit Pesto bestreichen, Tomaten- und Mozzarellascheiben darauflegen.',
      'Bei 200°C ca. 12-15 Min. überbacken, bis der Käse schmilzt.',
    ],
  },
  {
    id: 'cat_f5',
    title: 'Mediterraner Nudelsalat mit getrockneten Tomaten & Rucola',
    prepTime: '20 Min.',
    servings: 4,
    category: 'quick',
    theme: 'fresh',
    mainProtein: 'pasta',
    estimatedCost: 9.2,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Ohne schwere Mayonnaise! Perfekt auch zum Mitnehmen am nächsten Tag.',
    ingredients: [
      { name: 'Penne oder Fusilli', amount: '500g', category: 'pantry' },
      { name: 'Getrocknete Tomaten in Öl', amount: '100g', category: 'pantry' },
      { name: 'Mini-Mozzarellakugeln', amount: '150g', category: 'dairy' },
      { name: 'Rucola', amount: '100g', category: 'produce' },
      { name: 'Pinienkerne oder Sonnenblumenkerne', amount: '40g', category: 'pantry' },
      { name: 'Balsamico-Essig & Olivenöl', amount: 'je 3 EL', category: 'pantry' },
    ],
    instructions: [
      'Nudeln al dente kochen und abkühlen lassen.',
      'Tomaten klein schneiden, mit Mozzarella, Kernen und Rucola unterheben.',
      'Mit dem Balsamico-Dressing abschmecken.',
    ],
  },
  {
    id: 'cat_f6',
    title: 'Bunte Halloumi-Gemüse-Wraps mit Minz-Joghurt',
    prepTime: '18 Min.',
    servings: 4,
    category: 'quick',
    theme: 'fresh',
    mainProtein: 'vegetarian',
    estimatedCost: 10.2,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    notes: 'Schnell gerollte Wraps mit warmem Halloumi und erfrischender Gurken-Minz-Sauce.',
    ingredients: [
      { name: 'Große Tortilla-Wraps', amount: '4-6 Stück', category: 'bakery' },
      { name: 'Halloumi-Käse', amount: '250g', category: 'dairy' },
      { name: 'Griechischer Joghurt', amount: '200g', category: 'dairy' },
      { name: 'Frische Minze', amount: '1 Bund', category: 'produce' },
      { name: 'Karotten (geraspelt)', amount: '2 Stück', category: 'produce' },
      { name: 'Eisbergsalat', amount: '1 kleiner Kopf', category: 'produce' },
    ],
    instructions: [
      'Joghurt mit gehackter Minze, Knoblauch und Zitrone verrühren.',
      'Halloumi in Streifen braten.',
      'Wraps erwärmen, mit Joghurt bestreichen, mit Gemüse und Halloumi fest rollen.',
    ],
  },
  {
    id: 'cat_f7',
    title: 'Asiatischer Glasnudelsalat mit Knackgemüse & Limetten-Dressing',
    prepTime: '20 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'fresh',
    mainProtein: 'vegetarian',
    estimatedCost: 9.0,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    notes: 'Herrlich erfrischend und glutenfrei. Glasnudeln müssen nur mit kochendem Wasser übergossen werden.',
    ingredients: [
      { name: 'Glasnudeln', amount: '250g', category: 'pantry' },
      { name: 'Karotten', amount: '2 Stück', category: 'produce' },
      { name: 'Rote Paprika', amount: '1 Stück', category: 'produce' },
      { name: 'Frühlingszwiebeln', amount: '1 Bund', category: 'produce' },
      { name: 'Erdnüsse (geröstet & gesalzen)', amount: '60g', category: 'snacks' },
      { name: 'Limettensaft & Sojasauce', amount: 'je 3 EL', category: 'pantry' },
    ],
    instructions: [
      'Glasnudeln 5 Min. in heißem Wasser ziehen lassen, dann kalt abschrecken.',
      'Gemüse in feine Streifen schneiden.',
      'Mit Limetten-Sojadressing vermengen und mit Erdnüssen bestreuen.',
    ],
  },
  {
    id: 'cat_f8',
    title: 'Frische Lachs-Poke-Bowl mit Edamame, Gurke & Sesam',
    prepTime: '20 Min.',
    servings: 4,
    category: 'healthy',
    theme: 'fresh',
    mainProtein: 'fish',
    estimatedCost: 15.8,
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    notes: 'Hawaiianischer Trend: Frischer Fisch, knackiges Gemüse und aromatischer Sushireis.',
    ingredients: [
      { name: 'Frisches Lachsfilet (Sushi-Qualität oder kurz angebraten)', amount: '500g', category: 'meat' },
      { name: 'Sushireis oder Jasminreis', amount: '350g', category: 'pantry' },
      { name: 'Edamame-Bohnen (TK)', amount: '200g', category: 'produce' },
      { name: 'Avocado', amount: '2 Stück', category: 'produce' },
      { name: 'Gurke', amount: '1 Stück', category: 'produce' },
      { name: 'Sesamöl & Sojasauce', amount: 'je 2 EL', category: 'pantry' },
    ],
    instructions: [
      'Reis kochen und mit Reissessig abschmecken.',
      'Lachs würfeln und nach Wunsch kurz scharf anbraten.',
      'Schalen mit Reis füllen und mit Lachs, Edamame, Avocado und Sesam anrichten.',
    ],
  },

  // ==========================================
  // 3. WÄRMEND & DEFTIG (warming) - 8 Rezepte
  // ==========================================
  {
    id: 'cat_w1',
    title: 'Schwäbische Käsespätzle mit Röstzwiebeln & Blattsalat',
    prepTime: '25 Min.',
    servings: 5,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'vegetarian',
    estimatedCost: 9.5,
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80',
    notes: 'Reichlich würziger Bergkäse und Emmentaler mit knusprigen Röstzwiebeln.',
    ingredients: [
      { name: 'Eierspätzle (frisch)', amount: '750g', category: 'dairy' },
      { name: 'Würziger Bergkäse & Emmentaler', amount: '300g', category: 'dairy' },
      { name: 'Zwiebeln', amount: '3 große', category: 'produce' },
      { name: 'Butter', amount: '40g', category: 'dairy' },
      { name: 'Frischer Schnittlauch', amount: '1 Bund', category: 'produce' },
      { name: 'Kopfsalat', amount: '1 Kopf', category: 'produce' },
    ],
    instructions: [
      'Zwiebelringe in Butter langsam goldbraun und knusprig rösten.',
      'Spätzle abkochen oder in der Pfanne schwenken, heiß mit geriebenem Käse schichten.',
      'Mit Röstzwiebeln und Schnittlauch toppen, mit frischem Salat servieren.',
    ],
  },
  {
    id: 'cat_w2',
    title: 'Cremiges Rotes Linsen-Dal mit Naan-Brot & Reis',
    prepTime: '30 Min.',
    servings: 5,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'vegetarian',
    estimatedCost: 8.5,
    synergyBase: 'rice',
    synergyRole: 'cook-extra',
    synergyTip: 'Koche extra Basmatireis mit: Morgen gibt es den blitzschnellen gebratenen Eierreis (-15 Min.)!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=600&q=80',
    notes: 'Ein indischer Klassiker: Sättigend, wärmend und extrem kostengünstig.',
    ingredients: [
      { name: 'Rote Linsen', amount: '400g', category: 'pantry' },
      { name: 'Kokosmilch (Dose)', amount: '1 Dose (400ml)', category: 'pantry' },
      { name: 'Gehackte Tomaten (Dose)', amount: '1 Dose (400g)', category: 'pantry' },
      { name: 'Basmatireis', amount: '500g', category: 'pantry' },
      { name: 'Naan-Brot', amount: '1 Packung (2-4 Stk)', category: 'bakery' },
      { name: 'Garam Masala & Kurkuma', amount: 'je 1 TL', category: 'pantry' },
    ],
    instructions: [
      'Basmatireis kochen (große Portion für 2 Tage).',
      'Linsen mit Gewürzen, Tomaten und Kokosmilch ca. 20 Min. cremig kochen.',
      'Mit warmem Naan-Brot servieren.',
    ],
  },
  {
    id: 'cat_w3',
    title: 'Klassisches Chili sin/con Carne mit Mais & Bohnen',
    prepTime: '35 Min.',
    servings: 5,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'meat',
    estimatedCost: 11.9,
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80',
    notes: 'Würziger Familieneintopf. Schmeckt am nächsten Tag aufgewärmt noch besser!',
    ingredients: [
      { name: 'Rinderhackfleisch oder Veggie-Hack', amount: '500g', category: 'meat' },
      { name: 'Kidneybohnen (Dose)', amount: '2 Dosen (je 400g)', category: 'pantry' },
      { name: 'Mais (Dose)', amount: '1 Dose (300g)', category: 'pantry' },
      { name: 'Passierte Tomaten', amount: '500g', category: 'pantry' },
      { name: 'Zwiebeln & Knoblauch', amount: 'je 2 Stück', category: 'produce' },
      { name: 'Sauerrahm oder Creme Fraiche', amount: '1 Becher', category: 'dairy' },
    ],
    instructions: [
      'Hackfleisch mit Zwiebeln und Knoblauch scharf anbraten.',
      'Tomaten, Bohnen und Mais zugeben, mit Kreuzkümmel und Paprikapulver 20 Min. köcheln.',
      'Mit einem Klecks Sauerrahm und Baguette oder Reis servieren.',
    ],
  },
  {
    id: 'cat_w4',
    title: 'Kartoffel-Lauch-Cremesuppe mit knusprigen Bacon-Croutons',
    prepTime: '30 Min.',
    servings: 4,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'vegetarian',
    estimatedCost: 7.9,
    synergyBase: 'potatoes',
    synergyRole: 'cook-extra',
    synergyTip: 'Koche gleich 1kg Kartoffeln mehr ab: Morgen gibt es knusprige Bratkartoffeln (-20 Min.)!',
    timeSavedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80',
    notes: 'Wärmende Seelenschmeichler-Suppe. Für Vegetarier einfach ohne Schinkenwüfel.',
    ingredients: [
      { name: 'Festkochende Kartoffeln', amount: '1.5kg', category: 'produce' },
      { name: 'Stangenlauch / Porree', amount: '2 Stangen', category: 'produce' },
      { name: 'Gemüsebrühe', amount: '1 Liter', category: 'pantry' },
      { name: 'Schmand oder Sahne', amount: '1 Becher (200ml)', category: 'dairy' },
      { name: 'Schinkenwürfel oder Speck (optional)', amount: '100g', category: 'meat' },
      { name: 'Frische Muskatnuss', amount: '1 Prise', category: 'pantry' },
    ],
    instructions: [
      'Lauch und Kartoffeln würfeln, in Brühe ca. 20 Min. weich kochen.',
      'Die Hälfte der gekochten Kartoffeln für den Folgetag beiseitelegen!',
      'Restliche Suppe cremig pürieren, Sahne und Muskat einrühren und mit krossem Speck garnieren.',
    ],
  },
  {
    id: 'cat_w5',
    title: 'Klassische Lasagne al Forno mit Béchamelsauce',
    prepTime: '55 Min.',
    servings: 6,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'meat',
    estimatedCost: 13.5,
    imageUrl: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=600&q=80',
    notes: 'Das absolute Lieblings-Familiengericht für das Wochenende.',
    ingredients: [
      { name: 'Lasagneplatten', amount: '1 Packung (500g)', category: 'pantry' },
      { name: 'Gemischtes Hackfleisch', amount: '500g', category: 'meat' },
      { name: 'Gehackte Tomaten', amount: '2 Dosen', category: 'pantry' },
      { name: 'Vollmilch & Butter', amount: '500ml / 40g', category: 'dairy' },
      { name: 'Geriebener Gouda oder Mozzarella', amount: '200g', category: 'dairy' },
      { name: 'Möhren & Sellerie', amount: 'je 1 Stück', category: 'produce' },
    ],
    instructions: [
      'Bolognese aus Hackfleisch, Gemüse und Tomaten 25 Min. köcheln lassen.',
      'Schnelle Béchamelsauce aus Butter, Mehl und Milch rühren.',
      'In einer Form schichten und bei 190°C ca. 30 Min. goldbraun überbacken.',
    ],
  },
  {
    id: 'cat_w6',
    title: 'Deftiger Bauerntopf mit Hackfleisch, Kartoffeln & Paprika',
    prepTime: '30 Min.',
    servings: 5,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'meat',
    estimatedCost: 11.5,
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80',
    notes: 'Alles aus einem Topf: Herzhaft, unkompliziert und sättigend.',
    ingredients: [
      { name: 'Hackfleisch', amount: '500g', category: 'meat' },
      { name: 'Kartoffeln', amount: '800g', category: 'produce' },
      { name: 'Bunte Paprika', amount: '3 Stück', category: 'produce' },
      { name: 'Rinderbrühe', amount: '600ml', category: 'pantry' },
      { name: 'Tomatenmark', amount: '3 EL', category: 'pantry' },
      { name: 'Schmand', amount: '1 Becher', category: 'dairy' },
    ],
    instructions: [
      'Hackfleisch mit Zwiebeln und Tomatenmark anbraten.',
      'Kartoffel- und Paprikawürfel zugeben, mit Brühe aufgießen.',
      '20 Min. köcheln lassen und mit Schmand servieren.',
    ],
  },
  {
    id: 'cat_w7',
    title: 'Cremiges Hühnerfrikassee mit Erbsen, Möhren & Duftreis',
    prepTime: '35 Min.',
    servings: 5,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'poultry',
    estimatedCost: 12.5,
    imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80',
    notes: 'Milde helle Sauce mit zartem Hähnchenfleisch und feinem Gemüse.',
    ingredients: [
      { name: 'Hähnchenbrustfilet', amount: '600g', category: 'meat' },
      { name: 'Erbsen & Möhren (TK oder Glas)', amount: '300g', category: 'produce' },
      { name: 'Champignons (frisch)', amount: '200g', category: 'produce' },
      { name: 'Hühnerbrühe & Sahne', amount: '400ml / 150ml', category: 'dairy' },
      { name: 'Langkornreis', amount: '400g', category: 'pantry' },
      { name: 'Zitronensaft', amount: '1 EL', category: 'produce' },
    ],
    instructions: [
      'Reis aufsetzen.',
      'Hähnchen in Brühe gar ziehen lassen und würfeln.',
      'Helle Mehlschwitze mit Brühe und Sahne binden, Gemüse und Fleisch zugeben.',
    ],
  },
  {
    id: 'cat_w8',
    title: 'Cremige Süßkartoffel-Kokos-Suppe mit gerösteten Kernen',
    prepTime: '15 Min.',
    servings: 4,
    category: 'comfort',
    theme: 'warming',
    mainProtein: 'vegetarian',
    estimatedCost: 7.5,
    synergyBase: 'veggies',
    synergyRole: 'use-leftovers',
    synergyTip: 'Nutzt das Ofengemüse von gestern: In nur 15 Min. fertig püriert!',
    timeSavedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80',
    notes: 'Superschnell fertig, wenn Süßkartoffeln vom Vortag da sind. Sonst kurz kochen.',
    ingredients: [
      { name: 'Gegarte Süßkartoffeln / Ofengemüse', amount: '500g', category: 'produce' },
      { name: 'Kokosmilch (Dose)', amount: '1 Dose (400ml)', category: 'pantry' },
      { name: 'Gemüsebrühe', amount: '400ml', category: 'pantry' },
      { name: 'Frischer Ingwer', amount: '1 daumengroßes Stück', category: 'produce' },
      { name: 'Kürbiskerne', amount: '40g', category: 'pantry' },
      { name: 'Baguette oder Toast', amount: '4 Scheiben', category: 'bakery' },
    ],
    instructions: [
      'Süßkartoffeln mit Ingwer und Brühe aufkochen.',
      'Kokosmilch zugeben und mit dem Pürierstab samtig pürieren.',
      'Mit gerösteten Kürbiskernen und knusprigem Brot anrichten.',
    ],
  },

  // ==========================================
  // 4. BLITZSCHNELL (< 25m) (quick) - 8 Rezepte
  // ==========================================
  {
    id: 'cat_q1',
    title: 'Knuspriger Gebratener Eierreis mit Erbsen, Möhren & Frühlingszwiebeln',
    prepTime: '12 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'vegetarian',
    estimatedCost: 6.5,
    synergyBase: 'rice',
    synergyRole: 'use-leftovers',
    synergyTip: 'Gekochter Reis vom Vortag brät viel knuspriger und spart 20 Min. Kochzeit!',
    timeSavedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    notes: 'Das schnellste Abendessen der Welt: Gekühlter Reis brät perfekt kross.',
    ingredients: [
      { name: 'Gekochter Basmati- oder Jasminreis (vom Vortag)', amount: '500g', category: 'pantry' },
      { name: 'Bio-Eier', amount: '4 Stück', category: 'dairy' },
      { name: 'Erbsen & Möhren (TK)', amount: '200g', category: 'produce' },
      { name: 'Frühlingszwiebeln', amount: '1 Bund', category: 'produce' },
      { name: 'Sojasauce & Sesamöl', amount: 'je 2 EL', category: 'pantry' },
      { name: 'Knoblauch', amount: '2 Zehen', category: 'produce' },
    ],
    instructions: [
      'Eier in der Pfanne verquirlen und kurz stocken lassen, beiseitestellen.',
      'Knoblauch und Gemüse in Sesamöl anbraten.',
      'Den kalten Reis zugeben, auf hoher Hitze 4 Min. anbraten, Sojasauce und Ei unterheben.',
    ],
  },
  {
    id: 'cat_q2',
    title: 'Pesto-Gnocchi-Pfanne mit Kirschtomaten & Mini-Mozzarella',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'pasta',
    estimatedCost: 7.9,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Gnocchi aus dem Kühlregal direkt in die Pfanne – kein Wasserabkochen nötig!',
    ingredients: [
      { name: 'Frische Gnocchi (Kühlregal)', amount: '600g', category: 'dairy' },
      { name: 'Grünes Basilikum-Pesto', amount: '1 Glas (190g)', category: 'pantry' },
      { name: 'Kirschtomaten', amount: '250g', category: 'produce' },
      { name: 'Mini-Mozzarellakugeln', amount: '150g', category: 'dairy' },
      { name: 'Pinienkerne', amount: '30g', category: 'pantry' },
    ],
    instructions: [
      'Gnocchi in 2 EL Olivenöl ca. 7 Min. goldbraun und knusprig braten.',
      'Halbierte Kirschtomaten und Pesto unterrühren.',
      'Mozzarellakugeln zugeben, Deckel für 2 Min. drauf, bis der Käse schmilzt.',
    ],
  },
  {
    id: 'cat_q3',
    title: '15-Minuten Miso-Ramen mit weichem Ei & Spinat',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'vegetarian',
    estimatedCost: 8.2,
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=600&q=80',
    notes: 'Tröstende Nudelsuppe mit asiatischer Brühe, frischem Gemüse und wachsweichem Ei.',
    ingredients: [
      { name: 'Ramen- oder Mie-Nudeln', amount: '350g', category: 'pantry' },
      { name: 'Eier', amount: '4 Stück', category: 'dairy' },
      { name: 'Babyspinat', amount: '150g', category: 'produce' },
      { name: 'Miso-Paste oder Gemüsebrühe', amount: '3 EL', category: 'pantry' },
      { name: 'Frühlingszwiebeln', amount: '1 Bund', category: 'produce' },
      { name: 'Sojasauce & Sesam', amount: 'je 2 EL', category: 'pantry' },
    ],
    instructions: [
      'Eier 6,5 Min. wachsweich kochen und abschrecken.',
      'Brühe mit Miso und Sojasauce erhitzen, Nudeln 3 Min. direkt darin garen.',
      'In Schalen mit Spinat, halbierten Eiern und Frühlingszwiebeln servieren.',
    ],
  },
  {
    id: 'cat_q4',
    title: 'Schnelle Avocado-Hähnchen-Wraps mit Kräuterschmand',
    prepTime: '10 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'poultry',
    estimatedCost: 9.5,
    synergyBase: 'chicken',
    synergyRole: 'use-leftovers',
    synergyTip: 'Nutzt das gegarte Hähnchen vom Vortag: In nur 10 Min. gerollt und fertig!',
    timeSavedMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    notes: 'Perfekt für stressige Tage oder als schnelles Abendbrot.',
    ingredients: [
      { name: 'Gegarte Hähnchenbruststreifen (vom Vortag)', amount: '300g', category: 'meat' },
      { name: 'Tortilla-Wraps', amount: '4-6 Stück', category: 'bakery' },
      { name: 'Reife Avocados', amount: '2 Stück', category: 'produce' },
      { name: 'Kräuterschmand', amount: '1 Becher', category: 'dairy' },
      { name: 'Salatherzen / Rucola', amount: '1 Packung', category: 'produce' },
      { name: 'Tomaten', amount: '2 Stück', category: 'produce' },
    ],
    instructions: [
      'Wraps kurz in der Pfanne erwärmen.',
      'Mit Schmand bestreichen, mit Hähnchen, Tomatenscheiben und Avocado belegen.',
      'Fest einrollen und schräg halbieren.',
    ],
  },
  {
    id: 'cat_q5',
    title: 'Schnelle Tortellini in feiner Schinken-Erbsen-Sahnesauce',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'pasta',
    estimatedCost: 8.5,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Italienischer Restaurant-Liebling in nur einer Viertelstunde auf dem Tisch.',
    ingredients: [
      { name: 'Frische Ricotta- oder Fleisch-Tortellini', amount: '600g', category: 'dairy' },
      { name: 'Kochschinken (gewürfelt)', amount: '150g', category: 'meat' },
      { name: 'Erbsen (TK)', amount: '150g', category: 'produce' },
      { name: 'Schlagsahne oder Kochsahne', amount: '250ml', category: 'dairy' },
      { name: 'Parmesankäse', amount: '60g', category: 'dairy' },
      { name: 'Muskatnuss', amount: '1 Prise', category: 'pantry' },
    ],
    instructions: [
      'Tortellini nach Packung 3 Min. kochen.',
      'Schinken in etwas Butter anbraten, Sahne und Erbsen zugeben, 3 Min. einköcheln.',
      'Tortellini und Parmesan unterheben.',
    ],
  },
  {
    id: 'cat_q6',
    title: 'Shakshuka – Eier in pikanter Tomaten-Paprika-Sauce mit Feta',
    prepTime: '20 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'vegetarian',
    estimatedCost: 7.8,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    notes: 'Ein-Pfannen-Gericht aus dem Nahen Osten. Jeder dippt mit knusprigem Brot hinein.',
    ingredients: [
      { name: 'Bio-Eier', amount: '4-6 Stück', category: 'dairy' },
      { name: 'Gehackte Tomaten (Dose)', amount: '2 Dosen (800g)', category: 'pantry' },
      { name: 'Rote Paprika', amount: '2 Stück', category: 'produce' },
      { name: 'Feta-Käse', amount: '150g', category: 'dairy' },
      { name: 'Kreuzkümmel & Paprikapulver', amount: 'je 1 TL', category: 'pantry' },
      { name: 'Knuspriges Fladenbrot', amount: '1 Laib', category: 'bakery' },
    ],
    instructions: [
      'Paprikawürfel und Zwiebeln anbraten, Tomaten und Gewürze zugeben und 10 Min. einkochen.',
      'Mit dem Löffel 4-6 Mulden formen und die Eier hineinschlagen.',
      'Deckel drauf und bei schwacher Hitze 6 Min. stocken lassen. Feta darüberkrümeln.',
    ],
  },
  {
    id: 'cat_q7',
    title: 'Knusprige Bratkartoffelpfanne mit Kräuterquark & Gurkensalat',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'vegetarian',
    estimatedCost: 6.9,
    synergyBase: 'potatoes',
    synergyRole: 'use-leftovers',
    synergyTip: 'Gekochte Kartoffeln vom Vortag braten herrlich knusprig und sparen 25 Min. Zeit!',
    timeSavedMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80',
    notes: 'Echtes Wohlfühlessen. Schneller als jeder Lieferdienst.',
    ingredients: [
      { name: 'Gekochte Kartoffeln (vom Vortag)', amount: '800g', category: 'produce' },
      { name: 'Magerquark oder Speisequark', amount: '500g', category: 'dairy' },
      { name: 'Frischer Schnittlauch & Petersilie', amount: '1 Bund', category: 'produce' },
      { name: 'Salatgurke', amount: '1 Stück', category: 'produce' },
      { name: 'Zwiebel (fein gewürfelt)', amount: '1 Stück', category: 'produce' },
      { name: 'Butter oder Butterschmalz', amount: '2 EL', category: 'dairy' },
    ],
    instructions: [
      'Kartoffeln in Scheiben schneiden und in heißem Schmalz ca. 10 Min. goldbraun anbraten.',
      'Zwiebeln die letzten 3 Min. mitbraten.',
      'Quark mit Kräutern, Milch, Salz und Pfeffer glattrühren und mit Gurkensalat servieren.',
    ],
  },
  {
    id: 'cat_q8',
    title: 'Knusprige Käse-Quesadillas mit Bohnen-Dip & Tomatensalsa',
    prepTime: '15 Min.',
    servings: 4,
    category: 'quick',
    theme: 'quick',
    mainProtein: 'vegetarian',
    estimatedCost: 7.5,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    notes: 'Kinderleicht zubereitet in der Pfanne: Außen knusprig, innen herrlich käsig.',
    ingredients: [
      { name: 'Tortilla-Wraps', amount: '8 Stück', category: 'bakery' },
      { name: 'Geriebener Cheddar oder Gouda', amount: '250g', category: 'dairy' },
      { name: 'Schwarze Bohnen (Dose)', amount: '1 Dose (400g)', category: 'pantry' },
      { name: 'Mais (Dose)', amount: '1 kleine Dose', category: 'pantry' },
      { name: 'Tomatensalsa / Dip', amount: '1 Glas', category: 'pantry' },
      { name: 'Sauerrahm', amount: '1 Becher', category: 'dairy' },
    ],
    instructions: [
      'Wraps zur Hälfte mit Käse, Bohnen und Mais belegen und zuklappen.',
      'In der heißen Pfanne ohne Öl von beiden Seiten je 2-3 Min. backen, bis der Käse schmilzt.',
      'In Dreiecke schneiden und in Salsa und Sauerrahm dippen.',
    ],
  },

  // ==========================================
  // 5. KINDER-HITS (kids) - 8 Rezepte
  // ==========================================
  {
    id: 'cat_k1',
    title: 'Selbstgemachte Knusper-Nuggets mit Ofen-Süßkartoffel-Pommes',
    prepTime: '30 Min.',
    servings: 5,
    category: 'family-favorite',
    theme: 'kids',
    mainProtein: 'poultry',
    estimatedCost: 11.5,
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
    notes: 'Im Ofen gebacken mit knuspriger Cornflakes-Panade – viel gesünder als Fast Food!',
    ingredients: [
      { name: 'Hähnchenbrustfilet', amount: '600g', category: 'meat' },
      { name: 'Cornflakes (ungesüßt)', amount: '150g', category: 'pantry' },
      { name: 'Bio-Eier', amount: '2 Stück', category: 'dairy' },
      { name: 'Süßkartoffeln & Kartoffeln', amount: '1kg', category: 'produce' },
      { name: 'Bio-Ketchup & Kräuterquark', amount: 'je 1 Flasche / Becher', category: 'pantry' },
    ],
    instructions: [
      'Kartoffeln in Stifte schneiden, mit Olivenöl auf ein Backblech geben (200°C 25 Min.).',
      'Hähnchen in Stücke schneiden, durch Ei und zerkrümelte Cornflakes ziehen.',
      'Nuggets die letzten 15 Min. auf dem Blech mitbacken.',
    ],
  },
  {
    id: 'cat_k2',
    title: 'Bunte Nudelnester mit feiner Tomaten-Gemüse-Sauce',
    prepTime: '20 Min.',
    servings: 5,
    category: 'family-favorite',
    theme: 'kids',
    mainProtein: 'pasta',
    estimatedCost: 7.5,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Das Gemüse (Möhren & Zucchini) wird püriert – Kinder lieben den milden Geschmack.',
    ingredients: [
      { name: 'Tagliatelle oder Spaghetti', amount: '500g', category: 'pantry' },
      { name: 'Passierte Tomaten', amount: '2 Packungen (1 Liter)', category: 'pantry' },
      { name: 'Möhren', amount: '2 Stück', category: 'produce' },
      { name: 'Zucchini', amount: '1 Stück', category: 'produce' },
      { name: 'Frischer Parmesan', amount: '100g', category: 'dairy' },
      { name: 'Prise Rohrzucker & Oregano', amount: 'nach Belieben', category: 'pantry' },
    ],
    instructions: [
      'Möhren und Zucchini fein raspeln und in etwas Olivenöl dünsten.',
      'Tomaten zugeben, 10 Min. sanft köcheln und cremig pürieren.',
      'Mit gekochten Nudeln und viel geriebenem Parmesan servieren.',
    ],
  },
  {
    id: 'cat_k3',
    title: 'Mini-Pfannenpizzen zum kreativen Selbstbelegen',
    prepTime: '20 Min.',
    servings: 5,
    category: 'family-favorite',
    theme: 'kids',
    mainProtein: 'vegetarian',
    estimatedCost: 8.5,
    imageUrl: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=600&q=80',
    notes: 'Pita-Brote als Blitz-Böden! Jedes Kind belegt sein eigenes Kunstwerk.',
    ingredients: [
      { name: 'Pita-Brote oder Naan', amount: '6-8 Stück', category: 'bakery' },
      { name: 'Pizzatomatensauce', amount: '1 Glas', category: 'pantry' },
      { name: 'Geriebener Gouda & Mozzarella', amount: '250g', category: 'dairy' },
      { name: 'Mais, Paprika & Schinkenstreifen', amount: 'je 1 Dose / Stück', category: 'produce' },
    ],
    instructions: [
      'Pita-Brote mit Sauce bestreichen.',
      'Kinder belegen ihre Brote nach Lust mit Käse und Toppings.',
      'Bei 200°C 8-10 Min. überbacken, bis der Käse blubbert.',
    ],
  },
  {
    id: 'cat_k4',
    title: 'Milder Hähnchen-Reistopf mit Erbsen & Möhren',
    prepTime: '25 Min.',
    servings: 5,
    category: 'family-favorite',
    theme: 'kids',
    mainProtein: 'poultry',
    estimatedCost: 10.5,
    imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80',
    notes: 'Ein samtiges Ein-Topf-Gericht: Mild, wärmend und voll von Vitaminen.',
    ingredients: [
      { name: 'Hähnchenbrustfilet (in Würfeln)', amount: '500g', category: 'meat' },
      { name: 'Langkornreis', amount: '350g', category: 'pantry' },
      { name: 'Erbsen & Möhren (fein)', amount: '300g', category: 'produce' },
      { name: 'Milde Hühnerbrühe', amount: '750ml', category: 'pantry' },
      { name: 'Butter', amount: '30g', category: 'dairy' },
    ],
    instructions: [
      'Hähnchen in Butter anbraten.',
      'Reis und Gemüse zugeben, mit Brühe aufgießen.',
      'Bei kleiner Hitze 18 Min. quellen lassen, bis die Flüssigkeit aufgesaugt ist.',
    ],
  },
  {
    id: 'cat_k5',
    title: 'Goldgelbe Kartoffelpuffer mit frischem Bio-Apfelmus',
    prepTime: '25 Min.',
    servings: 5,
    category: 'comfort',
    theme: 'kids',
    mainProtein: 'vegetarian',
    estimatedCost: 6.5,
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=600&q=80',
    notes: 'Der unangefochtene Liebling an verregneten Nachmittagen.',
    ingredients: [
      { name: 'Kartoffeln (vorwiegend festkochend)', amount: '1.2kg', category: 'produce' },
      { name: 'Zwiebel', amount: '1 kleine', category: 'produce' },
      { name: 'Bio-Eier', amount: '2 Stück', category: 'dairy' },
      { name: 'Speisestärke oder Mehl', amount: '2 EL', category: 'pantry' },
      { name: 'Bio-Apfelmus', amount: '1 großes Glas (700g)', category: 'pantry' },
      { name: 'Öl zum Braten', amount: '4 EL', category: 'pantry' },
    ],
    instructions: [
      'Kartoffeln und Zwiebel fein raspeln und die Flüssigkeit ausdrücken.',
      'Mit Eiern, Stärke und Salz vermengen.',
      'Portionsweise in heißem Öl goldbraun und kross ausbacken, mit Apfelmus servieren.',
    ],
  },
  {
    id: 'cat_k6',
    title: 'Zucchini-Möhren-Käsepuffer mit Kräuter-Quark',
    prepTime: '20 Min.',
    servings: 5,
    category: 'healthy',
    theme: 'kids',
    mainProtein: 'vegetarian',
    estimatedCost: 7.5,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    notes: 'Gemüse versteckt in knusprigen Käsepuffern – selbst Gemüsemuffel greifen zu!',
    ingredients: [
      { name: 'Zucchini & Möhren', amount: 'je 2 Stück (ca. 500g)', category: 'produce' },
      { name: 'Geriebener Gouda', amount: '150g', category: 'dairy' },
      { name: 'Haferflocken (fein)', amount: '100g', category: 'pantry' },
      { name: 'Eier', amount: '2 Stück', category: 'dairy' },
      { name: 'Kräuterquark', amount: '1 Becher', category: 'dairy' },
    ],
    instructions: [
      'Gemüse reiben, mit Käse, Eiern und Haferflocken vermengen.',
      'Kleine Puffer formen und in der Pfanne je Seite 4 Min. backen.',
      'Frisch mit Kräuterquark genießen.',
    ],
  },
  {
    id: 'cat_k7',
    title: 'Milde Familien-Bolognese mit verstecktem Wurzelgemüse',
    prepTime: '35 Min.',
    servings: 5,
    category: 'family-favorite',
    theme: 'kids',
    mainProtein: 'meat',
    estimatedCost: 11.2,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    notes: 'Sellerie und Möhren werden im Zerkleinerer ganz fein püriert – herrlich süßlich und aromatisch.',
    ingredients: [
      { name: 'Rinderhackfleisch', amount: '500g', category: 'meat' },
      { name: 'Spaghetti oder Spiralnudeln', amount: '500g', category: 'pantry' },
      { name: 'Gehackte Tomaten', amount: '2 Dosen (800g)', category: 'pantry' },
      { name: 'Möhren & Sellerie', amount: 'je 2 Stück', category: 'produce' },
      { name: 'Frischer Parmesan', amount: '80g', category: 'dairy' },
    ],
    instructions: [
      'Gemüse sehr fein pürieren und mit Hackfleisch anbraten.',
      'Tomaten zugeben und 20 Min. köcheln lassen.',
      'Über al dente gekochte Nudeln geben und mit Parmesan servieren.',
    ],
  },
  {
    id: 'cat_k8',
    title: 'Knusprige Fischstäbchen-Wraps mit milder Remoulade & Gurkensalat',
    prepTime: '15 Min.',
    servings: 5,
    category: 'family-favorite',
    theme: 'kids',
    mainProtein: 'fish',
    estimatedCost: 9.5,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    notes: 'Ein witziger Twist: Knusprige Fischstäbchen im Wrap gerollt mit knackigem Gurkensalat.',
    ingredients: [
      { name: 'Fischstäbchen (TK, MSC)', amount: '1 Packung (15 Stk)', category: 'meat' },
      { name: 'Tortilla-Wraps', amount: '5 Stück', category: 'bakery' },
      { name: 'Salatgurke', amount: '1 Stück', category: 'produce' },
      { name: 'Kopfsalatblätter', amount: '5 große', category: 'produce' },
      { name: 'Milde Remoulade oder Joghurt-Mayo', amount: '1 Tube', category: 'pantry' },
    ],
    instructions: [
      'Fischstäbchen im Ofen oder der Pfanne knusprig backen.',
      'Wraps erwärmen, mit Remoulade bestreichen und mit Salat belegen.',
      'Je 3 Fischstäbchen hineinlegen, einrollen und servieren.',
    ],
  },
];
